### ISSUE TITLE
The Apple Pay button doesn't show

### ISSUE THREAD

**Issue by novoio** [woocommerce/woocommerce-gateway-stripe#1036]
Hello, 

I am Donovan - software engineer. I have worked on a simple eShop website with WordPress + WooCommerce. I have used this plugin for the Credit card processing.

The Stripe credit card payment works in perfect. Also, we'd like to need the Apple Pay feature for our customers easily to purchase goods on our website.

I found it that the plugin supports the Apple Pay button so I've followed all the instructions as in the link to enable the Apple Pay: https://docs.woocommerce.com/document/stripe/?_ga=2.88466587.1066420384.1568227323-1819321553.1568227323

But we're not seeing the Apple Pay button yet.

I look forward to hearing back from you soon.

Best,
Donovan

**Comment by allendav** [comment]
Hi @novoio 

Have you successfully verified your domain with Apple Pay per these instructions? https://stripe.com/docs/stripe-js/elements/payment-request-button#verifying-your-domain-with-apple-pay

And, just to be sure, you're looking on the cart page while using Safari - the Apple Pay button will only appear to the Safari browser and only on the cart page.

**Comment by novoio** [comment]
Yes, I have successfully verified the domain as per the instructions in the link.

https://prnt.sc/pg30zc

And we've tested on Safari on which the Apple Pay was enabled.

**Comment by dougaitken** [comment]
Hi @novoio 

Taking a look at your product page there - `https://drinkgifted.com/home_4` - it looks like Apple Pay isn't loading due to your customized product page layout. 

Look at a standard product page, I can see that the Apple Pay Payment Request button loads as expected - `https://drinkgifted.com/product/green-thyme-tea-mastic-superfood/`

![https://cld.wthms.co/hfHeko](https://cld.wthms.co/hfHeko+)
Image link: https://cld.wthms.co/hfHeko

I'm closing this Issue as the thread is I can see Apple Pay loading as expected, we're unable to offer support for your custom code here.

**Comment by novoio** [comment]
Hi @dougaitken ,

I am sorry for the late response. Thank you for pointing it out.
I really appreciate you for that.

All the Best,
Donovan
