### ISSUE TITLE
Cannot place order with payment request buttons for Chinese provinces

### ISSUE THREAD

**Issue by treibalen** [woocommerce/woocommerce-gateway-stripe#1065]
**Describe the bug**
Cannot place an order with Stripe payment request buttons with a shipping address in China due to an error.

**To Reproduce**
1. Click on payment request button on your product page and type in a shipping address in China:

![https://cld.wthms.co/wWGc5E](https://cld.wthms.co/wWGc5E+) 
Full Size: https://cld.wthms.co/wWGc5E

2. Receive an error:

![https://cld.wthms.co/0xWmes](https://cld.wthms.co/0xWmes+) 
Full Size: https://cld.wthms.co/0xWmes

`Shipping Province is not valid. Please enter one of the following: Yunnan / 云南, Beijing / 北京, Tianjin / 天津, Hebei / 河北, Shanxi / 山西, Inner Mongolia / 內蒙古, Liaoning / 辽宁, Jilin / 吉林, Heilongjiang / 黑龙江, Shanghai / 上海, Jiangsu / 江苏, Zhejiang / 浙江, Anhui / 安徽, Fujian / 福建, Jiangxi / 江西, Shandong / 山东, Henan / 河南, Hubei / 湖北, Hunan / 湖南, Guangdong / 广东, Guangxi Zhuang / 广西壮族, Hainan / 海南, Chongqing / 重庆, Sichuan / 四川, Guizhou / 贵州, Shaanxi / 陕西, Gansu / 甘肃, Qinghai / 青海, Ningxia Hui / 宁夏, Macau / 澳门, Tibet / 西藏, Xinjiang / 新疆
`

Related PHP Warning:

`PHP Warning:  preg_match(): Unknown modifier '&amp;' in /home/mik/woosites/woo-payment/wp-content/plugins/woocommerce-gateway-stripe/includes/payment-methods/class-wc-stripe-payment-request.php on line 987`

I tested it with Apple Pay too - the province needs to be typed manually there, but it still fails even if I use the exact same province names as in the error, such as `Yunnan`.

**Expected behavior**
To be able to place an order for any Chinese province with Stripe payment request button. 

**Additional context**
Raised in https://wordpress.org/support/topic/php-warnings-87/

Noting that I accidentally tested it with 4.1.16 as well - same error.

**Comment by wifidel** [comment]
This error not only occurs in Chinese province but also occurs in Spanish provinces.

**Comment by SiR-DanieL** [comment]
I confirm that it also happens for Spain. I tested it locally and I got the same error with a valid Spanish address.

20280056-hc

**Comment by dougaitken** [comment]
Reported in a forum post - https://wordpress.org/support/topic/multiple-addresses-errors-with-apple-pay/

**Comment by damiannep** [comment]
Another report of this happening for Spanish in 2879570-zen

**Comment by ricardo** [comment]
It looks like this error happens because WooCommerce expects China states to be formatted like: `Yunnan / 云南`, but Chrome provides a list of values like `Yunnan Sheng`.

Apple Pay doesn't provide a list of states/provinces, you need to type them manually. So, for Spanish provinces, I believe the issue is with accents. If you type `Malaga`, it's not the same as `Málaga`. - The same happened to me while testing with Brazilian billing addresses (Paraná).

To solve this, we probably need to do some mapping to adapt inputs from the PaymentRequest API and possibly match the state either with or without special characters.

**Comment by v18** [comment]
Related: #568
