### ISSUE TITLE
Add support for installments

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-gateway-stripe#1095]
p7bbVw-3uD-p2

Allow installments on credit cards. More details can be found here: https://stripe.com/docs/payments/installments

**Comment by GeoJunkie** [comment]
Requested in 2511970-zen

**Comment by allendav** [comment]
For the purpose of 4.4.0 APM-palooza, it would be best to first do a spike / estimated effort instead of aiming to close this issue in 4.4.0.  The results of the spike/estimate should be recorded here.

cc @bmccotter

**Comment by rodcul** [comment]
Hey @allendav any update on when we'll be able to process payments using oxxo with woocommerce? Cheers 😄

**Comment by Altherbishop** [comment]
Hi, we need help about how we can add the card payments in installments and the oxxo store cash payment for the woocomerce en México PLUGIN???.

we got this links for this task.

https://stripe.com/docs/payments/installments

https://stripe.com/docs/payments/oxxo

thanks for helping us

**Comment by sabas1080** [comment]
+1

**Comment by bmccotter** [comment]
Hi @Altherbishop @sabas1080 -- Oxxo will be GA with Stripe come August. We're working to implement this in the Stripe plugin as it is on our roadmap. Thank you for tagging us and we appreciate your feedback! cc @allendav @thenbrent

**Comment by Altherbishop** [comment]
> Hi @Altherbishop @sabas1080 -- Oxxo will be GA with Stripe come August. We're working to implement this in the Stripe plugin as it is on our roadmap. Thank you for tagging us and we appreciate your feedback! cc @allendav @thenbrent

Thanks for the comment, did you know if "card payments in installments" for México will be included???

https://stripe.com/docs/payments/installments

https://stripe.com/docs/payments/oxxo

@sabas1080 @allendav @thenbrent

**Comment by Urano-Gonzalez** [comment]
> For the purpose of 4.4.0 APM-palooza, it would be best to first do a spike / estimated effort instead of aiming to close this issue in 4.4.0. The results of the spike/estimate should be recorded here.
> 
> cc @bmccotter

@allendav,  any news? Thanks!!!

**Comment by bmccotter** [comment]
@Urano-Gonzalez as [mentioned above ](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1095#issuecomment-658306138)Oxxo is on our roadmap to add once we have full access to it.

**Comment by Altherbishop** [comment]
> @Urano-Gonzalez as [mentioned above ](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1095#issuecomment-658306138)Oxxo is on our roadmap to add once we have full access to it.

Hi @bmccotter you got any news about the payments in installments???

https://stripe.com/docs/payments/installments

**Comment by Urano-Gonzalez** [comment]
Thanks, If you need account for test, I can help.

**Comment by Altherbishop** [comment]
Hi @bmccotter you got any news about the payments in installments for México??? Stripe recently open the México office and they announced that option. can you help us????

https://stripe.com/docs/payments/installments

**Comment by bmccotter** [comment]
Hi @Altherbishop nothing yet in regards to timelines for WooCommerce Stripe.

**Comment by Altherbishop** [comment]
Any news about how we can add the card payments in installments and the oxxo store cash payment for the woocomerce in México PLUGIN???.

we got this links for this task.

https://stripe.com/docs/payments/installments

https://stripe.com/docs/payments/oxxo

thanks for helping us

**Comment by Altherbishop** [comment]
> Hi @Altherbishop nothing yet in regards to timelines for WooCommerce Stripe.

Hi @bmccotter  Any news about how we can add the card payments in installments and the oxxo store cash payment for the woocomerce in México PLUGIN???.

we got this links for this task.

https://stripe.com/docs/payments/installments

https://stripe.com/docs/payments/oxxo

thanks for helping us

**Comment by bmccotter** [comment]
Hi @Altherbishop no news yet. We're exploring the best ways to integrate.

cc @allendav @laurendavissmith

**Comment by stephhjacq** [comment]
Another request in 3363100-zen

**Comment by pablogtzgileta** [comment]
+1 Looking forward for this option

**Comment by alainneue** [comment]
Any news about OXXO Pay??
Some clients are starting to ask about this, but we're unable to achieve it at this time.

**Comment by joserodrigomendez** [comment]
Hello... Do you have an estimated launch date for the Stripe OXXO payment option in woocommerce plugin update?

**Comment by Urano-Gonzalez** [comment]
Seems Woocommerce don't have in their priorities work on Oxxo integration
I am starting to implement it
I expect for half of February i finish the integration
I will have all of  you in the loop!
https://wootools.dev/

**Comment by ConSumaConciencia** [comment]
Ya habrá actualizaciones para incluir Oxxo como forma de pago de Stripe en el plugin? Porfis!!!!

**Comment by Altherbishop** [comment]
> Ya habrá actualizaciones para incluir Oxxo como forma de pago de Stripe en el plugin? Porfis!!!!

Mejor me pasé a mercado pago.

**Comment by yunierescobar** [comment]
Esta es una solicitud importante para los usuarios de Woocomerce en México, uno de los mercados más grandes de latinoamérica. Por favor ténganlo en cuenta antes que muchos clientes migren a otras pasarelas de pago mejor adaptadas al mercado mexicano.

**Comment by Altherbishop** [comment]
Mejor me fui a la plataforma de MercadoPago, especializada en el mercado LATAM

**Comment by alexpereztop** [comment]
¿Cuándo estará lista la conexión Stripe-Oxxo para WooCommerce? Sin duda, Oxxo es la opción más cómoda para pagar en efectivo en México.

**Comment by lobatoreyes** [comment]
Any news of this implementation?

**Comment by reykjalin** [comment]
No news yet @lobatoreyes.

We have higher priority issues we're working on at the moment, but we're working on fitting support for OXXO into our plans for the Stripe plugin.

**Comment by Hans-101** [comment]
Wonder how much more interest must be shown in order for WC to put this on radar...

**Comment by melindahelt** [comment]
Requested at https://wordpress.org/support/topic/activar-opcion-de-cobro-pro-medio-de-oxxo/

**Comment by leonardola** [comment]
Hello everyone. I've got great news for you all. I just opened a PR for adding OXXO [here](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2115).
So we are closer to releasing it. I am still fixing the last few bits to make sure all tests pass. 

Next I will be adding support for installments

**Comment by rodcul** [comment]
@leonardola you are a LEGEND 👍 

> Next I will be adding support for installments

**Comment by leonardola** [comment]
OXXO does not allow installments. Installments are allowed on credit card payments. Because of that I am renaming this issue to handle the installments implementation. OXXO was implemented on #2066. Anyone interested in OXXO should follow that issue and corresponding PR.

**Comment by laurendavissmith** [comment]
Pausing for now while we finish OXXO and Boleto

cc/ @LCmry

**Comment by thenbrent** [comment]
I'm closing this so the [feature request board](https://woocommerce.com/feature-requests/stripe/#) can be the canonical source of tracking popularity and help determine priority in our roadmap for features, instead of a GitHub issue (which will be focused on bug backlog). We currently have both this issue and two open feature requests for the same feature.

I have reached out to the team responsible for the WooCommerce.com feature request board to find out how to add votes to an existing request. Once I can do that, I will add 16 votes to the existing [Meses sin intereses request on the board](https://woocommerce.com/feature-request/add-the-msi-stripe-payment-option-to-the-woocommerce-stripe-plugin/) to ensure your contributions and the history of demand here is properly accounted for in that system (I will also merge [this duplicate request](https://woocommerce.com/feature-request/meses-sin-intereses-feature-for-stripe-in-mexico/#) and add an additional vote from it.)

If you're coming to this issue after it's closed looking for Meses sin intereses support, please vote on the above idea.

If you commented on this issue prior to it being renamed to focus on installments requesting OXXO or Boleto support more generally, please note that those [payment methods are now available](https://woocommerce.com/document/stripe/#additional-payment-methods).

To help understand our plans for this feature, we will be focusing our near term efforts on improving the Payment Elements integration currently in the Stripe extension (under the "[new checkout experience](https://woocommerce.com/document/stripe/#new-checkout-experience)") before adding additional APMs to it or the legacy elements integration. Once the UPE integration is the default, we will begin offering additional APMs, with priority helped determine by votes on the feature request (A8C reference for the roadmap here: pc4etw-Jq-p2)

More details on closing this action for A12s here: pc4etw-IK-p2
