### ISSUE TITLE
Stripe Dispute Web Hooks

### ISSUE THREAD

**Issue by musthavetickets** [woocommerce/woocommerce-gateway-stripe#1098]
When a dispute is updated for example you have won the case. Stripe sends the charge.dispute.closed and charge.dispute.funds_reinstated to woocommerce, but the web hooks are not actioned. The woocommerce order remains onhold and no notes are added to the order.

It's really an important bit of information to know that the order is ok and as for us, pay the vendor who provided the item.

Equally you would need to know if the dispute had been lost. If all the dispute web hooks could be added to the plugin.

**Comment by Easy-Tutor** [comment]
As a shop owner I have a big problem with sepa direct disputes. With this payment method (unlike credit card) this is an endpoint, because the case is lost and there is no option to react on this. Right now the order will set to on-hold and I have to manually set the order to "failed". So it would be good, if the order would be set to "failed" immediately.

**Comment by allendav** [comment]
See also #1108

**Comment by zwiesman31** [comment]
@shendy-a8c & @v18 Any updates here?

**Comment by v18** [comment]
@zwiesman31 - thanks for the ping! It's on our list to work on asap, but work hasn't started yet. We don't have an ETA yet.
