### ISSUE TITLE
Google Pay Order Summary Doesn't Show Product Name After Selecting Shipping Address

### ISSUE THREAD

**Issue by dphyled** [woocommerce/woocommerce-gateway-stripe#1101]
**Describe the bug**
After clicking the Buy Now (Google Pay) button on a product page, the modal will show the product title and price. However, after choosing a Shipping Address, it recalculates and no longer shows the Product title/price separately.

**To Reproduce**
1. Enable Payment Request buttons in Stripe.
2. Open a single product page for a simple product that requires shipping.
3. Click "Buy Now" button, and see that product is listed with price:

![Screenshot](https://d.pr/i/FxWzlG+)
Screenshot direct link: https://d.pr/i/FxWzlG

4. Choose a shipping address, and see that the product/price is no longer displayed:

![Screenshot](https://d.pr/i/ISXq0T+)
Screenshot direct link: https://d.pr/i/ISXq0T

**Expected behavior**
Expected to still be able to see product and price broken down separately.

**Environment (please complete the following information):**
 - WordPress Version: 5.3
 - WooCommerce Version: 3.8.1
 - Stripe Plugin Version: 4.3.1

**Comment by dphyled** [comment]
Thank you! Sorry, just realized I forgot to add tags 🤦‍♂

**Comment by jrodger** [comment]
Not a problem at all, thanks for the detailed issue write-up.

**Comment by reykjalin** [comment]
By default [we don't show itemized lists](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/b8de773f953445d4c53f888e41d4aa7426455314/includes/payment-methods/class-wc-stripe-payment-request.php#L1218-L1234) when using Payment Request Buttons, so I'm not actually sure which one is correct here; the first state (itemized) or the latter (subtotals only).

When you're on the product page the data is generated using [`get_product_data()`](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/b8de773f953445d4c53f888e41d4aa7426455314/includes/payment-methods/class-wc-stripe-payment-request.php#L284-L347), wheras on the cart page the data is generated using [`build_display_items()`](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/b8de773f953445d4c53f888e41d4aa7426455314/includes/payment-methods/class-wc-stripe-payment-request.php#L1209-L1295), so there's a bit of inconsistency there. The key difference being that `get_product_data()` always results in an itemized count when `build_display_items()` (by default) does not.

What then causes the issue described here is the fact that updating the shipping details via [`updateShippingOptions()`](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/b8de773f953445d4c53f888e41d4aa7426455314/assets/js/stripe-payment-request.js#L214-L231) [always calls `build_display_items()`](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/b8de773f953445d4c53f888e41d4aa7426455314/includes/payment-methods/class-wc-stripe-payment-request.php#L858-L863) [<-- 2 links].

Because of this inconsistency this is what happens:

1. Itemized list of items (1 item) created using `get_product_data()`.
1. Customer needs to choose shipping details.
1. Once shipping address is chosen, you now only get subtotals and not an itemized list because `updateShippingOptions()` always calls `build_display_items()`.

**So how do we fix this?**

That depends on what we decide the issue is here.

* If showing an itemized list on the product page is **correct** then we need to add that logic to [`get_shipping_options()`](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/b8de773f953445d4c53f888e41d4aa7426455314/includes/payment-methods/class-wc-stripe-payment-request.php#L802-L866).
* If showing an itemized list on the product page is **incorrect** then we need to add that logic to [`get_product_data`](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/b8de773f953445d4c53f888e41d4aa7426455314/includes/payment-methods/class-wc-stripe-payment-request.php#L284-L347).

@allendav @v18 I could really use your input on how we want to fix the issue because I'm not sure what the expected behavior is here.

If we want to, this is also an opportunity to use itemized lists by default as opposed to subtotals only. Not sure why we would choose to go with one or the other, but I thought I'd throw this out there 🙂.

Also, should this configuration be an option in the settings menu or remain a filter like it is now?

**Comment by allendav** [comment]
I think "showing an itemized list on the product page is correct" - my rationale is that the order summary should display as much information is needed to fully justify the total presented - I think that may be the same as the OP's "Expected to still be able to see product and price broken down separately."
