### ISSUE TITLE
Fatal error (instead of intended "no such order" message) occurs if WC_Payment_Gateways::get_available_payment_gateways() is called during the wp_enqueue_scripts action for a payment link for a non-existent order

### ISSUE THREAD

**Issue by DavidAnderson684** [woocommerce/woocommerce-gateway-stripe#1104]
**Describe the bug**

If during the `wp_enqueue_scripts` action `WC_Payment_Gateways::get_available_payment_gateways()` is called (e.g. as is done by the official Woo Stripe payment gateway extension), then visiting a link of the form http://example.com/checkout/order-pay/123456/?pay_for_order=true&key=wc_order_a102... where the order does not exist will result in a fatal error (and "Your site is experiencing technical difficulties"), instead of the intended outcome of WooCommerce displaying its normal message "Sorry, this order is invalid and cannot be paid for."

There doesn't seem to be a clear reason why code should not be able to call that method during that hook, so, I'm reporting against WC core instead of the extension.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install the official Woo Stripe gateway
2. Visit a payment link for a non-existent order

**Expected behavior**
"Sorry, this order is invalid and cannot be paid for."

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X ] I can reproduce this bug consistently using the steps above.

**Comment by v18** [comment]
Hey @claudiosanches - I have a couple of questions for you about this issue.

The issue happens because the Stripe gateway makes a call to `WC()->payment_gateways->get_available_payment_gateways();` before enqueueing the payment scripts on the "pay for order" page.

Should Stripe be checking that an order exists before calling `get_available_payment_gateways()`? If not, is there a better way to check that Stripe should enqueue its scripts?

---

Here's a rundown of why the bug happens when calling `get_available_payment_gateways()`:

When `get_available_payment_gateways()` is executed, it checks if each payment gateway is available using `$gateway->is_available()` here:

https://github.com/woocommerce/woocommerce/blob/30d7b2ce9d4ae732d1b036bd221328e5b7e870b8/includes/class-wc-payment-gateways.php#L151

This checks works ok for most payment gateways, but BACS checks to see about the order total using `get_order_total()` here:

https://github.com/woocommerce/woocommerce/blob/30d7b2ce9d4ae732d1b036bd221328e5b7e870b8/includes/abstracts/abstract-wc-payment-gateway.php#L283

And `get_order_total()` receives `false` when getting the order since the order doesn't exist:

https://github.com/woocommerce/woocommerce/blob/30d7b2ce9d4ae732d1b036bd221328e5b7e870b8/includes/abstracts/abstract-wc-payment-gateway.php#L264

However, the value of `false` isn't checked, and getting the order total using `$order->get_total()` throws an exception.

My suggestion is that the fix needs to happen in `is_available()`, by checking if an order exists before trying to get the order total. What do you think?

**Comment by claudiosanches** [comment]
Hello @v18, I agree that we could improve `get_order_total()`, yet this plugin should avoid calling `WC()->payment_gateways->get_available_payment_gateways()`, if it's just for CSS there's no need to check for the payment gateway to be available for that order, it's possible to just check if it's enable or not.

**Comment by claudiosanches** [comment]
@v18 I just started a PR to prevent this kind of fatal error: https://github.com/woocommerce/woocommerce/pull/29314

**Comment by thenbrent** [comment]
Closing this one as the patch to WC core has addressed this error.
