### ISSUE TITLE
Total isnt recalculated for Stripe after paid order edit

### ISSUE THREAD

**Issue by mrbeardo** [woocommerce/woocommerce-gateway-stripe#1120]
After an order has been paid, and another item has been added for the customer, I cannot get the total to calculate with the remaining amount due after the extra product has been added, but it is trying to charge full amount once a new invoice has been sent (Woocommerce Stripe Payment Addon)

**Comment by v18** [comment]
Hi @mrbeardo  - I wanted to check in with you to see if this issue is still happening.

Here are instructions for updating the order items:
https://docs.woocommerce.com/document/managing-orders/#editing-or-adding-order-items

I'll close this issue for now.

If there is still an issue, please re-open this issue and reply back with the steps you take to see the problem. Thanks!
