### ISSUE TITLE
Return 2xx response for all webhooks

### ISSUE THREAD

**Issue by treibalen** [woocommerce/woocommerce-gateway-stripe#1136]
**Describe the bug**

User in 2688538-zen reported the following behaviour:

- Their app and Stripe gateway are using different endpoints.
- But they are triggering some of the same events (for example `charge.succeeded`).

The scenario:

- `charge.succeeded` event is triggered by another app
- a notification is sent to all endpoints that are using `charge.succeeded` event
- another app's endpoint gets the notification and responds with SUCCESS
- Stripe gateway LIVE endpoint also gets sent notification and responds with FAIL because Stripe gateway is in TEST mode

The whole discussion can be found here: p1581335878187400-slack-CNXMMQBDW

**Expected behavior**
Stripe gateway to respond with SUCCESS when a notification is sent to LIVE endpoint even if the gateway in TEST mode

**Comment by reykjalin** [comment]
Tagging this with `Priority: Low` as per discussion in Slack.

**Comment by allendav** [comment]
Bumping this to High. This started annoying me while working on #1200

**Comment by sun** [comment]
Coming via https://wordpress.org/support/topic/stripe-webhooks-failing/

The problem also appears when you have a single application, but two instances of the application connected to your Stripe account - live and testing - whereas testing has test mode enabled, of course.  Stripe automatically disabled and removed both webhooks for both live and testing after some days, because one of them was always failing for each triggered event.

https://stripe.com/docs/webhooks/build#return-a-2xx-status-code-quickly documents:
> To acknowledge receipt of an event, your endpoint must return a 2xx HTTP status code to Stripe. All response codes outside this range, including 3xx codes, indicate to Stripe that you did not receive the event.
> 
> If Stripe does not receive a 2xx HTTP status code, the notification attempt is repeated. After multiple failures to send the notification over multiple days, Stripe marks the event as failed and stops trying to send it to your endpoint. After multiple days without receiving any 2xx HTTP status code responses, Stripe emails you about the misconfigured endpoint, and automatically disables your endpoint soon after if unaddressed.
> 
> Because properly acknowledging receipt of the webhook notification is so important, your endpoint should return a 2xx HTTP status code prior to any complex logic that could cause a timeout.

…as well as:

> The majority of webhook issues result in 4xx and 5xx HTTP status codes. 4xx indicates Stripe was able to contact your server, but the endpoint was not valid. Double-check that the endpoint URL is correct and able to receive POST requests. 5xx usually indicates an exception on your server was not handled properly.

The client-side webhook returns a HTTP status code outside of the 2xx range under various conditions, including an invalid signature:

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/2d7e3f2fa642a3d3fe427b9af7ba6c5c2a7e0375/includes/class-wc-stripe-webhook-handler.php#L67-L76

The plugin must not return a status code outside of 2xx if the endpoint is correct.

Stripe documents [best practices](https://stripe.com/docs/webhooks/best-practices) but does not document whether there is any further logic with regard to the 2xx status codes.  There are only a few official codes available: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#Successful_responses

Created https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1437 to fix this issue.

**Comment by v18** [comment]
The Stripe gateway returns 400 for all events not validated correctly:

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/fade49f410ab83e296ed0ce24e509d5f39f11f4d/includes/class-wc-stripe-webhook-handler.php#L89

**Comment by sun** [comment]
Yes, aforementioned PR fixes the problem.

**Comment by v18** [comment]
Closing as fixed.

**Comment by studiohmh** [comment]
I'm having this issue now and don't understand what the fix was above. All webhooks are failing in Stripe and I'm getting error codes, double checked that the keys were all correct and landed here while looking into it. What is the solution on my end?

**Comment by sun** [comment]
@studiohmh The fix was in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1437 but unfortunately did not make it into the plugin back then. The mistake was corrected in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1656.  Please ensure that you have at least version `5.4.0` of the plugin installed on your site:
https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/changelog.txt
