### ISSUE TITLE
Incorrect expiry info shows cvc error message instead

### ISSUE THREAD

**Issue by shaunkuschel** [woocommerce/woocommerce-gateway-stripe#1178]
**Describe the bug**
When placing an order with live API keys, if incorrect expiration info is entered, the cvc message (`The card's security code is incorrect.`) is shown on the front end/Checkout page and in the logs, instead of correctly stating that the expiration date is incorrect.

**To Reproduce**
1. With logging enabled and live API keys, make sure all credit card info at checkout is correct except for the expiration date (change the actual expiration month to a different, incorrect month).
2. Notice the message displayed on the checkout page is `The card's security code is incorrect.`, even though the security code is correct.
3. View the Stripe logs and notice that the logs show that the cvc check failed, rather than the expiration check:

```
                            [code] => incorrect_cvc
                            [doc_url] => https://stripe.com/docs/error-codes/incorrect-cvc
                            [message] => Your card's security code is incorrect.
                            [param] => cvc
```

**Expected behavior**
When an incorrect expiration date is entered, the logs and error message should indicate that with the `invalid_expiry_month` and/or `invalid_expiry_year` error code, so that the incorrect info can be updated.

**Screenshots**

![](https://d.pr/i/aQHFQO+)
(Link to screenshot: https://d.pr/i/aQHFQO+)

**Environment (please complete the following information):**
 - WordPress Version: 5.4
 - WooCommerce Version: 4.0.1
 - Stripe Plugin Version: 4.3.3

**Additional context**
Reported on 2888827-zen

**Comment by keninbassart** [comment]
User updated us to advise that when the zip code is incorrect they are then seeing this error

![error](https://d.pr/i/d5DvvB+)
Image Link: https://d.pr/i/d5DvvB

**Comment by v18** [comment]
Related: https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1187

**Comment by reykjalin** [comment]
After talking directly with Stripe about this issue it seems there is some confusion on our part between validation that Stripe performs and then ultimately what a card issuer might responds with.

The 'invalid_expiry_month' and year aren't validated with the issuer but rather validate whether it is a valid month/year in the future:

>By default, passing address or CVC data with the card number causes the address and CVC checks to succeed. If this information isn’t specified, the value of the checks is null. **Any expiration date in the future is considered valid.**
>
> [Stripe Documentation](https://stripe.com/docs/testing) (emphasis mine)

Ultimately a card issuer can choose to decline even if the expiry date is correct.

Sometimes a card issuer will send the `incorrect_cvc` error even when the CVC is correct but the expiration date is wrong. There is unfortunately no way for Stripe to know whether the problem lies with the CVC or the expiry date so that's why you sometimes end up with the wrong error code and message.

In other cases card issuers will not return a specific error but rather a generic "card declined" error. That's what happened for me when I tried to reproduce the issue.

Ultimately there is nothing we can do to fix this issue, so I'm closing this with a `category: won't fix`.
