### ISSUE TITLE
Add support for split installments "Meses sin intereses" (MX and Latam)

### ISSUE THREAD

**Issue by alainxps** [woocommerce/woocommerce-gateway-stripe#1180]
**Describe the solution you'd like**
 The option on the plugin is not developed yet, but the API does have the info about it.

**Describe alternatives you've considered**
Add the option to charge on installments  based on country.

**Additional context**
For a wide number of mexican and latam customers, installments is the most convenient option to pay.

**Comment by Urano-Gonzalez** [comment]
+1

**Comment by macazaga** [comment]
Hi, any updates on this? It's very important to have this for Mexican customers :)

**Comment by thenbrent** [comment]
Related to #1095.

**Comment by thenbrent** [comment]
I'm closing this so the [feature request board](https://woocommerce.com/feature-requests/stripe/#) can be the canonical source of tracking popularity and help determine priority in our roadmap for features, instead of a GitHub issue (which will be focused on bug backlog). We currently have a few GitHub issues and two open feature requests for the same feature.

I have reached out to the team responsible for the WooCommerce.com feature request board to find out how to add votes to an existing request. Once I can do that, I will add 2 votes to the existing [Meses sin intereses request on the board[(https://woocommerce.com/feature-request/add-the-msi-stripe-payment-option-to-the-woocommerce-stripe-plugin/) to ensure your contributions and the history of demand here (and the related issue https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1095) is properly accounted for in that system (I will also merge [this duplicate request](https://woocommerce.com/feature-request/meses-sin-intereses-feature-for-stripe-in-mexico/#) and add an additional vote from it.)

If you're coming to this issue after it's closed, please vote on the above idea.

To help understand our plans for this feature, we will be focusing our near term efforts on improving the Payment Elements integration currently in the Stripe extension (under the "[new checkout experience](https://woocommerce.com/document/stripe/#new-checkout-experience)") before adding additional APMs to it or the legacy elements integration. Once the UPE integration is the default, we will begin offering additional APMs, with priority helped determine by votes on the feature request (A8C reference for the roadmap here: pc4etw-Jq-p2)

More details on closing this action for A12s here: pc4etw-IK-p2
