### ISSUE TITLE
Payment Request API always showing 0 tax under certain conditions

### ISSUE THREAD

**Issue by joelkarunungan** [woocommerce/woocommerce-gateway-stripe#1190]
**Describe the bug**
Countries which require taxes to be included in all price displays but show breakdown in price (excl. tax) and a separate tax line item during payment is not working correctly with the Payment Request API -- it is showing tax as always 0 and only shows full price of the item. There essentially is no breakdown between price and tax summing up as the price displayed.

**To Reproduce**
1. Set up WooCommerce Tax options to include tax in the price: "Yes, I will enter prices inclusive of tax"
2. Set Up WooCommerce Tax options to display prices in the shop including tax
3. View a product and click the Pay now button (Payment Request button).
4. The alert pops up and shows the price in full, while 0 in tax.

**Expected behavior**
1. The price should be shown excluding tax
2. The tax amount should be shown, and not 0.
3. The total amount should sum up to the price displayed (inclusive of tax).

**Environment (please complete the following information):**
 - WordPress Version 5.4.1
 - WooCommerce Version 4.1.0
 - Stripe Plugin Version 4.3.3
 - Browser [e.g. chrome, safari] and Version -- Chrome 81.0.4044.138 (Official Build) (64-bit)
 - Any other plugins installed -- none

**Additional context**
I did not check in Apple Pay if the issue also exists.

**Comment by v18** [comment]
I have a couple of questions:

> The price should be shown excluding tax

For this, shouldn't prices be displayed including tax since the setting "display prices in the shop including tax" is set.

There's a similar issue for showing shipping inclusive of tax in the Google Pay model: #1064 

> The total amount should sum up to the price displayed (inclusive of tax).

I'm not able to repro this - the total price is shown correctly. Could you provide repro steps & screenshots if this is still happening?

Here's what I see:

<img width="497" alt="Screen Shot 2021-03-02 at 5 18 26 PM" src="https://user-images.githubusercontent.com/11487924/109618795-53ad6b00-7b7b-11eb-8f63-b818889ca389.png">


For this part:

> The tax amount should be shown, and not 0.

It's covered by the issue #1411 

I'm going to close this issue for now, but feel free to re-open if there's something missing.
