### ISSUE TITLE
Allow better browser detection for Payment Request button rendering

### ISSUE THREAD

**Issue by dougaitken** [woocommerce/woocommerce-gateway-stripe#1214]
**Describe the bug**

Anything based on Chrome(ium) will show G Pay branding. 

**To Reproduce**
0. Have "Branded" set as the "Payment Request Button Type"
1. Open Microsoft Edge / Brave / Opera
2. Allow save and fill payment methods
2.1 `opera://settings/payments`
2.2 `brave://settings/payments` - no mention of a Google Account
2.3 `edge://settings/payments` - no mention of a Google Account
3. Add any payment card, such as the test `4242` one
4. Load a product page and notice the G Pay branding

**Expected behavior**

The official G Pay branding will show for only Chrome where GPay may be used. Opera is questionable since the card is saved in the browser and not G Pay. 
Edge and Brave shouldn't mention G Pay since it is not G Pay, it is that browsers implementation of the payment request API.

**Comment by luizreis** [comment]
Good catch @dougaitken! I agree that's not expected behavior.

I have one question regarding Chrome desktop, though: are you able to use your Google Pay saved cards or just the local ones? Even though I have GPay saved cards, I can only select the locally saved ones in the Payment Request API modal (p7bbVw-3af#comment-10168).

**Comment by dougaitken** [comment]
Thanks @luizreis - I missed that p2 comment originally. 

Correct - I can only select locally saved payment cards via the Payment Request modal
