### ISSUE TITLE
Detect and recreate missing Transient options after accidental deletion

### ISSUE THREAD

**Issue by nabeel-s** [woocommerce/woocommerce-gateway-stripe#1241]
Hi,

During a routine database cleanup, I accidentally deleted the transient options from Options table. This resulted in the payment request buttons not appearing on any pages of the website.

As the Stripe payments were otherwise working fine, there was no way to tell that this was causing the missing buttons. It has been a nightmare trying to identify the cause.

Other plugins automatically recreate the transient options if they are deleted from the database. However, the Stripe plugin seems to not do this, hence the buttons never reappeared.

Please fix this in a future version of the plugin.

**Comment by reykjalin** [comment]
Hi @nabeel-s! 👋 

Thank you for reporting the issue! We'll be sure to look into this.

Since this is unlikely to affect many users we'll tag this with a `Low` priority for now.

**Comment by thenbrent** [comment]
Closing this one due to lack of recent activity. That said, transients should never be considered "long lived" and relied upon (i.e. it's 100% correct that the extension should automatically recreate the transient options if they are deleted from the database.) Therefore if this is still happening, we should reopen and address it. Closing only because the lack of recent activity implies it's no longer happening.
