### ISSUE TITLE
Stripe SEPA & Woocommerce subscriptions : automatically set subscription as active when payment is captured

### ISSUE THREAD

**Issue by tejkoslav** [woocommerce/woocommerce-gateway-stripe#1294]
maybe @roykho can help with this one :crossed_fingers: 

Title says it all... I have enabled Stripe SEPA payment for Woocommerce subscriptions.

1. First payment is processed and debit card is being charged.
2. Woocommerce subscription is set to "On-hold" immidiately after order is being placed.
3. Debit card is being charged successfully after few days.
4. Stripe dashboard: after few days "Payment authorized" turned into "Payment captured" (succeeded tag at payment & the amount appeared on the stripe account).
5. Woocommerce subscription still has "On hold" status few days after "Payment captured" was stated

**My question is very simple:**
How can I automatically **set status of woocommerce order to "Processing"** _(subscription will change to Active consequently automatically)_ when Stripe's payment status changes from "Payment authorized" to "Payment captured"?

_(btw. subsription via credit card payment option works as it should)_

I'm not a programmer but I suppose that few lines of code should do it since it's just a status change via API.

I'd really be helpful for all the help...

regards,
Toslav

**Comment by kmindi** [comment]
I have created a plugin for this (if I understand it correctls), you can have a look at the code here: https://github.com/kmindi/wc-stripe-asynchronous-payments-pending-to-payment-complete

**Comment by jrodger** [comment]
Thanks for writing up your question so clearly @tejkoslav.

Since credit card payments work as expected, my initial thought is that subscriptions should be made active once the SEPA payment completes successfully. However, there may be a good reason this isn't happen, so I've tagged this as a "question" for now. If it turns out there is a problem in the expected behaviour we can change this to "bug".

**Comment by tejkoslav** [comment]
Yeah... I've also written to Stripe and they said it should change to "Processing" when payment is captured (that usually happens after 5-7 days after purchase) or at least after 14 days (which should be maximum SEPA's time to get succesful/notsuccessful status). But it doesn't change; so it seems to be a bug yes.

**Comment by v18** [comment]
Hi there! I tried this scenario out using Stripe's [SEPA test account number](https://stripe.com/docs/testing#sepa-test-account-numbers) `DE08370400440532013003`, for which the payment "status transitions from processing to succeeded after three minutes."

Here are the steps:
1. Check out with Subscription, use `DE08370400440532013003` to check out with SEPA
2. See that Subscription status is `On hold.`
3. See that the Order status is `On hold`
4. See webhook `charge.succeeded` arrives after 3 minutes
5. See Order status change from `On hold` to `Processing`, as expected
6. See Subscription status change from `On hold` to `Active`, as expected.

Here are screenshots showing the status changes via Subscription and Order notes:

<img width="302" alt="subscription_notes" src="https://user-images.githubusercontent.com/11487924/117534793-e65fff80-b02d-11eb-99d8-2c7ae5649ebb.png">

<img width="304" alt="order_notes" src="https://user-images.githubusercontent.com/11487924/117534795-e8c25980-b02d-11eb-975b-b0d982f7519f.png">

I'm closing this issue as fixed. Please feel free to re-open if there's a problem I didn't address.

**Comment by kmindi** [comment]
@v18 I believe it should have worked like that always, and it is nice to have these delayed testing IBANs (they were not available from the beginning). Very important compared to credit card payments is that you have the webhook in place, as the charged information comes in later and not during the purchchase! So that is another part that can prevent SEPA and subscriptions to work as expected.

For others that stumple over this. The challenge with SEPA and subscriptions is, that there will be a very long (I mean 1-2 weeks) period where the payment is being "processed" and the subscription is on-hold (meaning often or usually for digital/virtual products that the customer has no access to the content of the subscription during that time). For this you might trust the customer and his/her IBAN/payment to go through and just activate the subscription while SEPA payment is still in progress (it might fail!) with the mentioned extension/code of me (and order status control plugin and making the product virtual if applicable).

This is propabably not the recommended approach as you might have a lot of customers that exploit this and then you don't want this, but for having continuous access to subscriptions it works pretty good from my experience with German customers so far.

**Comment by luismgl** [comment]
> @v18 I believe it should have worked like that always, and it is nice to have these delayed testing IBANs (they were not available from the beginning). Very important compared to credit card payments is that you have the webhook in place, as the charged information comes in later and not during the purchchase! So that is another part that can prevent SEPA and subscriptions to work as expected.
> 
> For others that stumple over this. The challenge with SEPA and subscriptions is, that there will be a very long (I mean 1-2 weeks) period where the payment is being "processed" and the subscription is on-hold (meaning often or usually for digital/virtual products that the customer has no access to the content of the subscription during that time). For this you might trust the customer and his/her IBAN/payment to go through and just activate the subscription while SEPA payment is still in progress (it might fail!) with the mentioned extension/code of me (and order status control plugin and making the product virtual if applicable).
> 
> This is propabably not the recommended approach as you might have a lot of customers that exploit this and then you don't want this, but for having continuous access to subscriptions it works pretty good from my experience with German customers so far.

Hi Kai,
thanks for developing this plugin. Although it's not an ideal solution since we need to trust the client, this would work for us right now.

Just one thing, we installed the plugin and it didn't have any effect when purchasing a subscription via SEPA. The subscription is still On Hold. I see the code hasn't been updated since 2018, is there any chance you could update it or give me some insight on what might be the problem?

**Comment by kmindi** [comment]
THe code is still working, no update needed. You need to make sure autocomplete orders plugin (from woocommerce) is already set up to really autocomplete orders at all (in my case for subscriptions I set it to autocomplete virtual orders). I'm happy if you create a ticket at my plugin repo to not create a discussion here.
