### ISSUE TITLE
Apple Pay - doesn't seem to check if apple-developer-merchantid-domain-association is already there

### ISSUE THREAD

**Issue by patrick-leb** [woocommerce/woocommerce-gateway-stripe#1298]
**Describe the bug**
My site was up and running with Apple Pay, Stripe validated the `apple-developer-merchantid-domain-association` file, however `.well-known/apple-developer-merchantid-domain-association` was on read only for nginx.
This caused the error message `Error: Unable to copy domain association file to domain root.`

**To Reproduce**
Upload manually `apple-developer-merchantid-domain-association` to `/.well-known` and `chown` ./well-known to another user, with the webserver on read-only permission

**Expected behavior**
The plugin should check if `apple-developer-merchantid-domain-association` is already there and readable before throwing an error that the folder is not writable.
Ideally the files should be compared and maybe and error can be thrown specifically if the MD5 doesn't match.

**Environment (please complete the following information):**
 - WordPress Version: 5.5.1
 - WooCommerce Version: 4.4.1
 - Stripe Plugin Version: 4.5.2 
 - Safari 13.1.1

**Comment by reykjalin** [comment]
Hello @patrick-leb! 👋 

Thank you for reporting this issue!

Since this seems to be an issue in the server environment (file permissions) I'm not sure whether this is something we can handle on our side, but we'll see what we can do!

Because this issue is related to an uncommon environment setup I'm tagging this as `Low` priority.
