### ISSUE TITLE
Stripe Apple Pay requires Phone Number - Need to remove this requirement 

### ISSUE THREAD

**Issue by bmccotter** [woocommerce/woocommerce-gateway-stripe#1303]
**Describe the bug**
User in this forum topic has set the Phone field as optional, but Apple Pay requires them to enter that field because we have requestPayerPhone: true

https://wordpress.org/support/topic/payment-request-buttons-requires-phone-nr/

**Expected behavior**
Per Stripe's documentation the phone number is optional and not a requirement. https://stripe.com/docs/apple-pay/best-practices

**Comment by bmccotter** [comment]
@allendav adding this to our agenda for discussion and prioritization given AP promotion.

**Comment by RadoslavGeorgiev** [comment]
I was just about to open a separate issue for this, but I'll add it here:

**Describe the bug**

The `requestPayerPhone` parameter [is hardcoded](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/assets/js/stripe-payment-request.js#L318) for all payment requests. The `billing_phone` checkout field is required by default, but this behavior can be changed.

**Expected behavior**

If the phone field is not required during checkout, it should not be required for payment requests.

**Suggested changes**

`WC_Countries::get_address_fields()` contains this code:

```php
$address_fields['billing_phone'] = array(
	'label'        => __( 'Phone', 'woocommerce' ),
	'required'     => 'required' === get_option( 'woocommerce_checkout_phone_field', 'required' ),
	// ...
)
```

The `woocommerce_checkout_phone_field` option is checked for those values within core:

- `required`
- `hidden`

However, it's only retrieved and never set. **Am I missing something in core?**

---

Even if we retrieve the `woocommerce_checkout_phone_field` setting, it's value is added to an array of address fields, which goes through `woocommerce_billing_fields` and `woocommerce_shipping_fields` filters, so its value could be modified by plugins like Checkout Fields Editor.

With this in mind, the only reliable option I see is to call `WC_Countries::get_address_fields()` within our `scripts` method, and check whether the phone field is required. The downside is that this method includes some heavy filters and should probably not be called outside of the checkout page.

**Comment by Camilo517** [comment]
Only bugs come out but no updates fixing them Is there a date for a next update fixing all these important bugs?

**Comment by bmccotter** [comment]
@Camilo517 we just created this as an issue yesterday and are working to get this in our next sprint.

**Comment by Camilo517** [comment]
Okey and  #1261 @bmccotter ?

**Comment by dechov** [comment]
> However, it's only retrieved and never set. Am I missing something in core?

@RadoslavGeorgiev I've found the code that defines the checkout field controls (in the Customizer) [here](https://github.com/woocommerce/woocommerce/blob/73deab28a5535ff049f61c5529e186b8837352f2/includes/customizer/class-wc-shop-customizer.php#L685-L716).

Thinking about it, it seems more reasonable to me that the specific `woocommerce_checkout_phone_field` option would control this matter (of requesting the phone number in the payment request) than for the overall address fields to control it – I don't think merchants would expect the latter (or Checkout Field Editor) to influence the fields that show up in the browser payment form in general. Thoughts on simply reading the one option value?

**Comment by RadoslavGeorgiev** [comment]
@dechov thank you for finding that code! I didn't know that the checkout is customizable through the customizer and would've never thought of it.

Now that I know where the option is coming from, I think using it for payment requests makes a lot of sense. The only reason against it would be that checkout fields are customizable through extensions, but when that's done, the phone field might be completely missing, or have a different name, etc., so that route is not too reliable either.

I'm all 👍 to use the `woocommerce_checkout_phone_field` option.
