### ISSUE TITLE
Support BACS direct debits (UK)

### ISSUE THREAD

**Issue by DavidAnderson684** [woocommerce/woocommerce-gateway-stripe#1322]
In the last few months, Stripe began support for UK direct debits (BACS) - https://stripe.com/docs/payments/payment-methods/bacs-debit . These are a popular payment method in the UK, being the only way that allows a vendor to get permission to directly charge a customer's bank account, indefinitely. The customer has power to cancel the permission at any time from their bank account - this control makes debits popular with customers.

Feature request: please add support for this payment method within the plugin.

**Comment by DavidAnderson684** [comment]
Some stats on the popularity: https://www.bacs.co.uk/Resources/FactsAndFigures/Pages/AnnualProcessingStatistics.aspx - total direct debit volumes processed in 2019 were £4.4 billion, i.e around $5.7 billion. Note on that page - "All payment figures are 000,s". There are around 501 million active direct debits, which is around 8 per member of the population.

**Comment by michael-sumner** [comment]
We have a large customer with this request and it would benefit Stripe greatly to have this feature.

**Comment by Peter-HVD** [comment]
I too have a need for this. It's been 2½ years since this ticket was raised and, to be frank, it's a disgrace that it hasn't yet been implemented.

**Comment by thenbrent** [comment]
Closing this one as the [corresponding feature request](https://woocommerce.com/feature-request/bacs-direct-debit/#) on the feature request board will be used to track its popularity to help determine its priority in our roadmap instead of a GitHub issue (which will be focused on bug backlog).

To help understand our plans for this feature, we will be focusing our near term efforts on improving the UPE integration currently in the Stripe extension (under the "[new checkout experience](https://woocommerce.com/document/stripe/#new-checkout-experience)") before adding additional APMs to it or the  legacy elements integration. Once the UPE integration is the default, we will begin offering additional APMs, like BACs (A8C reference for the roadmap here: pc4etw-Jq-p2)

ACH currently 2nd most popular feature request, and it is likely we will handle bank debit methods as a singular project with Bacs and BECs as part of that.

**Comment by DavidAnderson684** [comment]
@thenbrent It's a bit unfortunate that all the people who already registered their desire for it by up-voting the request here won't have those votes transferred into the new system - effectively they've registered a desire for it, but now that will be lost.

**Comment by thenbrent** [comment]
@DavidAnderson684 that's fair. I've requested 6 votes be added to the [BACs feature request](https://woocommerce.com/feature-request/bacs-direct-debit/#) just in case the votes from unique people here have not already been added there.

I'd also like to clarify what I was getting at with this part of my previous comment:

> ACH currently 2nd most popular feature request, and it is likely we will handle bank debit methods as a singular project with Bacs and BECs as part of that.

What I'm saying there is that BACs is likely to be prioritized based on ACH rather than the [BACs feature request](https://woocommerce.com/feature-request/bacs-direct-debit/#), and the ACH request given the similarities and the ACH request has a much high vote count making direct debit payment methods a much higher priority than that which is reflected in the BACs request alone. That's why I didn't transfer the votes initially like I'd requested for other issues I was closing.

That said, I do think it is a good idea to have these votes transferred in case the above statement changes.
