### ISSUE TITLE
Add setting to allow merchants to process as an authorization if local pickup shipping is selected

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-gateway-stripe#1324]
and then the merchant can capture the payment when the goods are picked up. By adding a new setting, captures can continue to happen automatically for other shipping methods

props @bmccotter

**Comment by thenbrent** [comment]
Closing this due to lack of demand / activity the last 3 years. The [feature request board](https://woocommerce.com/feature-requests/stripe/#) will also now be used to track popularity and help determine priority in our roadmap for features, instead of a GitHub issue (which will be focused on bug backlog).
