### ISSUE TITLE
Add Inbox Note promoting Apple Pay

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-gateway-stripe#1351]
Headline: Boost online sales with Apple Pay

Copy: Grow your business by making checkout easy with Apple Pay and Stripe

CTA (Button) - Get Started - and it should take them to the Apple Pay landing page https://woocommerce.com/apple-pay/

**Comment by thenbrent** [comment]
Additional requirements from Slack thread:

* Display to US merchants only
* Should be shown to "net new merchants", which can be defined as merchants that installed the Stripe extension 7 days ago
* Body copy should include the registered mark in superscript (per trademark guidelines) so it should read

> Grow your business by making checkout easy with Apple Pay® and Stripe

**Comment by bmccotter** [comment]
Hi All - approved copy and guidance from Apple Pay:

US Stripe Merchants - relatively new to Stripe, triggered after ~7 days or so:

This is the deep link to the guide https://developer.apple.com/apple-pay/marketing/ 



**Option 1**:

 Headline: Boost sales this holiday season with Apple Pay!

 Body: Now that you accept Apple Pay® with Stripe, you can boost sales by letting your customers know that Apple Pay is a simple and secure way to pay.

 CTA: Here’s a marketing guide to help you get started

 

 **Option 2 :**

 Headline: Boost sales this holiday season with Apple Pay!

 Body: Now that you accept Apple Pay® with Stripe, you can increase conversion rates by letting your customers know that Apple Pay is available.

 CTA: Here’s a marketing guide to help you get started

**Comment by thenbrent** [comment]
@bmccotter reads well to me.

> US Stripe Merchants - relatively new to Stripe, triggered after ~7 days or so:

Given it's holiday specific, it seems like we'll need an end date too, like 1st January. What date should be used for that?

Or should we just commit to releasing an update with non-holiday copy before the new year?

**Comment by bmccotter** [comment]
@thenbrent we discussed that with Apple Pay yesterday too, we will plan to release non-holiday copy before the new year if thats ok?

**Comment by thenbrent** [comment]
Sounds good to me.

**Comment by dechov** [comment]
Discussed with @britnimccotter yesterday, and we determined that since we have a way to wait to show the note until Apple Pay is set up (quite simply, after the changes in #1357), we can avoid worrying about timing by just showing the marketing note after the domain is verified.

I'd begun implementing a scheduled action to add the note, but realized that Apple Pay might not (yet) be enabled, so it wouldn't make sense to show "Now that you accept Apple Pay®…" messaging, possibly until a later point.

Let me know if showing the note immediately after enabling (contingent on automatic domain verification) feels too soon, and we could still schedule it out (a day?) at that point.

**Comment by bmccotter** [comment]
Hi @dechov I am fine with scheduling this out a day. Can we please plan to release it today?

**Comment by dechov** [comment]
Now opened https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1365, without scheduling the note – just triggering immediately. @bmccotter Better to show it a day after enabling / successful verification?

**Comment by bmccotter** [comment]
Yes, 1 day after enabling/successful verification is great.
