### ISSUE TITLE
Apple Pay fails when account registration is required

### ISSUE THREAD

**Issue by gamebits** [woocommerce/woocommerce-gateway-stripe#1352]
**Describe the bug**
When WooCommerce is configured to require account registration, the Stripe extension's Apple Pay feature fails for logged out users without explaining why or presenting an option to log in.

**To Reproduce**
1. Disable the "Allow customers to place orders without an account" option and enable "Allow customers to log into an existing account during checkout" (WooCommerce > Settings > Accounts & Privacy).
2. Enable the "Enable Payment Request Buttons. (Apple Pay/Google Pay)" option (WooCommerce > Settings > Payments > Stripe).
3. In an incognito window, visit a WooCommerce product page that has the "Buy with 🍎 Pay" button.
4. Attempt to purchase product directly from product page. Transaction will fail with "Payment Not Completed"

**Expected behavior**
Before Apple Pay payment workflow initiates, WooCommerce should check if the user is logged in and, if they are not, require they do so.

**Screenshots**
![Juiced.GS Sophistication & Simplicity](https://user-images.githubusercontent.com/12199101/97615426-86cacc80-19d8-11eb-80df-80da3c1cc16d.jpg)

**Environment**
 - WordPress 5.5.1
 - WooCommerce 4.6.1
 - WooCommerce Stripe Gateway 4.5.3
 - Safari 14 (macOS 10.14.6), Safari (iOS 13.6.1)

**Comment by phillipcornwell** [comment]
Found on 3598343-zen

**Comment by konstantin-klima** [comment]
I can confirm that this is happening when forcing the buttons to appear on the checkout page as well.
Can we get an ETA on this?

**Comment by diegocurbelo** [comment]
Hey @konstantin-klima, we don't have an estimate at this time

**Comment by lojel** [comment]
Similar issue for me but with the opposite settings: 
ENABLED: "Allow customers to place orders without an account"
DISABLED: "Allow customers to log into an existing account during checkout" 

Any clue? 

<img width="1134" alt="image" src="https://user-images.githubusercontent.com/21965567/107194159-a8514080-6a2a-11eb-8a21-bf1c8112a3d4.png">

**Comment by v18** [comment]
Solving this may solve #1194, but if not let's make sure to note which parts are still problematic for paying for subscription using the payment request buttons.

**Comment by v18** [comment]
Related: #1435

**Comment by WillBrubaker** [comment]
I've got what looks like this in 3776192-zen and I have been able to reproduce it, albeit inconsistently, on a testsite here: https://wctesting.tk/shop/

Oddly though, the user is already logged in and it also only happens if the assigned checkout page uses the checkout block rather than the default WooCommerce checkout shortcode.

It also seems unique to Apple Pay and Google Pay seems to work under the same set of conditions.

**Comment by lojel** [comment]
Following on this we have figured out the reason behind our "Payment not completed" issue.
The issue is simply related to the address region/state some people use with Apple Pay in some countries.

Apple Pay addresses in the US uses a dropdown list with 50 states so this issue never occurs in the US cause the values are not manually entered by the user.
However outside of the US Apple Pay rarely uses a dropdown list for the region/state field so people can enter any text in the region field which often result in a transaction failure because it doesn’t match any existing region.

USA
![Apple Pay USA](https://user-images.githubusercontent.com/21965567/109591232-23000e00-7b48-11eb-8426-dfb20f9db5af.jpg)

Take the example of Hong Kong for instance. There are 3 regions: Hong Kong Island, Kowloon, and New Territories. The region field is a text field. It’s very common that people use KL instead of Kowloon or HK instead of Hong Kong Island for instance which result in a payment failure cause the region doesn't match the one recognized by the system.

Hong Kong
![Apple Pay Hong Kong](https://user-images.githubusercontent.com/21965567/109591245-272c2b80-7b48-11eb-960f-a868946c4030.jpg)

The most concerning part for us was that payment failures for that specific issue are not logged at all by the plugin so we don't know how many times it happened before. It just displays “Payment Not Completed” in the Apple Pay flyout window on the user’s device with no further information on the user level and no failure notification on the store level.

We have fixed that on our side by programmatically fixing the region name when incorrectly entered (e.g. KL is fixed as Kowloon) and default the region name to a specific region when the value entered is not recognized. This works for us because we only sell in few countries but for those selling Internationally this fix might be tricky to implement.

The next step for us will be to:
1) Display meaningful error messages to the customer for Apple Pay instead of “Payment not completed”. This way the customer himself will be able to take corrective actions and make his payment.
2) Notified our development team when Apple Pay payment failures occur so we can take preventive actions internally.

That being said I think fixing this on the plugin level would be a major improvement for Apple Pay users. Some stores might be loosing sales at the moment because of this issue.

**Comment by malithsen** [comment]
Looks like the user in 5746855-zd-woothemes ran into this issue. Turning off both "Allow customers to create an account during checkout" and "Allow customers to log into an existing account during checkout" have solved it for them.

I wasn't able to reproduce this on a test site.
