### ISSUE TITLE
Apple Pay disappears 

### ISSUE THREAD

**Issue by NathanDillon** [woocommerce/woocommerce-gateway-stripe#136]
When clicking the Apple Pay button to pay the dialog comes up and then disappears

**Comment by roykho** [comment]
You have to make sure your two accounts match. If you're in test mode in Stripe, you must also use a Apple developers account for the device you're trying to test with.

**Comment by NathanDillon** [comment]
Thanks managed to fix that but now when I'm in live mode I keep getting a red exclamation mark on shipping address even though it matches my billing address

**Comment by bkorngold** [comment]
Having the same issue when clicking the Apple Pay button to pay, the dialog comes up and then disappears.  I am NOT in test mode.

**Comment by ntingey** [comment]
@bkorngold I'm having the same issue, did you manage to find a solution?

**Comment by bkorngold** [comment]
@ntingey Nope - never got an answer.

**Comment by thegrbteam** [comment]
Took me ages to get this....

I found out that there is a stripe error log in woocommerce (/wp-admin/admin.php?page=wc-status&tab=logs) and this issue was because the stripe API keys were wrong.

It seems every time you remove your domain from apple pay and re-add it (which I did loads of times thinking that was the issue), your stripe api keys change. So check they are correct.
