### ISSUE TITLE
3D secure cards saved when not verified by Stripe.

### ISSUE THREAD

**Issue by budzanowski** [woocommerce/woocommerce-gateway-stripe#1362]
## Describe the bug
When a user is doing a payment using a 3D secure card and selects the option to save the card for future payments the card is saved even if the Authentication failed.

## To reproduce

1. Setup a page with a checkout block.
2. Setup Stripe plugin ( test mode ).
3. Add items to the cart.
4. Complete the checkout form.
5. Use 3D secure Authentication required CC ( for example `4000 0027 6000 3184` ).
6. Select `Save payment information to my account for future purchases.`.
7. On the Authorization modal select to fail the Authorization for this CC.
8. Go My Account -> Payment Methods and see that the CC was saved.

## Expected behavior
If the CC fails authorization it should not be saved.

**Comment by asumaran** [comment]
First of all I'm a newbie to the Stripe API and to this repository `woocommerce-gateway-stripe` so bear with me. I've spent considerable amount of time on getting familiar with the code and testing possible solutions to this issue.

This issue happens because we attach the card to the customer before the `payment intent` is finished in the `WC_Stripe_Payment_Gateway->prepare_source()` method.

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/a33a56d230e5ab3689a2a8a1926cecbeecb36155/includes/abstracts/abstract-wc-stripe-payment-gateway.php#L632-L638

The card will **always** be saved when the user submits the checkout form and `Save payment information to my account for future purchases.` is checked. This should not happen for 3DS cards since the `payment intent` is not completed until the user provides authentication.

After reading the code I noticed that there's no shared place where we know exactly the `payment intent` has finished for both card types. so It has to be handled differently for each card type.

## Saving the card after the payment intent is complete

### For regular cards

For this case, If we want to save the card **after** the `payment intent` is confirmed which happens inside of the `WC_Gateway_Stripe->process_payment()` method.

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/a33a56d230e5ab3689a2a8a1926cecbeecb36155/includes/class-wc-gateway-stripe.php#L625-L628

This results in an error from stripe.

```
POST /v1/customers/cus_abc...xyz/sources

{
  "error": {
    "message": "The source you provided cannot be attached to the customer. It must be chargeable or pending.",
    "param": "source",
    "type": "invalid_request_error"
  }
}
```

In order to make it to work we **need** to attach the card to the customer before confirming the `payment intent`.

### For 3DS cards

As we saw above in order to (re)use the `payment intent` to save the card we need to attach the card to the user before the `payment intent` is complete. So there's no way to save the card the payment intent is complete which happens after the user has submitted the authentication. Which by the way is handled in another place, specifically inside the `WC_Stripe_Intent_Controller->verify()` method.

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/a33a56d230e5ab3689a2a8a1926cecbeecb36155/includes/class-wc-stripe-intent-controller.php#L83-L117

## Another approach 1

When talking with @diegocurbelo he proposed I should use the [`setup_future_usage`](https://stripe.com/docs/api/payment_intents/create#create_payment_intent-setup_future_usage) param when creating the intent and remove any trace of adding the card to the customer.

I've tested submitting the checkout form with `'setup_future_usage' => 'off_session',` in

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/a33a56d230e5ab3689a2a8a1926cecbeecb36155/includes/abstracts/abstract-wc-stripe-payment-gateway.php#L1067-L1081

 but it doesn't work properly. The first time the user submits the Checkout form the card apparently it's saved but it's not showing up on the "Payment methods" page in "My Account". The card will show up **after** the user goes to the checkout page to pay for a new order 🤷‍♂️.

## Another approach 2

I haven't tried it but I noticed we already have a way to add cards to a customer.

<img src="https://user-images.githubusercontent.com/1025173/113247064-d65f3e00-927f-11eb-840a-d5dd239ceed3.png" width="500" />

We could reuse the logic used there for adding the card to the user after the `payment intent` is complete since it seems we are adding the card without depending on a `payment intent`.

---

So, It would be helpful some tips or guidance from someone more familiar with the whole scenario on what approach to follow or what should I try next.

Consider that there's this comment that makes me feel we could break something if we move the place where we add the card/source to the customer as currently is:

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/281d644101b35716a20d5aee431632be3456be1d/includes/class-wc-gateway-stripe.php#L598-L602

/cc @diegocurbelo @ricardo @v18

**Comment by diegocurbelo** [comment]
Great job so far!!!, the approach 1 seems correct, the listed payment methods under My account are retrieved from the WC database, not from Stripe (this might change in the near future though). 

Did you remove the `add_source` call? or only `attach_source`?
Adding the `setup_future_usage` attribute to the PaymentIntent saves the method in Stripe, but we still need to save it to the WC database, so we need to keep this code block:

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/a33a56d230e5ab3689a2a8a1926cecbeecb36155/includes/class-wc-stripe-customer.php#L274-L315

**Comment by asumaran** [comment]
@diegocurbelo Thanks for the suggestion! I had removed the complete `$customer->add_source()` call. I'll test commenting out only the part where we attach the source to the customer `$this->attach_source( $source_id )` in `WC_Stripe_Customer`.

**Comment by asumaran** [comment]
@diegocurbelo it seems `setup_future_usage` was the way to go. I was able to save the source **only** after the payment intent has finished for regular and 3DS cards.

You can check [my WIP PR](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1507) if you are interested on the changes I've made so far. Code is not complete yet.
