### ISSUE TITLE
BECS (Australia) and BACS (UK) Direct Debit

### ISSUE THREAD

**Issue by pgpercival** [woocommerce/woocommerce-gateway-stripe#1413]
Stripe's ability to take direct debit payments in Australia (BECS) and UK (BACS) are really useful for subscription services. Is there any chance of getting these added to the WC stripe gateway?

**Comment by younggrandpa** [comment]
+1

**Comment by galbaras** [comment]
+1

Also, this is related to https://wordpress.org/support/topic/becs-direct-debit-payments-in-australia/, which was started 6.5 months ago!

**Comment by sverleis** [comment]
WooCommerce.com ticket with this as a request: #5404108-zen

**Comment by jpdaoatgfaukdotorg** [comment]
Hi everyone!  Any progress on getting Stripe BACS Direct Debit integrated with WooCommerce?  Stripe is super popular here in UK and people prefer BACS Direct Debit over other means, including cards, which expire (and then the failure rate is 13%).  BACS Direct Debit is soooo much easier to administrate.  Is there an ETA?

**Comment by thenbrent** [comment]
Closing this one as the corresponding feature requests for [Bacs](https://woocommerce.com/feature-request/bacs-direct-debit/#) and [BECS](https://woocommerce.com/feature-request/enable-becs-pay-in-woocommerce-stripe-payment-gateway/) on the feature request board will be used to track popularity to help determine priority in our roadmap instead of a GitHub issue (which will be focused on bugs in the maintenance backlog).

To help understand our plans for this feature, we will be focusing our near term efforts on improving the UPE integration currently in the Stripe extension (under the "[new checkout experience](https://woocommerce.com/document/stripe/#new-checkout-experience)") before adding additional APMs to it or the  legacy elements integration. Once the UPE integration is the default, we will begin offering additional APMs, like BACs (A8C reference for the roadmap here: pc4etw-Jq-p2)

ACH currently 2nd most popular feature request, and it is likely we will handle bank debit methods as a singular project with Bacs and BECs as part of that.
