### ISSUE TITLE
Make "update the payment method" checkbox text consistent with what's in WooCommerce Subscriptions

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-gateway-stripe#1421]
In https://github.com/woocommerce/woocommerce-gateway-stripe/blob/84b6457d691f47bdbcaa45f4d218ba852532c857/includes/compat/class-wc-stripe-subs-compat.php#L92 we have

> Update the Payment Method used for all of my active subscriptions.

But WooCommerce Subscriptions templates/checkout/form-change-payment-method.php has

> Update the payment method used for %1$sall%2$s of my current subscriptions

We should uncapitalize ours, replace "active" with "current" and consider bolding all like WCSubs does.

This is exposed in /my-account > View Payment Methods > Add payment method

**Comment by james-allan** [comment]
Just noting that this issue is currently limited to stores using the legacy checkout experience. The new UPE checkout experience doesn't display this checkbox at all. 

| Legacy Checkout | UPE |
|--------|--------|
| <img width="835" alt="Screenshot 2024-09-23 at 4 17 06 pm" src="https://github.com/user-attachments/assets/0f96a2c7-c9de-4f1c-99b2-e3355ab7999c"> | <img width="843" alt="Screenshot 2024-09-23 at 4 17 52 pm" src="https://github.com/user-attachments/assets/9607799e-4bda-4e37-ad0a-26a3bb084143"> | 

We should really add this feature to stores using the latest UPE - I'll file a separate issue for that.
