### ISSUE TITLE
Add Afterpay and Klarna to the list of payment methods

### ISSUE THREAD

**Issue by lojel** [woocommerce/woocommerce-gateway-stripe#1497]
**Is your feature request related to a problem? Please describe.**
Afterpay and Klarna are now available on Stripe but the plugin doesn't provide the possibility to integrate these 2 payment methods.

**Describe the solution you'd like**
An easy integration of Afterpay and Klarna via Woocoommerce Gateway Stripe.

**Describe alternatives you've considered**
A dedicated integration for each but that requires much more work and it also requires us to create a separate account for each payment method which is unnecessary since Stripe now integrate these 2.

**Comment by bhound** [comment]
This would really be a useful feature. As it stands other plugins are advertising that they can handle this, but the "official" plugin can't. Would prefer not to have to develop a standalone solution or have to switch to a third party plugin just to use a service that is already integrated with Stripe.

**Comment by CGA8C** [comment]
Feature Requested in Chat: 35996389-hc; suggested they use a stand-alone Klarna Gateway for now.

**Comment by joashrajin** [comment]
+1 at #5578245-zen

**Comment by WillBrubaker** [comment]
38702334-hc

**Comment by kaushikasomaiya** [comment]
6239978-zen

**Comment by Babylon1999** [comment]
zd-6333175

**Comment by Babylon1999** [comment]
zd-6586666

**Comment by thenbrent** [comment]
Closing this one as the [corresponding feature request](https://woocommerce.com/feature-request/add-afterpay-and-klarna-to-the-list-of-payment-methods/#) on the feature request board will be used to track its popularity to help determine its priority in our roadmap instead of a GitHub issue (which will be focused on bug backlog).

Afterpay & Klarna support is currently the 3nd most popular feature request for reference on its relative priority (with only ACH support and Apple Pay / Google Pay requests ahead of it).

Please vote on that feature request instead of posting future requests on this issue.

To help understand our plans for this feature, we will be focusing our near term efforts on improving the UPE integration currently in the Stripe extension (under the "[new checkout experience](https://woocommerce.com/document/stripe/#new-checkout-experience)") before adding additional APMs to it or the legacy elements integration. Once the UPE integration is the default, we will begin offering additional APMs, like Afterpay & Klarna (A8C reference for the roadmap here: pc4etw-Jq-p2)
