### ISSUE TITLE
Failed refunds showing as successful when using iDeal/ Sofort

### ISSUE THREAD

**Issue by rossviviano** [woocommerce/woocommerce-gateway-stripe#1523]
**Describe the bug**

Failed refunds via iDeal/ Sofort due to insufficient funds showing as successfully refunded in WooCommerce. 

Order in the Stripe Dashboard: ![Screenshot](https://d.pr/i/q2TMKo+)
Image Link: https://d.pr/i/q2TMKo

We can also see that the Stripe logs show the same `insufficient funds` error:

![Screenshot](https://d.pr/i/HT5moQ+)
Image Link: https://d.pr/i/HT5moQ

However, the order notes show (translated) `Product xxx stock increased from x to x. Status of the order changed from Completed to Refunded.`

**Expected behavior**
I'd expect for WooCommerce not to show the order as `refunded` if the refund wasn't successful. 

**Environment (please complete the following information):**
 - WordPress Version 5.7
 - WooCommerce Version 5.1
 - Stripe Plugin Version 5.0

**Additional context**
Brought up in 1722996-hc.

**Comment by dmvrtx** [comment]
It looks like it might be the problem for all failed refunds. [This block](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/752db9c62e3511835baaff6e34ace58674678ea0/includes/class-wc-stripe-order-handler.php#L325) clearly indicates that any error returned by `process_refund` is just ignored. It could be that refund on payment methods like credit cards are usually succesful because of its nature, but for Ideal/Sofort and some others there are more conditions to make them fail.

I consider throwing an exception in `WC_Stripe_Order_Handler::cancel_payment` if refund has failed and leave it to WooCommerce to handle the rest. It looks like to be well covered on WooCommerce side.
