### ISSUE TITLE
Need Google Pay Button's Popup render on Onpageload

### ISSUE THREAD

**Issue by merajali294** [woocommerce/woocommerce-gateway-stripe#1526]
**Describe the bug**
I’m trying to modify JS so that the Google Pay Button Popup Automatically loads once user comes to cart Page, but it does not work, can someone here check and fix this?

My use case is,
I want the Chrome PopUp to appear once the user clicks AddToCart in Single Product Page and then goes to Cart Page, and in this page I need Popup to appear so that he does the Payment right away,
I’m tweaking this part, prButton.mount( ‘#wc-stripe-payment-request-button’ );
But this mount function doesn’t allow me to use the window.addEventListener(‘load’, #wc-stripe-payment-request-button);

Please check this part and correct me so that Chrome Popup is enabled once user gets to Cart page,

Have implemented similar part here, it works, https://sravan523.com/api.php

**Expected behavior**
As I said it above I need this (https://i.imgur.com/S7pBqml.png) PopUP on page reload, it's quite simple, isn't it?
Thank you for your help!

**Environment (please complete the following information):**
 - WordPress Version 5.7
 - WooCommerce Version 5.1.0
 - Stripe Plugin Version [5.0.0](https://wordpress.org/plugins/woocommerce-gateway-stripe/) 
 - Browser chrome

Let me know if you need any help or information.
When I asked on Forum, they say it's a complex development topic.

**Comment by ricardo** [comment]
The Payment Request button was not intended to work this way. That's why the button also appears on the product page, so users can check out faster from there, if they want.

What you're trying to do seems possible, but here are a few things I would consider:

- Isn't the Payment Request button on the product page sufficient to allow users to checkout without going to the cart? Or at least giving them the option to not need the regular checkout flow?
- What would happen if you'd open the Payment Request dialog automatically without your users expecting it? Wouldn't it cause frustration if they wanted to change the items in their cart?
- What if they wanted to continue with the regular checkout flow?

Ultimately, I think opening the Payment Request dialog automatically would lead to bad user experience. Because users don't expect that to happen automatically in the cart.

However, if that's something you're willing to do, we don't offer any way to do it through our JavaScript integration, but you could do it in a _hacky_ way, perhaps you could wait until the button has loaded, and then trigger a `click` event.

Let's say you use a "Custom" button type. The dialog could be opened with something like
```javascript
jQuery('#wcpay-custom-button').click();
```

You'd still need to verify if the button has loaded and implement any other potential exceptions. We don't offer this type of support here on GitHub, but if you need any assistance with that, I'd recommend getting a [WooCommerce expert](https://woocommerce.com/experts/).

**Comment by v18** [comment]
I'm closing this issue as answered.

**Comment by merajali294** [comment]
@ricardo , thank you for your input,

1. Let me explain you my requirement here, Once user does the AddToCart, Im sending them to my Custom Page where I want to render the PayNow PopUp so that he immediately selects Address and does the Payment.

2. Or if woocommerce-gateway-stripe cannot provide the solution, is this something [Stripe](https://stripe.com/docs/stripe-js/elements/payment-request-button") are supposed to do, may be talking to them would help
