### ISSUE TITLE
"You did not provide an API key" intermittent Stripe error on checkout

### ISSUE THREAD

**Issue by SebKay** [woocommerce/woocommerce-gateway-stripe#1550]
We have a client in Ireland who takes payments via Stripe in WooCommerce. A few times per week he'll get a failed order come through and all customers have been saying they are seeing the following error appear at the top of the checkout:

```
You did not provide an API key. You need to provide your API key in the Authorization header, using Bearer auth (e.g. 'Authorization: Bearer YOUR_SECRET_KEY'). See https://stripe.com/docs/api#authentication for details, or we can help at https://support.stripe.com/.
```

**To Reproduce**
It's tricky to reproduce because it only seems to happen to live payments, but here's what our clients customer's have said:
1. Add product to cart.
2. Go to checkout and enter card details.
3. Click checkout and see the error.

**Expected behavior**
For the checkout to process the card details via Stripe and for the order to be completed.

**Screenshots**
Here is a screenshot of the error log (not very helpful unfortunately): https://www.dropbox.com/s/3tqvfeeo5snim0q/Screenshot%202021-05-04%20at%2013.18.58.png?dl=0

**Environment (please complete the following information):**
 - WordPress Version: 5.7.0 and 5.7.1 this has happened,
 - WooCommerce Version: 5.2.2
 - Stripe Plugin Version: 5.1.0
 - Browser [e.g. chrome, safari] and Version: This report has been sent by multiple customers so this information isn't available.
 - Other plugins installed:
   - ACF Content Analysis for Yoast SEO
   - Advanced Custom Fields PRO
   - Advanced Custom Fields: Gravity Forms Field
   - Business Reviews Bundle
   - Category Order and Taxonomy Terms Order
   - Classic Editor
   - Code Snippets
   - Google Analytics for WordPress by MonsterInsights
   - Gravity Forms
   - MCE Table Buttons
   - Premmerce Permalink Manager for WooCommerce
   - Regenerate Thumbnails
   - Safe SVG
   - Simple 301 Redirects
   - Simple 301 Redirects - Addon - Bulk CSV Uploader
   - Smush
   - WordPress Importer
   - WP Rocket
   - Yoast Duplicate Post
   - Yoast SEO
   
**Additional context**
I've done a lot of Google to see if anyone else has encountered the same issue, however I can't see any similar problems related to WooCommerce.

**Comment by v18** [comment]
Hi @SebKay - thanks for opening an issue. Since it's not reproducible, like you mentioned, I recommend that you contact WooCommerce Support to get their help in troubleshooting the problem. Here's where you can contact them:
https://woocommerce.com/my-account/create-a-ticket

Hopefully they can help find the common thread within the failed requests, and together we can help you and your client in this situation. Here are some things that might help them so if you can I suggest adding those details right away to your email:
- the Stripe API request log (from the Stripe dashboard) for **each** failed request
- are you able to get the same customer to see the same error twice? or are they able to check out after trying again?
- any pattern with the requests - e.g. country, guest checkout, time of day, type of product

**Comment by SebKay** [comment]
OK thanks for the info. I'll open an issue there and see what they say. Thanks!
