### ISSUE TITLE
Add Support for Sources -> needed for new European Payment Options 

### ISSUE THREAD

**Issue by quasel** [woocommerce/woocommerce-gateway-stripe#156]
Add support for https://stripe.com/blog/european-payment-methods

New Feature "Sources" - https://stripe.com/docs/sources

-------------------

- [x] Issue assigned to next milestone.
- [x] Issue assigned a priority (will be assessed by maintainers).

**Comment by Planetdune** [comment]
Waiting patiently for this one! Like many other European Stripe users..

**Comment by brunocrosier** [comment]
would it be possible to "crowdfund" development of this feature as a priority? this would be an absolute gamechanger for myself as a merchant selling to EU customers. I'm sure plenty of others are in the same boat as me. Maybe we could pool some funds together to get this feature implemented faster? If so, how much would be needed?

**Comment by MaikelVEGroup** [comment]
Hi!

I contacted Stripe to ask about the integration of Sofort/iDeal/Bancontact/SEPA because they are now beta testing these integrations, but only via API and not via the Stripe plugin. So i’m requesting this feature 🙂

**Comment by MaikelVEGroup** [comment]
*Integration on WooCommerce(WordPress)

**Comment by jyourstone** [comment]
Hello,

I also contacted Stripe about 3D Secure that they have in Beta now, but that's also only supported via API and not the Stripe plugin. It would be great if that was included.

**Comment by brunocrosier** [comment]
I'm building an integration for this and I will be selling it as a separate plugin. It should be ready in a few days. Anyone interested, let me know and I'll update you when it's available to purchase!

**Comment by MaikelVEGroup** [comment]
Hi! Definitely me! :)

**Comment by jnachtigall** [comment]
This has also been raised at http://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/17830732-stripe-sepa-support I guess it won't warm to upvote here and there ;)

Needless to say that this would be a game changer. SEPA direct debit is *way more* popular in Germany than credit cards.

**Comment by MaikelVEGroup** [comment]
Well they are only speaking about the SEPA option, here we're talking about SEPA, iDeal, Sofort

**Comment by jnachtigall** [comment]
True. Would be interesting to have some number here. For Germany: SEPA is extremely popular (at least same level as PayPal) whereas iDeal, Sofort and Credit Cards are rather unpopular. Might be different for other European countries though. I read that iDeal is very popular in the Netherlands, whereas I have never come across or heard of it in Germany (same for Sofort albeit its German name).

**Comment by MaikelVEGroup** [comment]
iDeal is just for Holland because it's for the Holland banks ;) Sofort is used by the greatest distributors in Belgium. SEPA is very unpopular therefor PayPal is well know in Belgium, every single Balgain has heard of it

**Comment by brunocrosier** [comment]
We've done it! If you want support for European payment methods on your WooCommerce site, we have developed this integration - and it's working great! You can get it here: https://woostripe.com

Cheers!

**Comment by brunocrosier** [comment]
@quasel @Planetdune @maikelVEGroup @jnachtigall @jyourstone - you might be interested!

**Comment by jaschaio** [comment]
Just got a message from stripe "SEPA Direct Debits have been enabled on your Stripe account". Implementing this in the WooCommerce Stripe Plugin would truly be a Game Changer. Happy to help to implement this as well. I am from Germany myself and I know that direct debit is way more common here than credit cards or even paypal.

**Comment by brunocrosier** [comment]
hey @jaschaio you can integrate all of the payment methods (SOFORT, Giropay, Bancontact, SEPA Direct Debits, iDEAL and 3D Secure) by buying this plugin: www.WooStripe.com

**Comment by ed-rocketship** [comment]
This is a much needed feature for the European market (specifically Germany) as users prefer to pay this way. For the moment the fact that this option is not available is keeping us from Stripe, and we really wanted to make the switch. Consider this my signed, sealed, and delivered up vote for this feature. Pretty please with flowers on top.

**Comment by madmath** [comment]
@brunocrosier Would be great if you could contribute this support to this open-source plugin since you already seem to have it working.

**Comment by brunocrosier1** [comment]
hey @madmath - good question!

for some reason my account @brunocrosier seems to have been blocked, so i've made a new account to reply to you.

here goes (brace yourself!) : 

as much as i would love to offer woostripe.com as open-source, i'm not a developer - i'm actually just a very impatient WooCommerce shop owner.

back in mid February i actually suggested in this very thread that we should crowdfund the development of this feature, but there was no real response (from woocommerce, @roykoho , or anyone else in the thread). so, rather than wait for someone else to do it, i hired a developer to build this feature. 

it took weeks to build (over 150 hours of billable development, plus my own blood, sweat and tears - not cheap!) which came out of my own pocket. i hoped that by selling the resulting plugin to other WooCommerce users, i'd be able to recover the funds that i had invested. 

with all that said, I really don't feel that it shouldn't be me, a 25 year old dude with an little online shop, that pays for this pretty huge (and awesome) feature that ultimately benefits WooCommerce and Stripe financially just as much as its users (if not more so)

Stripe obviously will benefit from more transactions, (ie. more commissions) and WooCommerce will benefit by expanding its list of features and integrations (hence why this very plugin is now free, as opposed to the previous price of $79).

However, if WooCommerce and/or Stripe were to get in touch with me and wanted to buy the rights to the code, i'd happily discuss it without holding them to ransom. I'm pretty much just looking to make back my initial investment.

I hope that all makes sense. If you disagree with anything I've said, please let me know.

**Comment by BenLinders** [comment]
Really like to see iDeal support in Woocommerce via Stripe!

**Comment by silicondales** [comment]
+1 on this one - may investigate further if my current project requires this.

**Comment by germanoronoz** [comment]
Hello @brunocrosier @brunocrosier1 ,

I purchased your plugin and discovered that does not support subscription type products.

Are you planning to develop this feature?

This is strictly needed for us, as subscriptions are the only products we sell on our WooCommerce store.

You actually did a great job, but I think you should say that this is not compatible with subscriptions on your product description, as the Stripe gateway actually is and it is normal to assume that the new sources will also be compatible.

Please tell me if you plan to develop this feature.

Here you have the developer docs:
https://docs.woocommerce.com/document/subscriptions/develop/payment-gateway-integration/

Thanks in advance.
Regards

**Comment by roykho** [comment]
@germanoronoz - please do not use this repo to ask about a paid plugin.

**Comment by germanoronoz** [comment]
@roykho ok, sorry, didn't know that.

**Comment by t-bo** [comment]
June almost here, and no new on implementing this? What are the reasons?

**Comment by gerdneuman** [comment]
@roykho Is there some kind of **time plan** for this? I see you marked as "[Pri] High". OTOH, half a year past without much happening in this direction and the commits also seem to suggest that this is not being worked on right now.

Fair enough, but for small as well as big businesses which already are on Stripe and/or WooCommerce and need to make long term decisions (e.g. when choosing payment or ecommerce solutions) it would be valuable to know whether this feature will land (or being worked on), say, still this year or rather in two years...

So what are the (approximate) plans?

**Comment by brunocrosier2** [comment]
@t-bo @gerdneuman @florianbepunkt I was in your position with my business a few months ago, but I am impatient and I don't like my business to be waiting in the hands of somebody else. So, I decided to have the integration custom-built by one of the best WP plugin devs in the world. I can assure you, it was not cheap. Now, we are selling [WooStripe](https://woostripe.com) as a 100% completed and stable solution that's being used by several webshop owners worldwide using WooCommerce + Stripe.

I'm fully aware @roykho will probably delete this comment and ban my account from commenting, as he has done before. I find it ridiculous that I'm literally being censored in the 21st Century, when all that I've done is put my own neck on the line and develop a solution to a problem that several entrepreneurs such as myself were clearly desperate for, and which WooCommerce and Stripe were (and still are) clearly not bothered about.

The fact is that after WooStripe was completed, I even approached WooCommerce and Stripe to see whether they would like to buy the code so that they can add it to this plugin - but neither WooCommerce nor Stripe sees it as their responsibility to pay for it. They weren't even interested enough to ask how much I would have sold it for. I would guess that this is probably the best answer to your question of "why this integration hasn't been developed until now", (along with the fact that it requires a **lot** of time, money, and expertise to develop it).

**Comment by silicondales** [comment]
@brunocrosier2 you definitely understand why your post is of a commercial nature and you should therefore not be polluting this issue thread with your attempt to sell "some other" product? Its the 21st century, as you rightly point out, that doesn't mean I want you to spam me with your attempts to sell a plugin.

**Comment by brunocrosier2** [comment]
@silicondales Wow. Somebody's completely missed the point. I suggest that you scroll your screen up to the[ 3rd comment in this thread](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/156#issuecomment-280540703) where I suggested crowdfunding this integration. It's beyond ridiculous to portray me as some sort of corporate cowboy. Where were you when I suggested crowdfunding it, by the way? 

You've accused me of spamming you.

**Spam:** _irrelevant or unsolicited messages sent over the Internet, typically to a large number of users, for the purposes of advertising, phishing, spreading malware, etc._

Is that what I'm doing? Did I solicit your attention in my comment? No. I am directly replying to 3 users who are (understandably) asking why this feature hasn't been added yet, and I have provided an in-depth response. 

I am not "polluting this thread". This thread is stagnant. I allowed @roykho over 5 days to reply, and he ignored the users' questions. I felt qualified to answer their question, and did so.

My most recent comment before today was on March 31st and it was a **direct response** to somebody asking me why I haven't opensourced my integration.

So, I would appreciate it if in future you could avoid bringing my character or intentions into disrepute.

**Comment by germanoronoz** [comment]
@brunocrosier2 Your plugin is not fully finished (it does not support subscriptions, and has some bugs, for example), I purchased it and wrote you a couple of messages trhough your form in WooStripe.com, never got an answer.

How can I contact you?

**Comment by silicondales** [comment]
I am subscribed to this issue thread - your message got emailed to me. That was not solicited. And the very next comment shows why its not appropriate for here.

**Comment by t-bo** [comment]
@germanoronoz lol... What a plugin.

**Comment by germanoronoz** [comment]
@t-bo haha 

Anyway I am sorry to post this kind of comment here, but I have anything else to do to get some support.

**Comment by brunocrosier2** [comment]
@germanoronoz my email is clearly visible on the website, and we haven't received an emails from you (see screenshot). My plugin doesn't claim anywhere in its description to support Subscriptions, so I don't see how that is a fair or relevant comment? It's like buying an iPhone and saying "oh but it doesn't work underwater". Feel free to email me for support, this obviously isn't the place for that.

![image](https://user-images.githubusercontent.com/29249031/26871711-65885406-4b74-11e7-81fe-273d03f297e4.png)

@silicondales I don't control whether or not **you choose** to be subscribed to the thread, you're very welcome to ignore my comment(s). My comment was **clearly** intended for 3 specific users, in direct response to their question. If had mentioned you specifically for no reason, you'd have a point, but I didn't, so you don't. 

@t-bo see above. I'm willing to accept criticism where it's due, but it's ridiculous to criticize it for something that it doesn't claim to do. 

It's great to see so many people being so active in pointing fingers and criticizing things that they haven't even seen. I would have **loved** to have heard from you guys 4 months ago when I was asking if anyone wanted to help crowdfund this integration. No worries though - you guys go ahead and keep on waiting for somebody else to release it for free!

**Comment by silicondales** [comment]
@brunocrosier2

Okay, you decide what is "ridiculous" and what is "spam". I'm seldom right, but you always are. I get it.

I don't want to help crowdfund this integration. Nobody here did. But you went ahead and built it. Well done. Bring out the pom poms. Let's design a snapback cap with your name on it to celebrate. I'm delighted for you. 

I'll even offer some unsolicited advice: releasing a commercial plugin is not a light undertaking. You'll need to offer a *lot* of support, and updates, so you really need to be sure there is sufficient market for your plugin to justify the ongoing support and development overhead which will be expected of you.

I mean, even "free" plugins create large support demands. Like, sometimes, people chirp up on issue threads and hijack them to create their own derivative products, thereby generating cruft for the original developers in the form of issue emails which aren't related to the actual issue, but are in fact related to *some other plugin*.

I don't see why you came back here with any intention other than to use this issue thread to market your commercial plugin. That is pretty much the dictionary definition of spam. You clearly expected some form of adverse reaction, as evidenced by your preemptive statements on "censorship". But you went ahead and did it anyway. 

The rest of this conversation pretty much played out as any one of us might have anticipated.

**Comment by brunocrosier2** [comment]
@silicondales 

> I don't see why you came back here with any intention other than to use this issue thread to market your commercial plugin.

As I have already stated, I was replying to 3 users who were asking why this feature still hasn't been added to the official plugin. My answer was after 5 days of silence from @roykho. I quoted the dictionary definition of spam, and then explained to you how my participation in this thread is anything but spam. 

Not sure where you're going with the jibe about snapbacks. Yes, that's what my e-commerce site sells, but I haven't mentioned that here, and I'm not sure why you have either. Having now returned the favor and taken a glance at what your company sells, I see that you sell ... **WordPress and WooCommerce plugins**. 

Now would be a good time for you to take a look at the dictionary definition of irony.

**Comment by germanoronoz** [comment]
@brunocrosier2 I used the form in your site, twice, so you should check it, as it seems to be broken.

Native Stripe gateway works with subscriptions, and you sell the plugin as an add-on, so AT LEAST you should put in your site publicly that it does not support subscriptions, because it is normal to think that it does...

As @silicondales said, selling commercial plugins require to provide A LOT of support, and yours is none.

We are developing ourselves the subscriptions integration and will maintain the plugin.

Regards

**Comment by silicondales** [comment]
spam === **unsolicited** messages of a **commercial nature**.

**Comment by roykho** [comment]
I apologize for the delay of this feature as we were all busy with integrating Apple Pay at the time and seeing that it is stable and many other fixes that we had to do. However we will finally put this on our Q3 plan and shouldn't take too long to develop.

**Comment by roykho** [comment]
Sources added in https://github.com/woocommerce/woocommerce-gateway-stripe/tree/4.0.0 and now developing the EU sources.
