### ISSUE TITLE
Express payment methods not showing up in the Checkout block

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gateway-stripe#1653]
## To reproduce
1. Install and set up WooCommerce + WooCommerce Blocks + WooCommerce Stripe Gateway.
2. With a device that supports at least one express payment method (Google Pay or Apple Pay), go to the Cart block.
3. Verify that express payment methods show up.
4. Go to the Checkout block.
5. Notice that express payment methods don't show up.

## Expected behavior
Express payment methods should show up in the Checkout block in the same way they do in the Cart block.

**Comment by Aljullu** [comment]
I initially opened this issue in WC Blocks repo because I thought it was a regression there, but after testing I noticed it's a regression in Stripe gateway introduced between 5.2.3 and 5.3.0.

cc @reykjalin for awareness.

**Comment by reykjalin** [comment]
Hi @Aljullu, thanks for the report!

This is because we currently respect a filter we also use for the Shortcode flow to control where the Express Payment Methods appear; `wc_stripe_show_payment_request_on_checkout`.

I've already opened a different issue to handle this (https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1640) so I'm going to close this issue 🙂 

We've talked about this a bit internally, and as part of a bigger change in the settings screen in the coming months we're going to expose a UI to control where the Express Payment Methods appear. Because of that I don't think we'll be changing the current behavior any time soon (but feel free to advocate for that in #1640 and I'll be sure to pass that on to our designer 🙂).

For now, you should be able to display the PRB in the checkout by enabling the `wc_stripe_show_payment_request_on_checkout` filter with:

```php
add_filter( 'wc_stripe_show_payment_request_on_checkout', '__return_true' );
```
