### ISSUE TITLE
SPIKE - Stripe+UPE - UI work

### ISSUE THREAD

**Issue by frosso** [woocommerce/woocommerce-gateway-stripe#1660]
## Description

We will be fully porting UPE and the new settings design to the Stripe plugin: pc4etw-hj-p2

We will be porting some of the componentry from WCPay to Stripe.
Some of the components are "connected" to `@wordpress/data`, but we will be porting that as well.

The plan is to pretty much copy/paste/adjust the components into the Stripe plugin.

Please report your findings based on the designs and write some high-level tickets.

## Questions
- Do we have the dependencies we need to start porting the UI work?
- What components can we reuse?
- What adjustments do we need to make?
- How many setting pages would we need to account for?

**Comment by harriswong** [comment]
### UI components in the Stripe's settings page 

Based on the latest design (Igkr3nOx0UoGDlHrsJ4eux-fi-0%3A1), here are a list of the components we will need:

#### Orders page
-  Inbox notice. We can probably reuse https://github.com/Automattic/woocommerce-payments/blob/develop/includes/notes/class-wc-payments-notes-additional-payment-methods.php.

#### Payment Methods `wp-admin/admin.php?page=wc-settings&tab=checkout`
_Click WooCommerce > Settings > Payments. It will display a list of all payment methods._
- After onboarding wizard step 3, user can click "Go to Stripe settings". At this point, the users is brought back to the list of payment methods, with a help popup highlighting the Stripe's row. 

#### UPE Settings - Payment method tab `wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe`
_Click WooCommerce > Settings > Payments > Stripe . It will display the UPE additional payment methods, express checkout._
- This "Payment methods" tab can reuse most codes from https://github.com/Automattic/woocommerce-payments/tree/develop/client/settings.
- We will need to build an onboarding wizard (Tasks). This plugin doesn't have an existing `TaskList`. We can reuse some existing codes from https://github.com/Automattic/woocommerce-payments/tree/develop/client/overview/task-list. Then, we can add the onboarding task. 
- Add a new info notice since we can no longer change payment method's title and description.
- When disabling UPE, show a prompt to ask for feedback. We can reuse https://github.com/Automattic/woocommerce-payments/tree/develop/client/settings/survey-modal.
- Unlike WCPay, Payment methods can be empty. We will need to add a place holder image when there is no payments. 
- "Add payment methods" modal will display fees. Do we have the merchant's fees information?
- Express checkouts, we can reuse https://github.com/Automattic/woocommerce-payments/blob/develop/client/settings/payment-method-settings/payment-request-settings.js

#### UPE Settings - Settings tab `wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe`
_Click WooCommerce > Settings > Payments > Stripe > Settings tab. It will display the settings for Stripe; General settings, Account Details, etc._
- There are some work to create a tab component or perhaps we can utilize WordPress [TabPanel](https://developer.wordpress.org/block-editor/reference-guides/components/tab-panel/).
- There are a few new sections on this page that WCPay doesn't have. That said, we can reuse the `SettingSection` component; some sections needs to be collapsable. 
- "Connect to Stripe" button. This opens up the OAuth flow and it will create a new account. Check pc4etw-a9-p2#comment-713 
- Add a new warning notice to the top of page if Stripe is not connected. The message of the notice is interactive. Clicking links inside may pop up Stripe's prompt or will scroll the page. 
- Add state and css to "grey out" some settings if Stripe is not connected.

**Comment by harriswong** [comment]
### Replacing settings page  `wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe`
_Click WooCommerce > Settings > Payments > Stripe_

- We will replace this page with a full React driven page. 
- I can see this using the same approach we did previously in WooCommerce Payments https://github.com/Automattic/woocommerce-payments/pull/1551
  - To quickly test this, I was able to get a `<div id="wcpay-account-settings-container">React container place holder</div>` page to replace the current settings. There is just no js to load the app into `wcpay-account-settings-container`.
- This would probably require some changes in package.json (react, etc) and webpack.config.js. I think this would be covered in https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1661.
- We need to remove the duplicated payment settings page (ie. sepa, sofort, etc) in this folder https://github.com/woocommerce/woocommerce-gateway-stripe/tree/develop/includes/admin

**Comment by harriswong** [comment]
### Dependency
- `TaskList` component for wizard
- `NoteTraits` from woocommerce-admin (inbox notification)

**Comment by harriswong** [comment]
Tickets are being created along with other tickets, I'm moving this to the review column.
