### ISSUE TITLE
SPIKE - Stripe+UPE - Webpack/Assets compilation

### ISSUE THREAD

**Issue by frosso** [woocommerce/woocommerce-gateway-stripe#1661]
## Description

We will be fully porting UPE and the new settings design to the Stripe plugin: pc4etw-hj-p2
It sounds like some work has already started to include Webpack in the plugin.

## Questions
- What is remaining to do?
- What approach are we going to follow for the tests?
- What linting rules do we need?

**Comment by tommyshellberg** [comment]
### Webpack config
It looks like a lot of work has been done already, many thanks to @diegocurbelo for adding webpack to Stripe!

The `feature/upe` branch at this time already has a `webpack.config.js` file using the `defaultConfig` created by `wordpress/scripts`. This provides us with hot reloading, css minification, bundle analyzer, and more. It is my understanding that this feature branch will soon be merged into `develop` which will be a great starting point for our UPE settings work.

This `webpack.config.js` file is already set up to import the default wp scripts config using a spread operator and has some overrides in place, namely the `entry` point, making it easy for us to override the default config.

The `entry` point object is where we'll need to determine the entry point for UPE's settings app. 
We could add a new entry point called something like `upe_settings` since we don't want this enqueued on the front-end:

```
  entry: {
    index: './client/blocks/index.js',
    upe_classic: './client/classic/upe/index.js',
    upe_settings: './client/upe/settings/index.js',
  }
```

It's still not totally clear how UPE will work on the frontend with blocks and with "classic" UPE(the two existing entry points) but for the settings page it seems irrelevant since the implementation of UPE on the frontend should be out of scope. The settings page should stay the same regardless of how UPE is displayed on the frontend.

### JS 

When webpack rebuilds with this new entry point, we'll have some new files in the `build` directory which can be enqueued within the plugin for the settings page.

Something to consider is that [there is already some JS loaded on the Stripe settings page](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/cf24c32bd57bdb5cb8577da9bd500d34087eeb5b/includes/class-wc-gateway-stripe.php#L343):

This URL:
`http://localhost:8082/wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe`

It looks like most of its functionality will be replaced by the React settings app so if UPE is enabled we'll want to enqueue the UPE settings JS from `/build/` instead of the existing Stripe JS from `/assets/`.

Settings page design w/ Figma file link: pc4etw-a9-p2

On a related note, it looks like there are already some menu items added to the Stripe settings page for enabling various UPE methods. Given that this page will be replaced by a React app we'll want to avoid wasted effort from Fractal. Do you plan to continue adding to the settings page @diegocurbelo or can we cleanly take over from here?

### CSS 
It looks like SCSS files will automatically be processed into .css files through the `MiniCssExtractPlugin`, provided they are imported by a component. So, following our example from above, if we have a `client/upe-settings/` folder with an index.js file and an imported sibling style.scss file, webpack will build a CSS file and file map.

![Screen Shot 2021-08-13 at 12 48 05](https://user-images.githubusercontent.com/6723003/129346106-423b5064-3068-4619-8d60-74d2c963afc5.png)

### Tests

The Stripe plugin has used Mocha + Chai for JS testing, however, it looks like some newer tests have been written for UPE which make use of `Jest` since it is available from @wordpress/scripts:

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/feature/upe/client/styles/upe/test/index.js#L31

In order for the tests to be copied over from WCPay, we'd need to add at a minimum the following dependencies:

```
@testing-library/jest-dom
@testing-library/react
@testing-library/user-event
@wordpress/api-fetch
@wordpress/data
```

I also like the idea of creating new npm scripts for JS tests since it appears they don't exist in the Stripe plugin at the moment. I would like to see `test:js` and `test:watch` since it speeds up development time. These would use `wp-scripts` to execute test running which is already available.

`https://github.com/Automattic/woocommerce-payments/blob/develop/package.json#L28`

### Linting
We have some linting in Stripe already thanks to [WooCommerce eslint-plugin](https://www.npmjs.com/package/@woocommerce/eslint-plugin):
https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/.eslintrc.js#L2

Overall, I think we are in a pretty good place and it won't require too much work, the major points are:

- Add new entry point in the webpack.config.js file - can be done in #1680 
- Add the missing devDependencies in package.json to allow WCPay UPE component tests to be re-used - can be done in #1694
- Enqueue UPE settings page JS from `build/` and not `assets/` when UPE Settings preview is enabled - can be done in #1680
