### ISSUE TITLE
SPIKE - Stripe+UPE - Settings backend + data layer

### ISSUE THREAD

**Issue by frosso** [woocommerce/woocommerce-gateway-stripe#1662]
## Description

We will be fully porting UPE and the new settings design to the Stripe plugin: pc4etw-hj-p2
The data layer used by WCPay uses `@wordpress/data` and a PHP controller to save/retrieve the data.

## Questions
- Can/should we use the same approach here?
  - What libraries are we missing?
- What settings do we need to store?

**Comment by waclawjacek** [comment]
## Can/should we use the same approach here?

### Can we?

For WCPay, we have replaced the PHP-generated settings page with a React-powered one. Since this approach consists of enqueuing the right scripts on the right page, which then houses the JS talking to REST API endpoints, I do not see any compatibility problems with replicating this approach in this extension.

We will, however, need to make sure that the necessary JS libraries are imported.

One thing that will have to be verified is version support. [The extension's current `Requires at least` header is `4.4`.](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/38744bb1c4add59869f5067734c0960f726b1228/readme.txt#L4) (WCPay's is `5.6`.) The WordPress REST API was publicly released in `4.7`.

This could be a potential blocker in trying to reuse some of the code, possibly forcing us to revise the supported version policy. I did not check version support during this spike.

### Should we?

The settings are pretty similar to WCPay's which is a strong argument in favor of using the same approach, with departures in some non-blocking cases:

* Multiple payment methods are supported even if UPE is disabled, meaning support for it in new settings will be required.
  * This is different than UPE payment methods.
* ~More than one express checkout customization page (separate for different methods).~ (No longer part of scope.)
* Support for using no payment methods (= using only express checkouts).
  * This should not cause any problems on the settings side of things.

Using a unified approach will be beneficial for maintenance and adding new features.

### What libraries are we missing?

This is not an exhaustive list but a list of the more prominent packages that stood out to me while browsing the code. On the PHP end, I did not notice any missing dependencies.

- **React:** react, react-dom
- **WordPress packages:** @wordpress/api-fetch, @wordpress/components, @wordpress/data, @wordpress/data-controls, @wordpress/element, @wordpress/hooks, @wordpress/i18n, @wordpress/icons, @wordpress/url
- **Testing:** @testing-library/react, @testing-library/user-event, @testing-library/jest-dom
- **Other:** classnames, lodash

## What settings do we need to store?

### Screenshots for some context

In the current version of the extension, settings are divided into separate gateways:

![Markup on 2021-08-10 at 14:09:26](https://user-images.githubusercontent.com/1759681/129727554-6badf0a5-91fa-49d4-b294-c9ee917f34ff.png)

The main gateway looks like this:

![Markup on 2021-08-17 at 14:02:30](https://user-images.githubusercontent.com/1759681/129727575-e24e9c9e-7d63-4921-97a0-ab1d48df5837.png)

Each gateway (aside from the main "Stripe" one) looks like this:

![Markup on 2021-08-10 at 14:11:02](https://user-images.githubusercontent.com/1759681/129727597-38d8a486-e19c-4e4d-a69f-820e9f5d91e3.png)

### Existing settings

#### In general settings (i.e. the main Stripe gateway)

- Stripe enabled: yes/no
  - Toggling disables the gateway on the WC > Payments page.
- Title
- Description
- Enable test mode: yes/no
  - Depending on this, the extension will present inputs to enter live or test API keys (below).
- Live API keys:
  - Live publishable key
  - Live secret key
  - Live webhook secret
- Test API keys:
  - Test publishable key
  - Test secret key
  - Test webhook secret
- Separate credit card form enabled: yes/no
  - This adjusts credit card form display styles
- Customer bank statement (22 chars)
- Capture charge later: yes/no
- Payment request buttons
  - Enabled: yes/no
  - Button type
  - Button theme
  - Button height
    - **Changed in new settings:** allow selecting one of predefined sizes instead of inputting a number
  - Note that there is no option to select where to display the payment request buttons. More in "New settings" below.
- Saved cards enabled: yes/no
- Debug logging enabled: yes/no

#### On each payment method's settings page

**Note:** If we roll out UPE as opt-in early access, even though with UPE there is no option of changing the title and description (they are automated), if someone does not opt into using UPE we will have to support inputting the title and description for a payment method in the new settings.

- Method enabled: yes/no
- Title
- Description

### New settings

- Where to display express checkouts?
  - **Note:** At the moment there is only one checkbox in the extension deciding whether to display express checkouts or not. Checking it will display express checkouts on the Cart and Single Product pages. Tweaking this behavior is [currently supported using filters](https://docs.woocommerce.com/document/stripe/#code-snippets). The option values controlled by the below checkboxes could act as defaults for these filters.
  - Checkout: yes/no
  - Product page: yes/no
  - Cart: yes/no
- Accepted payment methods
- ~Enabled express checkout methods~ (No longer part of scope - this is "if" express checkout is enabled now.)
- Was the "View your Stripe payment methods all in one place" dialog closed?
![Markup on 2021-08-17 at 15:32:56](https://user-images.githubusercontent.com/1759681/129734998-a046da9b-49d2-4fe8-b3fb-d6820abc997f.png)

#### Feature flags

UPE and the setting screens are planned to be released together. I suggest keeping separate feature flags for them just in case (testing and to be able to revert on-the-fly):

- Is UPE preview enabled?
- Is UPE enabled?
- Is new settings design enabled?

#### API endpoints

- Endpoints for storing settings
- Endpoint for getting current fees (unless they are always the same in which case they can be stored on the client side)
- Endpoint for getting payments and deposits status and connected account name
  ![Markup on 2021-08-17 at 15:35:26](https://user-images.githubusercontent.com/1759681/129735348-d7537d0a-b1c0-4083-97f2-1c7d7b3013e8.png)
- Endpoints for onboarding tasks - marking them as completed and enabling UPE

## Other notes

- ~What should be the customization options for other express checkouts than Apple Pay/Google Pay?~ (No longer part of scope.)
- Support for having no payment methods might be problematic - a dummy gateway might be necessary.
- Survey will be a link, not requiring a Jetpack connection: pc4etw-ch-p2#comment-709
- Something I found interesting: the Stripe extension [contains some code talking to the Connect Server](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/38744bb1c4add59869f5067734c0960f726b1228/includes/connect/class-wc-stripe-connect-api.php#L93) for the purpose of the OAuth flow.
