### ISSUE TITLE
Stripe API Test Keys - no more pk_test prefix

### ISSUE THREAD

**Issue by cguweb-com** [woocommerce/woocommerce-gateway-stripe#1664]
**Describe the bug**
Settings gives the following errors when setting up test mode for stripe:

The "Test Publishable Key" should start with "pk_test", enter the correct key.
The "Test Secret Key" should start with "sk_test" or "rk_test", enter the correct key.

And this doesn't seem to be the case any longer, as my new stripe test keys just have pk_ prefixes

If I am correct, then your Stripe test mode is broken badly right now, and cannot be used / doesn't show up at checkout.

**To Reproduce**
1. woocommerce settings payments stripe manage and enable test mode with latest test key from stripe, which you'll see has no pk_test prefix.

**Comment by dougaitken** [comment]
Hey @cguweb-com 

I appreciate some time has passed since the original comment, thanks for your patience. I’ve been unable to replicate the issue you described using the latest release of the core WooCommerce plugin and the [WooCommerce Stripe Payment Gateway](https://wordpress.org/plugins/woocommerce-gateway-stripe/).

> as my new stripe test keys just have pk_ prefixes

If this is still showing for you, I would check that your Stripe account is in Test Mode - `https://dashboard.stripe.com/test/apikeys` - note the `test` in the URL. 

I've rolled my own test keys for a test site and the new ones still have `pk_test` and `sk_test`

As I’m unable to reproduce this, I’m marking this Issue as Closed. Please do open a new one if you are able to reproduce this again.
