### ISSUE TITLE
SPIKE - UPE in Blocks Checkout

### ISSUE THREAD

**Issue by bborman22** [woocommerce/woocommerce-gateway-stripe#1667]
Currently the plugin [uses its own APIs to perform a block checkout](https://github.com/woocommerce/woocommerce-gateway-stripe/tree/develop/client/blocks). The goal of this spike is to provide details and a recommendation for building out the UPE block checkout using the plugin's APIs or using the [WC Blocks APIs](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/extensibility/checkout-flow-and-events.md).

Some things to keep in mind:
* Determine the current interest/priority in moving existing gateways to the Blocks API
* Determine possibility of having the existing block checkout flow co-exist with a UPE Blocks checkout flow
* Determine scope/concerns of implementing the blocks checkout flow vs using the existing flow

**Comment by reykjalin** [comment]
As per our documentation [here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/client/blocks/README.md) we should only use the AJAX APIs if there's a limitation in the Blocks API that makes it infeasible to do so.

**Comment by ricardo** [comment]
As per the above [documentation](https://github.com/woocommerce/woocommerce-gateway-stripe/tree/develop/client/blocks#why-we-chose-to-use-our-pre-existing-ajax-apis-instead-of-the-woocommerce-blocks-apis-for-payment-request-buttons):

> Why we chose to use our pre-existing AJAX APIs instead of the WooCommerce Blocks APIs for **Payment Request Buttons**

The plugin uses its own APIs for the express checkout block (payment request buttons), but it uses the Blocks API for the credit card checkout. Other payment methods are currently not implemented.

WCPay also uses a separate API for the express checkout block, so for the UPE checkout block, I believe the implementation would look pretty similar to WCPay's 2429-gh-Automattic/woocommerce-payments.

👉 So, to answer the main concern of this issue, I think we can build the UPE checkout block using the Blocks API, just as the regular checkout block.

I also don't see any trouble in getting the express checkout block and the UPE block co-exist in the same checkout flow. That's apparently working as expected in WCPay right now.

> Determine scope/concerns of implementing the blocks checkout flow vs using the existing flow

@bborman22 by using the existing flow, do you mean the existing AJAX APIs? If so, I think I answered it above, otherwise could you elaborate more?

**Comment by ricardo** [comment]
@bborman22 As an additional question, should we support other payment methods in the blocks checkout as part of this issue? Since only credit card is supported with the non-UPE block checkout right now.

**Comment by bborman22** [comment]
I think some work has started on this already, which is great, but wanted to answer the two questions posed still. For the existing flow question, that was just related to the AJAX API, which was addressed and answered my question that the Blocks API will be used. 

> As an additional question, should we support other payment methods in the blocks checkout as part of this issue? Since only credit card is supported with the non-UPE block checkout right now.

If I'm understanding the question correctly, we shouldn't be putting any effort in to support non-UPE payment methods in the blocks checkout (at least related to this issue). However, we should be able to have all the payment method types available within UPE supported in blocks checkout, unless we have some limitation there that I'm not aware of.

**Comment by reykjalin** [comment]
> I think some work has started on this already

Correct; I just linked #1825 to this issue 🙂 

> we should be able to have all the payment method types available within UPE supported in blocks checkout, unless we have some limitation there that I'm not aware of

I don't expect any issues here either, I think it'll just be a matter of enabling the APMs and possibly applying some minor style changes.
