### ISSUE TITLE
[settings] Onboarding wizard functionality

### ISSUE THREAD

**Issue by frosso** [woocommerce/woocommerce-gateway-stripe#1718]
## Description

Implement the functionality for the onboarding wizard

## Acceptance criteria
- UI matches designs
- First step shows informative text (done in https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1683)
- First step allows enabling UPE (use https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1724 to toggle the flag)
- Second step allows enabling additional available payment methods (UI matches design)
- Third step lists enabled payment methods

**Comment by waclawjacek** [comment]
@jarekmorawski I have two questions for you! :)

## "X new methods are now live"

A message in the last step says "X new methods are now live on your store!"

Since some of the payment methods might have already been supported on a store using traditional payment gateways rather than UPE, what should we display here?

E.g. let's say a merchant had Sofort enabled and during UPE onboarding, they select Sofort and Giropay. Should the message say 2 new methods were enabled or just 1?

![Markup on 2021-09-07 at 08:56:44](https://user-images.githubusercontent.com/1759681/132298492-63b3127b-3b47-4d7b-bb7b-6ae4a791fff8.png)

## Methods selected by default

Should only the methods that have been enabled using traditional gateways be enabled during UPE onboarding? I.e. let's say Giropay's been supported in a store using a traditional gateway. Should the onboarding display this?

![Markup on 2021-09-07 at 09:01:24](https://user-images.githubusercontent.com/1759681/132299129-c0caaa52-be09-4cc5-a38b-e9712a8ed01b.png)

**Comment by jarekmorawski** [comment]
Hi there! 👋 

> Since some of the payment methods might have already been supported on a store using traditional payment gateways rather than UPE, what should we display here?

Great question. Now when I think of it, perhaps it makes more sense to remove the "new" part and only say "X payment methods are now live on your store!". The X would be the number of all selected payment methods, both previously enabled and new ones selected during the UPE setup.

I will update the designs.

> Should only the methods that have been enabled using traditional gateways be enabled during UPE onboarding? I.e. let's say Giropay's been supported in a store using a traditional gateway. Should the onboarding display this?

Yes. If I had giropay and Sofort enabled in Settings > Payments, these two should be pre-selected during the setup.

**Comment by waclawjacek** [comment]
Awesome, thank you! Great idea with the "X payment methods are now live" messaging.

**Comment by waclawjacek** [comment]
This issue has to wait for design decisions due to some extra setup being necessary on merchants' side: p1631001920004300-slack-C01RTUVR81K

**Comment by frosso** [comment]
@waclawjacek I moved the effort on this task forward a tiny bit by ensuring the "Enable" button works: https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1803 - that seems to be one of the parts of the task that are not currently blocked.

EDIT: lol the PR got assigned to you anyways 😅

**Comment by frosso** [comment]
Closing in favor of https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1887
