### ISSUE TITLE
Apple Pay should work in Saudi Arabia

### ISSUE THREAD

**Issue by aheckler** [woocommerce/woocommerce-gateway-stripe#1799]
**Describe the bug**
Apple Pay not available for stores in Saudi Arabia, but it should be.

**To Reproduce**
1. WC test site with Stripe active.
2. Set shop address to `Al-Khobar, Saudi Arabia 31952`
3. In Stripe settings, turn on payment request buttons.
4. Open shop in Safari and navigate to a product page.
5. Apple Pay doesn't appear. Console error:

<img width="1520" alt="Markup 2021-09-07 at 09 34 06" src="https://user-images.githubusercontent.com/5512652/132366763-dd216cdb-20f5-4260-9a4b-4a9e5db78636.png">

**Expected behavior**

Apple Pay seems like it should work. (Not sure about Google.)

According to this page: https://stripe.com/apple-pay 

> Stripe supports Apple Pay in all countries where Apple Pay is accepted.

And it turns out Apple Pay is accepted in Saudi Arabia: https://support.apple.com/en-us/HT207957

cc @jrodger per p1631021663190200-slack-C7U3Y3VMY

**Comment by ricardo** [comment]
Saudi Arabia isn't supported as the store country by Stripe and therefore it's not possible to initialize payment request buttons with the store based in `SA`.

There's a second problem where even if the store country is supported, there's no way a customer can checkout with Apple Pay, because Apple Pay doesn't provide the necessary fields for WooCommerce when checking out in Saudi Arabia or other countries not supported by WooCommerce + Payment Request buttons.

Added "priority: low" because although there are certainly other unsupported countries, ideally this should be fixed in core by adding more flexibility to the format provided by the Payment Request API.

There are pending compatibility discussions in WC core around this (https://github.com/woocommerce/woocommerce/issues/29795). If that doesn't get fixed in core, we can try to propose another workaround.

For internal context: p1631027271050400-slack-C01BZUL57SQ

**Comment by Baribj** [comment]
Are there any updates on this issues ?

**Comment by ricardo** [comment]
@ritwaldev Unfortunately Stripe is still not supported in Saudi Arabia.

https://stripe.com/global

**Comment by Baribj** [comment]
Hi @ricardo Stripe's Apple Pay is supported in Saudi Arabia as per your comment above.  I was actually referencing the second issue where the Apple Pay would throw an error due to state field not being passed.

Apple Pay doesn't require a State field for users in SA.

Its been almost 3 months now and I think this ticket should get a bit more attention since payment with Apple Pay accounts to almost 63% of all sales of one of the biggest shopping apps in SA. 

Apply Pay is largely adopted in SA and being able to offer that option to customers in SA is absolutely crucial.

**Comment by ricardo** [comment]
@ritwaldev, I see what you mean. Apple Pay is supported, for customers, but Saudi Arabia is not supported as the store country by Stripe.

For clarification, the second issue is because WooCommerce requires a state field while Apple Pay does not provide it. Ideally WooCommerce should provide better ways to handle express payments.

One way you could fix the second issue is by overriding the WooCommerce core state validation. If you add this to your functions.php, I believe it should work:

```php
add_filter( 'woocommerce_checkout_fields', 'woocommerce_override_state_validation' );

function woocommerce_override_state_validation( $checkout_fields ) {
	if ( isset( $checkout_fields['billing']['billing_state']['country'] ) && 'SA' === $checkout_fields['billing']['billing_state']['country'] ) {
		$checkout_fields['billing']['billing_state']['required'] = false;
	}

	if ( isset( $checkout_fields['shipping']['shipping_state']['country'] ) && 'SA' === $checkout_fields['shipping']['shipping_state']['country'] ) {
		$checkout_fields['shipping']['shipping_state']['required'] = false;
	}

	return $checkout_fields;
}
```

**Comment by Baribj** [comment]
@ricardo This is a nice workaround. Thanks for sharing this.

**Comment by dougaitken** [comment]
> Stripe supports Apple Pay in all countries where Apple Pay is accepted.

I believe this is on the condition that Stripe is supported in that country where the merchant is located. 

Closing as the is a workaround provided but also this isn't a Stripe plugin limitation but a Stripe.com limitation.
