### ISSUE TITLE
The Express Payments button disappears on quantity change

### ISSUE THREAD

**Issue by ralucaStan** [woocommerce/woocommerce-gateway-stripe#1829]
## Describe the bug
The Express Payments button in the Cart block disappears every time the quantity of a product is updated.

## To reproduce
Steps to reproduce the behavior first make sure you have an express payment set up via WooCommerce Stripe Gateway. 

1. Go to a cart page with the Cart Block
2. Increase the quantity of a product
3. Notice how the Express Payment button disappears and then appears again and the content shifts up.

## Expected behavior
The button should not disappear, at most, it should be disabled when the button below is disabled.

## Screenshots
https://user-images.githubusercontent.com/1628454/121048148-37931880-c7bf-11eb-80d5-a8ef217c6995.mov

**Comment by mikejolley** [comment]
@ralucaStan @nerrad Does this still need working on? The behaviour has changed recently. The button does get a loading state, but when the cart is updated, ultimately the button flashes because it's rerendered from scratch. 

![2021-09-09 16 31 52](https://user-images.githubusercontent.com/90977/132716549-fab94c1a-b5ad-45e8-a910-be3f037854b3.gif)

**Comment by mikejolley** [comment]
I've transferred this across but I'm holding off on a PR because there seem to be some new issues with the Stripe integration that I cannot explain. I will test some more and log an issue once confirmed.

**Comment by dougaitken** [comment]
_To ensure the WooCommerce team are having the most impactful work, we review older open Issues on this GitHub repository to find out what is still relevant._ 

I appreciate some time has passed since the original comment, thanks for your patience.

It is possible that this issue has been fixed by a more recent release as I’ve been unable to replicate the issue you described using the latest release of the core WooCommerce plugin and the [WooCommerce Stripe Payment Gateway](https://wordpress.org/plugins/woocommerce-gateway-stripe/). 

As I’m unable to reproduce this, I’m marking this Issue as Closed.
