### ISSUE TITLE
Express Payment Buttons are broken after updating products in the Cart Block

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gateway-stripe#1830]
**Describe the bug**

Testing against the latest version of Stripe (5.4.1) and Blocks (going back as far as v5.0), there is a new incompatibility with the Cart Block and express payments. When the cart changes, the payment request object also updates, but the payment modal does not show updated totals. Additionally, after a cart change, the "cancel" handler fails to run leaving the payment button in a loading state.

I tested this on Edge (chromium) and Chrome. Both showed the same problem. I am marking this as high priority because functionality is broken.

**To Reproduce**
1. Go to a page showing the Cart Block, with items in your cart
2. Click the express payment button
3. Notice the modal shows the correct total. Cancel payment. Notice the button goes back to a clickable state.
4. Change the qty of an item in the cart and wait a few moments for the change to persist.
5. Click the express payment button
6. **Notice the total is wrong.**
7. Click the cancel button in the payment request modal. **Notice the button remains in loading state.**

**Expected behavior**
After updating cart items, the express payment button needs to reflect the new totals.

**Environment (please complete the following information):**
 - WordPress 5.8
 - WooCommerce 5.7.0-dev
 - Stripe 5.4.1
 - Edge/Chrome Browser
 - WooCommerce Blocks 5.9.0-dev

**Comment by reykjalin** [comment]
I've started looking into this but haven't found a solution. I think I've tracked down _why_ this is happening though. The key is this console error:

<img width="1694" alt="image" src="https://user-images.githubusercontent.com/13835680/137647440-65e4cb76-1bdc-471d-9a50-a4608671cf27.png">

In essence; we can't recreate the payment request unless we also destroy and recreate the `PaymentRequestButtonElement`. There's some more discussion on this in https://github.com/stripe-archive/react-stripe-elements/issues/284.

The relevant code is here:

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/06f21325c37c99a084df94c0c2a7dfc80eca08ce/client/blocks/payment-request/payment-request-express.js#L39-L133

I've been trying various methods to use hooks in an attempt to recreate the `PaymentRequestButtonElement`, but haven't been successful so far. I'll keep trying throughout this week 👍 

We're in a situation where we must send an API request to the cart to get the correct information to construct the payment request due to various normalizations and special handling we do on the backend of the store to make sure everything works as intended. This is why we've been recreating the Payment Request up until this point; it's the simplest way to make sure everything is correct after we retrieve the cart data via API.
Since using hooks to recreate the whole component doesn't seem to work, maybe we just have to send that API request and update the payment request using that data instead of re-creating the whole payment request, because **updates to the payment request via `paymentRequest.update()` are allowed**. At least that's what I'll try next 🤔
