### ISSUE TITLE
UPE - SEPA orders should go from "pending" to "on hold"

### ISSUE THREAD

**Issue by ricardo** [woocommerce/woocommerce-gateway-stripe#1850]
The goal of this issue is to bring visibility to an inconsistency between the classic SEPA checkout and the UPE SEPA checkout.

Currently, the UPE SEPA checkout goes from "pending" to "completed/processing", but the classic SEPA goes from "pending" to "on hold" and then "completed/processing" once the webhook is received from Stripe.

Also, the classic checkout adds an order note while the order is "on hold". It works similar as a manual payment:

> Stripe charge awaiting payment: py_******. Order status changed from Pending payment to On hold.

**Steps to reproduce:**
1. Disable UPE.
2. Enable SEPA debit.
3. Install [Stripe CLI](https://stripe.com/docs/stripe-cli).
4. Run `stripe login` and select the Stripe account you're connected to.
5. Run `stripe listen --forward-to 'http://localhost:8082/?wc-api=wc_stripe'` and copy the webhook signing secret (`whsec_******`) to the plugin settings.
6. Perform a SEPA payment with `AT321904300235473204` ([via Stripe SEPA testing](https://stripe.com/docs/testing)) which will succeed after 3 minutes.
7. Before the payment is captures successfully, go to **WooCommerce > Orders** and notice the status of the last order is "On hold". After 3 minutes, the order should be "Completed/Processing".
8. Repeat steps 6 and 7 with UPE enabled and notice the order isn't set to "On hold" and there's no note added to the order.

**Comment by FangedParakeet** [comment]
I _think_ this is because on [this line](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/includes/payment-methods/class-wc-stripe-upe-payment-gateway.php#L555), where we update the order after redirection, for some reason we send the payment intent instead of the charge as a parameter to the `process_response` function. Since SEPA has delayed payment completion, the status of the intent is `processing` and there is no case for that in [this function](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/includes/abstracts/abstract-wc-stripe-payment-gateway.php#L498), so nothing gets updated on the order.

FWIW, this is fixed in #1780, where we [pull the charge from the intent](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/fbb20362ada02e3779f2e1d0b273580a48f646c0/includes/payment-methods/class-wc-stripe-upe-payment-gateway.php#L583) and use that as a parameter instead.

**Comment by ricardo** [comment]
Related https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1943
