### ISSUE TITLE
Empty Express checkout block rendered when Express checkout is disabled in payment method settings

### ISSUE THREAD

**Issue by nickfmc** [woocommerce/woocommerce-gateway-stripe#1877]
I have express payments turned off in Stripe (Enable Payment Request Buttons. (Apple Pay/Google Pay) ) and that is the only payment method I am using . however in Chrome I still see a blank div for the express checkout, so I get the text --- OR --- proceed to checkout.

**Comment by nerrad** [comment]
Thanks for the report! I can reproduce using the following steps:

- In WooCommerce Stripe Gateway settings, uncheck the "Enable Payment Request buttons" option.
- Load the checkout on the frontend, notice that the payment request button does not render but the containing element still does.

<img width="892" alt="CleanShot 2021-09-16 at 13 42 32@2x" src="https://user-images.githubusercontent.com/1429108/133659653-b13b5bb8-dd7b-4b17-96de-96dd0bdb015d.png">

This also impacts the cart (the `-- or ---` should not be displayed):

<img width="531" alt="CleanShot 2021-09-16 at 13 42 18@2x" src="https://user-images.githubusercontent.com/1429108/133659716-cb00d3d4-a712-4ff1-b165-5e672ed6d199.png">

Should note that there is also an uncaught promise error that is actually causing this. Although the Checkout block has an [error boundary](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/26499eaf98bd6d39aea4fbefc592670ca830129c/assets/js/blocks/cart-checkout/payment-methods/express-payment-methods.js#L149-L154), the error isn't caught by it because it is the result of a non-handled promise error. Here's the error stack:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'total')
    at createPaymentRequestUsingCart (utils.js:58)
    at _callee$ (hooks.js:46)
    at tryCatch (regenerator-runtime.js?ver=0.13.7:63)
    at Generator.invoke [as _invoke] (regenerator-runtime.js?ver=0.13.7:293)
    at Generator.next (regenerator-runtime.js?ver=0.13.7:118)
    at asyncGeneratorStep (asyncToGenerator.js:3)
    at _next (asyncToGenerator.js:25)
```

It doesn't look like the Stripe extension is considering that payment requests might not be enabled (or only partially accounting for it)? I also see that there is a separate async request being done to get the cart details for the express payment method instead of using the provided data from the checkout block.

**Comment by nerrad** [comment]
Ideally, if payment request buttons are not enabled, the Stripe extension won't even register the express payment method.

**Comment by dougaitken** [comment]
The workaround here is to delete the Block that contains the Express Payment buttons using the WordPress Editor, but agreed this isn't ideal and the Block shouldn't be rendered at all if the Express Payment button is disabled on the Checkout page.
