### ISSUE TITLE
[documentation] UPE documentation in Stripe docs

### ISSUE THREAD

**Issue by frosso** [woocommerce/woocommerce-gateway-stripe#1899]
## Description

Update the Stripe documentation with a section that mentions UPE.
The new section will be linked from the "Learn more" link in the plugin:
![133829750-9abb3759-5b55-44b8-b74f-9d31007776c7](https://user-images.githubusercontent.com/273592/133853999-bac6f5ff-5fdb-4eb4-893f-13684ad388bb.png)

Feel free to talk with UX about the takeaways the merchant should have from this new section.
One of the takeaways is that UPE does not support all features, like pre-orders.

Once the docs have been updated, please also update the plugin's code to reflect the correct URL.

**Comment by c-shultz** [comment]
Just a note that I'm deprioritizing this issue: https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1821 with the intent that we mention limitations (e.g. "This doesn't work with pre-orders") on a UPE section of the docs.

**Comment by harriswong** [comment]
I am planning on adding a new section (probably 14) in https://docs.woocommerce.com/document/stripe/. The title may be called "New checkout experience". It will include
- how to enable the experimental via the "New checkout experience" checkbox 
![image](https://user-images.githubusercontent.com/572862/134256087-1fa8bccf-a8f4-4605-be1e-69f2785da77f.png)
- overview of the new payment method table after "New checkout experience" is enabled
![image](https://user-images.githubusercontent.com/572862/134256158-1a413f7e-bc12-421b-a70d-89e8b9db80b5.png)
- Explain what the "Get more payment methods" do
![image](https://user-images.githubusercontent.com/572862/134256772-b2a1e7eb-78e9-4571-866e-c7283505301e.png)
- Explain how to enable/disable UPE methods and what is required to do so. Do we need to explain [Stripe's compatibility](https://stripe.com/docs/connect/account-capabilities), or is that gonna introduce confusion? 
- Attach a screenshot of the checkout page; how it would look like when certain UPE payment methods are enabled.
- Stripe UPE does not work with pre-order plugin https://woocommerce.com/products/woocommerce-pre-orders/
- "Capture charge immediately" is required for other payment methods beside card. Otherwise, checkboxes won't show as saved.

@jarekmorawski What do you think of the above?

**Comment by harriswong** [comment]
I created a revision for the doc. Pending review.

**Comment by harriswong** [comment]
Pinged docs guild janitor to review.

**Comment by frosso** [comment]
@harriswong it looks like we should have a pretty good idea of what the link to this new section will be. What are your thoughts on opening a PR to replace the `?TODO` on the settings page, so it's merged in time for the release?

**Comment by harriswong** [comment]
I'm going to use this link that doesn't exist yet: `https://docs.woocommerce.com/document/stripe/#new-checkout-experience` :D

**Comment by harriswong** [comment]
Documentation reviewed. Updated documentation will be published on Sep 29th UTC+1.

**Comment by dougaitken** [comment]
[Docs update published](https://docs.woocommerce.com/document/stripe/#new-checkout-experience)
