### ISSUE TITLE
Shipping amount not passed to payment provider sometimes

### ISSUE THREAD

**Issue by Poolee** [woocommerce/woocommerce-gateway-stripe#1905]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**
On multiple occasions, no discernible pattern, I have received payment for orders through the Stripe payment processor that didn't include the shipping cost.  I have checked with support for the Stripe plugin I am using, however they tell me the issue is with WooCommerce not passing the total amount including shipping.

I expected to receive the [order_amount], but received [amount] instead which was minus the [Total Shipping].

I've included a NORMAL payment for comparison, where [amount] = [order_amount].
No coupons have been used.

Cheers
Paul

[eh_stripe_pay_live-2021-09-15-fcf5cdbefed09416cf72ae34fbe3e4b0.log](https://github.com/woocommerce/woocommerce/files/7175210/eh_stripe_pay_live-2021-09-15-fcf5cdbefed09416cf72ae34fbe3e4b0.log)
[eh_stripe_pay_live-2021-08-20-fcf5cdbefed09416cf72ae34fbe3e4b0.log](https://github.com/woocommerce/woocommerce/files/7175211/eh_stripe_pay_live-2021-08-20-fcf5cdbefed09416cf72ae34fbe3e4b0.log)
[eh_stripe_pay_live-2021-09-01-fcf5cdbefed09416cf72ae34fbe3e4b0 - NORMAL.log](https://github.com/woocommerce/woocommerce/files/7175212/eh_stripe_pay_live-2021-09-01-fcf5cdbefed09416cf72ae34fbe3e4b0.-.NORMAL.log)
[eh_stripe_pay_live-2021-09-04-fcf5cdbefed09416cf72ae34fbe3e4b0.log](https://github.com/woocommerce/woocommerce/files/7175213/eh_stripe_pay_live-2021-09-04-fcf5cdbefed09416cf72ae34fbe3e4b0.log)

**Comment by Poolee** [comment]
@juliaamosova, hi I am using 'Stripe Payment Gateway for WooCommerce ( Basic )' by WebToffee, not WooCommerce's own Stripe plugin, so this needs to go back in woocommerce/woocommerce I believe.

WebToffee have already looked at the issue and have confirmed the problem is not with their plugin, but with the [amount] being passed through from WooCommerce.

**Comment by Poolee** [comment]
@juliaamosova, please review!

**Comment by dougaitken** [comment]
Hi @Poolee 

I appreciate some time has passed since the original comment, thanks for your patience. As you mentioned in a later reply, this issue was a conflict with the `'Stripe Payment Gateway for WooCommerce ( Basic )' by WebToffee` plugin. 

If you're able to still replicate this and it happens using a default theme, this other Stripe plugin, and the latest core WooCommerce plugin, then one option would be to test with another payment gateway such as our own Stripe one, or a default one like Cash on Delivery. 

If you still feel it is a bug, I'd recommend opening a [new bug report GitHub Issue on the core WooCommerce repository](https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=1-bug-report.yml) and clearly stating that the issue is between WooCommerce and this third-party Stripe plugin, with details of why the core WooCommerce plugin is at fault.

Thanks,
