### ISSUE TITLE
Unable to add bancontact method with UPE from my account -> payment methods

### ISSUE THREAD

**Issue by superdav42** [woocommerce/woocommerce-gateway-stripe#1929]
when adding a new payment method in the my account page with UPE enabled it is not possible to use bancontact.

**To Reproduce**
1. Go to My Account -> Payment Methods -> Add New Payment Method
2. Select bancontact. Enter name and email.
3. On stripe page click Authorize

Being able to add a bancontact method.

**Comment by superdav42** [comment]
I traced the problem to [this line ](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/3332c9346610c7c55160ebf6edd6ec085a24b653/includes/payment-methods/class-wc-stripe-upe-payment-method.php#L202). The problem is `$payment_method->sepa_debit->last4` does not exist so WC_Payment_Token_SEPA fails validation because it does not have a last 4 digits.

I'm not sure the best way to fix this since neither the payment method object or the setup intent object have the SEPA last four digits. Only the Payment intent seems to have this data which is how it works when saving the payment method at checkout. 

I think the best way to fix this would be to create a new payment token class for bancontact and iDeal. The only information we can add to these to differentiate them is the billing_details.name and billing_details.email. I'm not sure this would be enough. I do think it'd be better to show the saved methods as bancontact instead of transforming them into IBAN. But we'd still have a problem if a customer wants to save two bancontact payment methods and they use the same email and name because they would appear to be the same payment method.

@FangedParakeet Do you have thought on how to solve this?

**Comment by EvanDotPro** [comment]
I agree the conversion from bancontact to SEPA IBAN doesn't seem right in this case and that a separate token class implementation makes sense if the validation criteria differs (i.e., no last 4).

**Comment by FangedParakeet** [comment]
Yes, I have some thoughts! This is off the top of my head, but I'm somewhat confident about what I'm about to describe. 

@superdav42, I don't think you can use `add_token_to_user_from_payment_method` inside `create_token_from_setup_intent`, because if the payment method is Bancontact or iDEAL--that gets converted to a SEPA payment method to be used with recurring payments--the payment method ID on the intent will be for the payment method used for the initial purchase (i.e. the Bancontact/iDEAL payment method) _not_ the generated SEPA payment method. That's actually why I left [this comment](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/3332c9346610c7c55160ebf6edd6ec085a24b653/includes/payment-methods/class-wc-stripe-upe-payment-method.php#L192-L193), because my intention was to use the function `add_token_to_user_from_intent` at this point instead. 

You can see that with the [card payment method](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/3332c9346610c7c55160ebf6edd6ec085a24b653/includes/payment-methods/class-wc-stripe-upe-payment-method-cc.php#L78-L80) and [SEPA payment method](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/3332c9346610c7c55160ebf6edd6ec085a24b653/includes/payment-methods/class-wc-stripe-upe-payment-method-sepa.php#L49-L51), `add_token_to_user_from_intent` is basically just a wrapper for `add_token_to_user_from_payment_method`: I [expand the payment method field](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/3332c9346610c7c55160ebf6edd6ec085a24b653/includes/payment-methods/class-wc-stripe-upe-payment-gateway.php#L722), so that `$intent->payment_method` returns the entire payment method object instead of just the payment method ID, and pass this payment method object to `add_token_to_user_from_payment_method` from `add_token_to_user_from_intent`. However, for [other payment methods](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/3332c9346610c7c55160ebf6edd6ec085a24b653/includes/payment-methods/class-wc-stripe-upe-payment-method.php#L177-L187), that function does something a bit different.

On payment methods that get converted to SEPA I needed to [look inside the payment method details on the charge](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/3332c9346610c7c55160ebf6edd6ec085a24b653/includes/payment-methods/class-wc-stripe-upe-payment-method.php#L250-L253) to find these [additional `generated_sepa_debit` fields](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/3332c9346610c7c55160ebf6edd6ec085a24b653/includes/payment-methods/class-wc-stripe-upe-payment-method.php#L183) that we need to use as the payment method ID when we save the token. Just FYI, if you try making these requests through Postman or something like that where you can see the full response, it's clearer to see these fields.

If you expand the payment method field [here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/3332c9346610c7c55160ebf6edd6ec085a24b653/includes/payment-methods/class-wc-stripe-upe-payment-gateway.php#L1141) inside `create_token_from_setup_intent`, like I suggested we do [here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/3332c9346610c7c55160ebf6edd6ec085a24b653/includes/payment-methods/class-wc-stripe-upe-payment-gateway.php#L724), you won't actually need to make a separate call to `payment_methods/` [here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/3332c9346610c7c55160ebf6edd6ec085a24b653/includes/payment-methods/class-wc-stripe-upe-payment-gateway.php#L1147), because you can just pull the payment method from the intent.

However, the one big mystery is that I have only tested this above process with payment intents--not setup intents, since setup intents weren't yet implemented when I implemented saving payment methods--so I'm not sure where this `generated_sepa_debit` field will be, since I don't think there is a charge object on a setup intent. That's why I left this [little TODO](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/3332c9346610c7c55160ebf6edd6ec085a24b653/includes/payment-methods/class-wc-stripe-upe-payment-method.php#L255). I'd recommend looking at the full setup intent response object and see if that `generated_sepa_debit` is tucked away elsewhere. Otherwise I've noticed that if you look into the details on the payment method, there is a `generated_from` field that is usually `null`: perhaps this field will be populated in this scenario. Unfortunately, that's a mystery I'll have to leave unto you to solve, @superdav42!

![generated_from field](https://cdn-std.droplr.net/files/acc_1104206/ow1AZs)
_Mysterious `generated_from` field on payment method_ 

Let me know if any of the above didn't make sense, because I'm pretty sure that's what's going wrong here.

**Comment by EvanDotPro** [comment]
Very informative, thanks @FangedParakeet! This actually clarified a couple of inaccurate assumptions I had made. :)

**Comment by FangedParakeet** [comment]
One last thing, because you guys mentioned creating a separate token class for Bancontact and iDEAL: I added [this extra `$payment_method_type` property](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/includes/class-wc-stripe-sepa-payment-token.php#L36-L41) on `WC_Payment_Token_SEPA`, which gets set [here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/includes/payment-methods/class-wc-stripe-upe-payment-method.php#L222) when the payment token is created. This was my idea to store the original payment method type of the payment token, in case it had been converted to SEPA from another payment method. 

This gets referenced [here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/includes/class-wc-stripe-payment-tokens.php#L255-L256), so that if, for example, you disable a payment method with converted saved payment method tokens, these payment tokens won't appear anymore. I.e. if I save a bunch of payment tokens with Bancontact and another bunch with SEPA, even though they are all `WC_Payment_Token_SEPA` tokens, the Bancontact tokens will only be available while Bancontact is enabled. I'm pretty sure this is working, if you fancy trying that out. 

Let me know if you think that's a good enough approach or if you guys think we might need to make a new token class instead.

**Comment by superdav42** [comment]
I have tested if the tokens and payment methods work as things are by just disabling the validation of the last4 digits. It lets me save a bancontact payment method just fine and it works at checkout. So really the issue we need to solve is a display one. 
![image](https://user-images.githubusercontent.com/1534605/134466542-370339bd-6033-4209-85fe-282dea489790.png)
The last two methods are bancontact methods but there's no way to differentiate them if there are two added. 

I think the ideal solution is to let the customer give each payment method a nickname to identify them but this may require some WC core changes.

I'll investigate further.

**Comment by FangedParakeet** [comment]
I wonder if we can update these labels dynamically by doing something more with the filters we have on `woocommerce_payment_methods_list_item` or `woocommerce_get_credit_card_type_label` that set the SEPA label [here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/includes/class-wc-stripe-payment-tokens.php#L347-L363) and [here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/includes/class-wc-stripe-payment-tokens.php#L41-L55)...I think you should be able to get the original Stripe payment method by calling `get_payment_method_type()` on the WC payment token as things stand now.
