### ISSUE TITLE
UPE and non-UPE modes have separate saved card sets

### ISSUE THREAD

**Issue by waclawjacek** [woocommerce/woocommerce-gateway-stripe#1998]
**Describe the bug**

Toggling UPE results in a different set of saved cards presented.

This does not seem to affect cards associated with subscriptions.

**Expected behavior**

The same list of cards is presented.

**Screenshots**

![Screen Capture on 2021-09-29 at 13-04-25](https://user-images.githubusercontent.com/1759681/135256729-d15c21f0-f3fc-46ed-8827-ab4260a065b6.gif)

**Environment (please complete the following information):**
 - WC Stripe 5.6-test

**Comment by superdav42** [comment]
To be clear they are not separate sets. It is possible to use saved payment tokens created before UPE was enabled but not possible to use payment tokens saved when with UPE after UPE is disabled.

This is because  the classic Stripe gateway uses payment sources but UPE uses payment intents. The newer payment intents API is backwards compatible with payment sources but it doesn't work the other way around.

The only way to really fix this would be to add support for payment intents in the classic gateway. Not a trivial task but should be possible and probably something that should be done eventually. While we are at it we'll probably want to switch to using payment intents and setup intents throughout the plugin.

**Comment by FangedParakeet** [comment]
Just wanna add that I specifically added [this](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/includes/class-wc-stripe-payment-tokens.php#L191-L195) and [this](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/includes/class-wc-stripe-payment-tokens.php#L217-L221) in the function that gets the payment tokens for the non-UPE gateway, so that payment methods saved in the UPE gateway do not appear when the non-UPE gateway is enabled, because they cannot be used with the Sources API and will throw angry errors. I think going the other way (from non-UPE to UPE) the tokens should be retained--at least for the card gateway, because they share the same gateway ID.
