### ISSUE TITLE
Payment failing with error

### ISSUE THREAD

**Issue by BrentOzar** [woocommerce/woocommerce-gateway-stripe#2069]
**Describe the bug**
My payments are going through fine, including renewal payments, except for one user.

When one of my users tries to check out with an early renewal of a WooCommerce subscription, using a different credit card than they'd initially used, they get an error:

"Sorry, we are unable to process your payment at this time. Please retry later."

In the Stripe plugin debug logs and in my Stripe dashboard, I get this failure error:

```
{
  "error": {
    "code": "payment_intent_unexpected_state",
    "doc_url": "https://stripe.com/docs/error-codes/payment-intent-unexpected-state",
    "message": "This PaymentIntent's payment_method could not be updated because it has a status of succeeded. You may only update the payment_method of a PaymentIntent with one of the following statuses: requires_payment_method, requires_confirmation, requires_action.",
    "payment_intent": {
      "id": "pi_0HlgZv0A5YEjST1IJ4usP1V0",
      "object": "payment_intent",
      "amount": 29500,
      "amount_capturable": 0,
      "amount_received": 29500,
      "application": null,
      "application_fee_amount": null,
      "canceled_at": null,
      "cancellation_reason": null,
      "capture_method": "automatic",

```

This happens every time to this one user, and has been happening for a few days. Not urgent - I just gave this customer another year of free membership to work around it, but wanted to open the issue to help diagnose the root cause if we can.

**To Reproduce**
I don't have a quick way to reproduce this in its entirety.

**Expected behavior**
The payment should complete.

**Screenshots**
I have a video of the user trying to go through the checkout process if that helps. I don't want to post it publicly since it has the customer's name/address.

**Environment (please complete the following information):**
The WooCommerce/WordPress status report is attached. I'm running WordPress 5.8.1, WooCommerce 5.8.0, and Stripe Gateway 5.6.2.

[Status.txt](https://github.com/woocommerce/woocommerce-gateway-stripe/files/7346016/Status.txt)

**Comment by dougaitken** [comment]
Hey @BrentOzar 

I appreciate it has been some time since you posted, we're working our way through older GitHub Issues to ensure we catch up and keep up. 

This would fall under a support requests and this is handled by the Happiness Engineers for the WooCommerce Stripe plugin. If you post this in the [WooCommerce Stripe Support Forums](https://wordpress.org/support/plugin/woocommerce-gateway-stripe/), someone will be able to offer support or advice there.

Alternatively, head to [WooCommerce.com > My Account > Support](https://woocommerce.com/my-account/create-a-ticket/) and open a support request with the team, choose **Stripe** from the _I need help with:_ dropdown menu.
