### ISSUE TITLE
[settings] Add pending activation flow/notice

### ISSUE THREAD

**Issue by cesarcosta99** [woocommerce/woocommerce-gateway-stripe#2090]
## Description

Add the pending activation notice to the payment methods list. Notice should be displayed during UPE onboarding flow and in the settings. The pending activation status is based in the account capabilities. 

The flow/notice consists in:

1. Show a modal when the merchant tries to enable the payment method that requires activation
![image](https://user-images.githubusercontent.com/10233985/138355691-016add8d-cb80-48a3-ae18-b82ee02a05a6.png)
2. Flagging the payment method with a pill
![image](https://user-images.githubusercontent.com/10233985/138355871-c4131d67-a3dc-4a43-a134-f79c4f531749.png)

## Questions

- Is there a way for us to know which information is required (and are missing) to enable specific payment methods?
- Is that email in the modal the Stripe account email or the store owner email? In case it's the first, from a previous research (p1632324818229800-slack-C01BZUL57SQ) I found out that Stripe does not provide that info through their API, however some research can be done in order to confirm that. The messaging in the tooltip may need to be changed as well.
- What actions must be taken after user clicks on Continue button?
  - Enable the payment method?
  - Do something on Stripe's behalf to send that email? If yes, what and how?
- Does the pill is always visible or when the payment method is enabled only?
- Any other questions?

## Acceptance criteria
- Behavior has been clarified
- UI matches design
- Functionality is implemented
- Modal behaves similar to other modals in mobile

**Comment by ricardo** [comment]
Jumping in to help answering some of the questions:

> Is there a way for us to know which information is required (and are missing) to enable specific payment methods?

Yes, we can get such information from the [capabilities](https://stripe.com/docs/api/capabilities) API.

```
curl https://api.stripe.com/v1/accounts/acct_******/capabilities/sepa_debit_payments \
  -u sk_test_******:
```

And check the [requirements](https://stripe.com/docs/api/capabilities/object#capability_object-requirements) attribute.

However, some capabilities can't be requested from certain countries, e.g trying to request a requirements status for SEPA in Brazil would return the following error:

```
The sepa_debit_payments capability is not requestable for accounts in BR.
```

And that raises another question, what should we do in those cases?

> What actions must be taken after user clicks on Continue button?

If we were planning to trigger some sort of activation or follow up email with requirements, we might need a re-design for this step, because although this applies for connected accounts, we can't request capabilities for standard accounts through the API. As Stripe confirmed: p1631639985148800/1630537567.054800-slack-C9976E5MJ. Merchants will have to go to their dashboard and request the capabilities from there.

We also need to consider how we're going to display the payment methods that are not supported, or if we should display these at all.

> Is that email in the modal the Stripe account email or the store owner email?

We might want to reconsider if we want to display this messaging, since we can't request capabilities on merchants' behalf, but I think the idea was to have Stripe send an email to the Stripe account owner, but as Stripe doesn't allow us to retrieve the authentication email, we should probably just omit it.

> Does the pill is always visible or when the payment method is enabled only?

I think this is a matter of UX. IMO it's nice to show that some requirements are pending for the account in order to enable the APM, even if it's not enabled.

---

That said, I think we need to have these in mind in order to move forward:

1. We can't request new capabilities on merchants' behalf, so we can probably keep the "Get more payment methods" button as a way to access the capabilities dashboard and manually request new capabilities, and have something in our documentation which makes it clear that some countries don't offer certain payment methods.
2. We need to do something about the payment methods that are not supported at all for the Stripe account. IMO we could either have them totally disabled without the option to enable it (like in [this screen](https://user-images.githubusercontent.com/5509901/140255530-d8dad3f6-ccab-4680-8d08-bf1990b12d47.png)), or not show them at all. We could leverage the capabilities attribute from the accounts endpoint and diff that against all the UPE payment methods and display the list accordingly.

**Comment by cesarcosta99** [comment]
As a reference, in WCPay that notice is displayed under three capability statuses and contain the following messaging:

1. `pending`: `{method name} is pending approval. Once approved, you will be able to use it.`
2. `pending_verification`: `{method name} won't be visible to your customers until you provide the required information. Follow the instructions sent by our partner Stripe to {store admin email}.`
3. `inactive`: `To use {method name}, please contact WooCommerce support.`

IMO, that implementation is simple enough and cover all the ground for the merchant to understand what action they need to take, especially because we can't request new capabilities on merchants' behalf, as you well said, @ricardo. It may be a good idea to adjust the messaging a little bit, though.

**Comment by jarekmorawski** [comment]
> And that raises another question, what should we do in those cases?

Interesting issue! My guess is that Stripe will prevent merchants from turning on these methods in the first place. In that case they wouldn't appear in the plugin since we should make sure the list aligns with Stripe's and includes methods that 1) we support in the UPE 2) are available to enable/enabled in Stripe.

> we can't request capabilities for standard accounts through the API.

That's correct. I've removed this step from the design. To add new payment methods, merchants must go to the Stripe dashboard, then refresh the list in Stripe.

> We need to do something about the payment methods that are not supported at all for the Stripe account.

As mentioned on P2 (pc4etw-lh), unsupported payment methods shouldn't be visible in the UPE at all. Even if merchant enables it in the dashboard, it won't appear in the plugin.

> Is that email in the modal the Stripe account email or the store owner email?

Stripe account email. If we're not able to obtain it through the API, we can tweak the copy to avoid mentioning the email: "(...) Follow the instructions we've sent to the email address linked with your Stripe account."

> Does the pill is always visible or when the payment method is enabled only?

It's visible at all times.

**Comment by cesarcosta99** [comment]
Copying recent internal discussion p1636128079031800-slack-C02BHNRN6R1.

**Comment by ricardo** [comment]
@jarekmorawski, I have a couple remaining questions, but went ahead and opened a PR with a few suggestions.

**Question 1:** I saw that the "One more step to enable" modal was moved to "Junk" on Figma, and since we can't request capabilities for the merchant on Stripe, this step got removed, right?

Also, the tooltip/popover on Figma had the same copy from WCPay, mentioning that an email would be sent to the merchant, but as we discussed here, that wouldn't be possible on the Stripe extension, so I've proposed an idea on PR #2143:

<img width="530" alt="Stripe SEPA pending activation notice" src="https://user-images.githubusercontent.com/5509901/141398061-7e4deb2e-bf24-4425-b4ab-d132ef3345c6.png">

Edit: screenshot is outdated, @cesarcosta99 actually [proposed](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2143#issuecomment-967657531) an improvement to the copy.

> %s won't be visible to your customers until you activate it in the {{stripeDashboardLink}}Stripe dashboard{{/stripeDashboardLink}}. Once it's active, click {{refreshPaymentMethods}}here{{/refreshPaymentMethods}} to dismiss.

Regarding the first part of the tooltip "{Payment method title} won't be visible to your customers until you activate it in the [Stripe dashboard](https://dashboard.stripe.com/settings/payments).", since the payment method activation needs to be done by the merchant from the Stripe dashboard, I've tweaked the copy to include a link to the Stripe dashboard where the action needs to be taken.

**Question 2:** Do you think it's OK/desirable to have a link on that tooltip? How about the styling of the link?

Regarding the last part of the tooltip copy "Once it's active, click [here](#) to dismiss this notice.", there was an extra problem with Stripe, that since the actions need to be taken _outside_ of the plugin, we can't know when the payment method gets activated, so it's necessary to add a way to refresh the payment method and dismiss the "pending activation" notice.

**Question 3:** Do you think it's ok to have that kind of action embedded in the tooltip, or would it be better to instruct the user to click somewhere else to refresh? I guess it's easier for them to simply click on the tooltip, because this can be displayed on multiple pages, and we would need different instructions depending on where the user is.

Any other thoughts/ideas? Perhaps changing the messaging?

**Comment by jarekmorawski** [comment]
Thanks so much for your initiative and input, @ricardo. 🙇 

> Question 1: I saw that the "One more step to enable" modal was moved to "Junk" on Figma, and since we can't request capabilities for the merchant on Stripe, this step got removed, right?

Yes!

> Also, the tooltip/popover on Figma had the same copy from WCPay, mentioning that an email would be sent to the merchant, but as we discussed here, that wouldn't be possible on the Stripe extension, so I've proposed an idea on PR #2143:

That's a good idea. Firstly, AFAIK Stripe sends the emails too when you enable the payments from the dashboard. Secondly, the badge would only appear after the merchant went to the Stripe dashboard and requested activation. We could also display it when someone enabled the payment method in the plugin and we know it's not activated in the dashboard.

I thought we could change the badge's label to `Requires activation` to indicate there's something merchants need to do first. Then the tooltip could say:

> {Payment method title} requires activation in your Stripe dashboard. Follow the instructions there and check back soon.

How does that sound? The badge will appear both before and after someone activates the payment method so it needs to be versatile.

> I've tweaked the copy to include a link to the Stripe dashboard where the action needs to be taken.

Perfect! Thank you so much.

> Regarding the last part of the tooltip copy "Once it's activated, click here to dismiss this notice.", there was an extra problem with Stripe, that since the actions need to be taken outside of the plugin, we can't know when the payment method gets activated, so it's necessary to add a way to refresh the payment method and dismiss the "pending activation" notice.

I'd leave the link out for now. Ideally, we'd detect when the payment method is activated and hide the badge automatically. The purpose of it is to let merchants know that even if they enable the payment method, it won't appear on checkout unless it's activated in Stripe.

The add new payment method flow (pc4etw-lh) assumes that we'd refresh the list to check which payment method have pending activation. I wonder if we could do the same on refresh when you're in a non-UPE settings page? In payment method settings, we'd refresh the list when the merchants click the button in the ellipsis menu.

**Comment by ricardo** [comment]
Thanks for the responses @jarekmorawski!

> Secondly, the badge would only appear after the merchant went to the Stripe dashboard and requested activation.

Just to clarify, when you first create a new account, some payment methods might still remain in the "pending" status before you provide the necessary information to fully activate the capability. It doesn't necessarily need to be requested first, so the badge would apply in that case too, since there's no way to tell whether the payment was requested or is simply pending because there are some information missing.

> I'd leave the link out for now. Ideally, we'd detect when the payment method is activated and hide the badge automatically.

Unfortunately it doesn't seem trivial to refresh the capabilities based on the actions taken on the Stripe account. We have a separate issue for detecting that automatically https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1879.

We have an additional problem that the current implementation has the capabilities cached, so the "pending" notice doesn't go away unless you explicitly click to refresh the payment methods 😕.

> The purpose of it is to let merchants know that even if they enable the payment method, it won't appear on checkout unless it's activated in Stripe.

Just to clarify, if we have the capabilities up to date with Stripe, it's possible to tell whether the payment method will appear on checkout. So we can show or hide the notice accordingly.

> I wonder if we could do the same on refresh when you're in a non-UPE settings page?

I believe we would need to clear our account/capabilities cache upon refreshing the settings page. I need to investigate the possible consequences of that, but I think this can be done as part of the issue https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1879, by checking if it's possible to automatically refresh the capabilities first.

---

#### Action steps

We have the 5.8.0 release this Wednesday and it'd be nice if we could include this pending activation badge. We could implement the remaining suggestions in a future release.

Based on your feedback, I think we can immediately fix these:

- Change the badge to `Requires activation`.
- Change the first part of the tooltip to `{Payment method title} requires activation in your Stripe dashboard.`

In regards to hiding the badge automatically, I'd suggest one of these options as immediate fixes:

1. Keep the "here" link action to refresh the capabilities embedded in the tooltip for now; or
2. Remove the "here" action for now - the badge won't disappear unless we implement a way to refresh that automatically later. If we go with this option, what should be the second part of the tooltip copy?

@jarekmorawski let us know which option sounds better.
