### ISSUE TITLE
Can't pay with a 3DS card after a card which causes a CVC failure in WooCommerce Blocks Checkout

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gateway-stripe#2102]
After a credit card payment that produced a CVC failure error, it's not possible to retry the payment with a 3DS card.

## To reproduce

1. Go to the Checkout block.
2. Try to pay with the card number `4000000000000101`, it should fail (see [Stripe docs](https://stripe.com/docs/testing)).
3. Then, try to pay with a 3DS card (`4000002500003155`).

Expected:

4. It should open a modal to validate the 3DS card.

Actual:

4. The payment fails again. (If you switch to another payment method and then select Stripe again, then it works).

## Screenshots

https://user-images.githubusercontent.com/3616980/116876710-2c2b5b00-ac1d-11eb-9bbd-5995f2659de8.mp4

**Comment by nerrad** [comment]
Whoever picks this up, it'd be good to investigate if this is something that should be fixed at the Checkout block level or in a payment method extension. I'm thinking the latter, but it's still possible there are some needs the payment method will have from the Block payment method API.

**Comment by opr** [comment]
I am unable to reproduce this - https://www.loom.com/share/be53bf44a49c4cbb9d03115a36d5eff9

@Aljullu please would you try again with checkout i2 and see if this is solved now?

I notice the error notices are doubled up though so I will investigate this.

**Comment by Aljullu** [comment]
That's weird, I can consistently reproduce in Firefox and Chrome:

https://user-images.githubusercontent.com/3616980/138730211-aad9073c-e25b-48b7-ab97-f4e220cd0f3e.mp4

I tested in `trunk` and uploading the Stripe Payment Gateway, with a virtual and a physical product, and in all cases it happened. :confused:

**Comment by opr** [comment]
I've been debugging this, and I can see that _sometimes_ the  Stripe `source` that gets `POST`ed to the Checkout endpoint is the same for both `4000000000000101` and `4000002500003155` - if you follow the testing instructions, but manually input the card numbers rather than copying and pasting, then the card requiring 3DS works perfectly every time.

For some reason, the `sources` endpoint at stripe doesn't get called with the new card details if you copy and paste the second card number in and immediately try to check out. If you wait a moment, or go back and delete the last character of the card and re-enter it, it seems to work.

@nerrad and @Aljullu: this is an error with the front-end implementation of Stripe, so I think we should move it to their repository.

@Aljullu if you can try with the steps I mentioned above and confirm it's working please let me know and I'll move it 😃

**Comment by Aljullu** [comment]
> @Aljullu if you can try with the steps I mentioned above and confirm it's working please let me know and I'll move it 😃 

You're right! It looks like waiting for some time or updating the numbers manually solves the issue.

I didn't research it, but if you think the issue is in Stripe, I would say go for it and transfer the issue.

**Comment by wjrosa** [comment]
Hey @Aljullu ! I cannot reproduce this issue with the new checkout experience using the latest version of the plugin. Tried multiple times with different cards. I will be closing this for now. Let us know if that's not true for you, and we will reopen the issue.
