### ISSUE TITLE
Non-UPE pre-orders with charge upon release have a blank payment method name

### ISSUE THREAD

**Issue by ricardo** [woocommerce/woocommerce-gateway-stripe#2104]
**Describe the bug**
Non-UPE pre-orders with charge upon release have a blank payment method under the edit order page.

**To Reproduce**
1. Make sure [WooCommerce Pre-Orders](https://woocommerce.com/products/woocommerce-pre-orders/) is installed and active.
2. Create a pre-order product with charge upon release:
  a. As a merchant, navigate to Products > Add new.
  b. Set the product title to: "Pre-order product with charge upon release".
  c. Under product data, add a regular price of 10.
  d. Select pre-orders.
  e. Check "Enable pre-orders for this product".
  f. Set an availability time in the future.
  g. Select when to charge: "Upon release".
  h. Click "Publish".
3. As a merchant, make sure "new checkout experience" is disabled under **WooCommerce > Settings > Payments > Stripe**.
4. As a shopper, add the pre-order product to the cart and proceed to checkout.
5. Pay with a new credit card.
6. Make sure the order details page has a description at the top saying that you will be automatically charged for your order.
7. As a merchant, navigate to **WooCommerce > Orders**.
8. Notice the order description says: "Payment via . Customer IP: ...".

The pre-order works as expected, but it doesn't save the payment method name.

**Expected behavior**
1. Pre-orders should save a payment description.

**Screenshots**
<img width="387" alt="Screen Shot 2021-10-26 at 22 37 03" src="https://user-images.githubusercontent.com/5509901/138985218-049d647d-7c2c-40d1-9515-87a4da69112a.png">

**Comment by asumaran** [comment]
@ricardo after my comment https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2086#issuecomment-953407962 I realized this issue is actually related to https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2039 I was able to reproduce this issue after clearing the Stripe's title and description

<img width="660" alt="Screen Shot 2021-10-27 at 7 42 15 PM" src="https://user-images.githubusercontent.com/1025173/139167025-0b2a75f3-a135-4f33-915b-9cc584208fe0.png">

<img width="404" alt="Screen Shot 2021-10-27 at 7 42 37 PM" src="https://user-images.githubusercontent.com/1025173/139167047-b7d78ad7-1728-4288-8bb4-55a53ff425d8.png">

**Comment by ricardo** [comment]
Ah gotcha, that's why then!

So related: #2039

**Comment by ricardo** [comment]
Closing in favor of #2039
