### ISSUE TITLE
Update renew subscription manually test instruction

### ISSUE THREAD

**Issue by cesarcosta99** [woocommerce/woocommerce-gateway-stripe#2113]
**Describe the bug**
In the [Renew subscription manually test](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#renew-subscription-manually), we are supposed to see two buttons in the subscription view (7th step below), however I saw three (`Cancel`, `Change payment` and `Renew now`).

**To Reproduce**
1. As a Merchant create a subscription product (see official documentation for more details).
2. As a Merchant navigate to 'WooCommerce -> Settings -> Subscriptions'
3. Enable 'Accept Manual Renewals', ' Turn off Automatic Payments ' and click 'Save changes' button on page bottom.
4. As a Shopper add the subscription product to the cart and complete checkout.
5. As a Shopper, navigate to 'My account -> Subscriptions' and open the newly created subscription entry.
6. Ensure 'Payment' states 'Via Manual Renewal'.
7. Observe 2 buttons for 'Actions'.
8. [...](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows#renew-subscription-manually)

**Expected behavior**
I believe that we just need to update the test instruction, but we must confirm that the three buttons are the expected output within the subscriptions context.

**Screenshots**
![image](https://user-images.githubusercontent.com/10233985/140239657-415b201c-d0dc-4429-9d22-7801a6d1865d.png)

**Comment by thenbrent** [comment]
> we must confirm that the three buttons are the expected output within the subscriptions context.

The number of buttons can change quite a bit depending on various settings within WC Subscriptions (and also states) and the subscription product purchased.

For example, in the case of a physical product being purcahsed, a **_Change address_** button will be displayed, like this:

<img width="983" alt="Screenshot 2023-06-20 at 14 39 49" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/235523/38c9dbe9-5005-4674-a454-d715834744a4">

The testing instructions do not specify that a virtual product should be used for testing.

I suspect the **_Change payment_** button displayed in the original screenshot was likely included because _Turn off Automatic Payments_ was unchecked (I just tested, and it was correctly only shown after unchecking that).

When a store offers a payment method that can process automatic payments (like Stripe), WC Subscriptions will add a _Change payment_ button to the subscription to allow the shopper to switch from manual to automatic payments. 

Because of the above and in particular, the fact that many codebases and data outside the Stripe extension influences the number of buttons displayed on the subscription, I've updated the testing instructions to remove number of buttons from the manual test and others. Instead, they now only require that the _Renew now_ button or other required button is displayed.
