### ISSUE TITLE
4.0.2 changelog repeated twice in changelog.txt

### ISSUE THREAD

**Issue by colmtroy** [woocommerce/woocommerce-gateway-stripe#2167]
Very very minor bug :)
See https://github.com/woocommerce/woocommerce-gateway-stripe/blob/1fcf10d063cd97813644f195e463cf3e76a4f50e/changelog.txt#L451

4.0.2 changes are listed twice.

**Comment by dougaitken** [comment]
_To ensure the WooCommerce team are having the most impactful work, we review older open Issues on this GitHub repository to find out what is still relevant._ 

I appreciate some time has passed since the original comment, thanks for your patience.

The duplication is still in the changelog but this hasn't caused any problems. I appreciate the keen eye!
