### ISSUE TITLE
Add `is_live` and `test_mode` to account summary API

### ISSUE THREAD

**Issue by brianyu28** [woocommerce/woocommerce-gateway-stripe#2262]
**Is your feature request related to a problem? Please describe.**
For in-person payments, the account summary endpoint needs the parameters `is_live` (whether the underlying Stripe account is an actual account connected to a bank) and `test_mode` (payment gateway extension should use test keys instead of live keys).

**Additional context**
See #2200.

**Comment by brianyu28** [comment]
@allendav `test_mode` seems very straightforward to add, but I had a clarifying question about the below comment:

> `is_live` indicates that the underlying Stripe account is not just a developer account but an actual account connected to a bank, etc.

Do you know if there is a property that exists somewhere in the Stripe account's metadata that would tell us this, or if it's something we have to infer from other information (for example, [`details_submitted`](https://stripe.com/docs/api/accounts/object#account_object-details_submitted) might indicate whether bank account details have been submitted to Stripe)?

The reason why I originally thought this was the opposite of `test_mode` was because the only existing place in the Stripe extension I can see mention of an `is_live` property is here, where it's true if test mode `=== 'no'`:

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/4f47751f5dd3d26eb245878a936f96510a11d2e4/includes/class-wc-stripe-order-handler.php#L367-L369

That seems inconsistent with the idea that `is_live` and `test_mode` can both be true, so I just wanted to make sure I understood where the `is_live` information should be coming from.

**Comment by allendav** [comment]
> Do you know if there is a property that exists somewhere in the Stripe account's metadata that would tell us this, or if it's something we have to infer from other information

So, to give context, although web payments (i.e. through WooCommerce checkout) work for is_live true (activated accounts) for both test_mode true and test_mode false, attempting to get a token to connect a card reader using test secrets will not work for is_live true accounts - e.g. see https://github.com/woocommerce/woocommerce-ios/pull/5358

So, in our mobile apps, we want to avoid attempting to connect card readers for live stores in test mode. 

With that context, we (WooCommerce Payments server) knows how the account was created because it was involved in its creation, but as you point out, we don't know how accounts used by the Stripe extension were created.

I looked through https://stripe.com/docs/api/accounts/retrieve briefly and I didn't see anything that would definitively indicate activation status.

May I recommend pinging Stripe engineering in our slack channel with them? They are likely to have a recommendation.

**Comment by brianyu28** [comment]
Merged in #2272

**Comment by allendav** [comment]
Thank you! fyi @ctarda

**Comment by ctarda** [comment]
Thanks @brianyu28 ! Pinging also @AnirudhBhat and @malinajirka
