### ISSUE TITLE
Shipping not updated when quantity updated (Google Pay Only)

### ISSUE THREAD

**Issue by calebmcelroy** [woocommerce/woocommerce-gateway-stripe#2277]
**Describe the bug**
If you open the Google Pay payment dialog, then close it and change the quantity, reopening the payment dialog will result in the shipping being incorrect. This only happens with Google Pay not Apple Pay.

**To Reproduce**
1. Setup shipping cost that is different based on quantity.
2. Go to product page.
2. Set desired quantity.
3. Click Google Pay button.
4. Use back arrow to exit modal.
5. Change quantity. 
6. Click Google Pay button again. 
7. You should see that the shipping information is incorrect.

**Expected behavior**
To have the correct shipping information.

**Environment:**
 - WordPress Version: 5.8.3
 - WooCommerce Version: Version 6.0.0
 - Stripe Plugin Version: 6.0.0
 - Browser: Version 96.0.4664.110 (Official Build) (x86_64)
 - Any other plugins installed: WooCommerce Table Rate Shipping (Version 3.6.4)

**Additional context**
The problem is that in Google Chrome the _“shippingaddresschange”_ event is not called again once re-opening the payment dialog the second time after the quantity is change. That is what Safari does so the current code works just fine. The solution is to save the shipping address then after updating cart on the button click, call _“wc_stripe_payment_request.updateShippingOptions“_ with the saved address before showing payment modal. That is what I did to fix it.

I can submit a pull request if you’d like.

Thank you!

**Comment by asumaran** [comment]
@calebmcelroy, Thanks for opening an issue reporting this. It seems you have already figured out what's happening. In order to update the payment sheet, we need to wait for the response [here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/assets/js/stripe-payment-request.js#L621) (which return the exact amounts from the backend).

The problem is that we can't make asynchronous calls after clicking the Google Pay/Apple Pay button. I mean, we could **but** to update the payment sheet, we need to wait for the server response. We have tested this approach and it works well in Chrome, but it fails on Safari. It is a known issue, and it's been long discussed as part of #1563. Alternative approaches have been considered internally but unfortunately, we have no ETA at the moment.

**Comment by calebmcelroy** [comment]
After submitting this issue, I did run into that Safari doesn't like the asynchronous calls after the click event. I plan on just doing a browser check and implementing async call only for Chrome until you complete an official fix. Thanks for your help and reply!
