### ISSUE TITLE
Statement descriptor value is not present in accounts REST API response - blocks mobile intent creation

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-gateway-stripe#2297]
**Describe the bug**
Even when set in the plug-in settings:

<img width="1505" alt="descriptor" src="https://user-images.githubusercontent.com/1595739/151070174-5feadbfc-f40e-4f1c-b793-348ed7f93456.png">

the statement descriptor in the accounts REST API response is empty:

![IMG_0301](https://user-images.githubusercontent.com/1595739/151070134-66666f36-0749-4429-aa07-168162485ca5.PNG)

**This is a must fix for the mobile apps. We can't create payment intents without a descriptor.**

Observed with plugin version 6.0.0

cc @ctarda @malinajirka - this is a must fix - we cannot create payment intents without a descriptor - payment intent creation fails

**Comment by brianyu28** [comment]
Hi @allendav! Thanks for opening this.

The descriptor returned by the REST API should be pulling from the Stripe account's "Statement descriptor" in Stripe settings. If you visit https://dashboard.stripe.com/settings/account (when signed in to the account linked to your test site), is there a value for the "Statement descriptor"?

I am noticing that when I update the statement descriptor in the extension settings, that value doesn't seem to be synced to Stripe settings — that may be part of what's contributing to this issue here.

**Comment by allendav** [comment]
Hey @brianyu28 - definitely blank at Stripe's end:

<img width="939" alt="Screen Shot 2022-01-25 at 3 43 29 PM" src="https://user-images.githubusercontent.com/1595739/151078343-8ff9b31d-79bb-4b0a-90d6-654ec0ad8be6.png">

To minimize the amount of hunting around for settings that merchants need to do, it would be ideal if the merchant could set it in the plugin and have it 1) sync to stripe and 2) provided in response to REST API requests

Thanks!

**Comment by brianyu28** [comment]
I agree. Once (1) happens, (2) will happen as a result, since the REST API is pulling from Stripe's data (which is why you're getting a blank response right now). I'm not sure why changing the statement descriptor in WC isn't changing the statement descriptor in Stripe settings, but I'll look into that.

**Comment by brianyu28** [comment]
As a temporary workaround, setting the statement descriptor in Stripe settings should let you get the statement descriptor via the REST API and therefore create payment intents.

**Comment by brianyu28** [comment]
After looking through the [documentation](https://woocommerce.com/document/stripe/), I think it's actually intended behavior that these two aren't in sync: the Stripe account statement descriptor is used as a fallback if there's no statement descriptor provided in the extension settings.

I'll update the REST API to follow the same logic: default to providing the WC settings statement descriptor and fall back to the Stripe account statement descriptor.

**Comment by allendav** [comment]
> default to providing the WC settings statement descriptor and fall back to the Stripe account statement descriptor

I'd suggest a default default too, if both settings and Stripe have empty strings. Perhaps the default default could be a sanitized length-limited string based on the site title or something. That way we set up our merchants for success by default :)
