### ISSUE TITLE
Payment request buttons on product page do not support custom field/pricing extensions such as WooCommerce Product Add-ons

### ISSUE THREAD

**Issue by PoeHaH** [woocommerce/woocommerce-gateway-stripe#2322]
**Describe the bug**

The payment request buttons on the single product page (Google Pay/Apple pay) don't integrate with other official WooCommerce extensions such as WooCommerce Product Add-ons.

**To reproduce**

1. Make sure the Stripe gateway plugin is configured and your site runs HTTPS so the apple pay/google pay button appears on product pages.

2. Install the official 'product addons' plugin: https://woocommerce.com/products/product-add-ons/ 

3. Go to Products > Add-ons and click "Create New" to create a new product addon.

4. In the "add-on fields" section, create a new "Short Text" field. Make sure it is applied to all products and has "adjust price" enabled with a flat fee of 2. Screenshot of all the settings for this field: https://i.snipboard.io/dw0WEm.jpg 

5. Visit any product, and add some text in the addon field so the $2 extra price is added. Screenshot of the product page: https://i.snipboard.io/Uc3otH.jpg . Notice how the product price is correctly set to $92 ($90 base price + addon price of $2).

6. Press the "Buy with Google Pay" button on that same page. The Google payment modal appears and you can see the issue: the price is the main product price ($90) instead of the total product price, including the addon price ($92): https://i.snipboard.io/auoQO8.jpg

**Expected behavior**
The total price should be $92 instead of $90. The addon price is not included.

**Additional context**

A few additional things I'd like to add:

1) this is currently the top voted issue on the ideas board: https://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/34518661-apple-pay-payment-request-to-support-custom-field

2) The filter "wc_stripe_hide_payment_request_on_product_page" was recently deprecated, which only makes it harder for external developers to at least make sure the buttons don't show if compatibility is not possible.

3) Integration seems possible because another official WooCommerce plugin "WooCommerce PayPal Checkout Gateway" works correctly for the same scenario. It looks like the only thing that needs to happen is either follow Woo standards or include relevant filters for others to hook into.

4) I've used the Product Add-ons plugin as an example but there are plenty of other plugins that don't work because of this, both official and non-official.

**Comment by rafaelzaleski** [comment]
> The filter "wc_stripe_hide_payment_request_on_product_page" was recently deprecated, which only makes it harder for external developers to at least make sure the buttons don't show if compatibility is not possible.

The deprecation was reverted on version 6.3.0.

**Comment by PoeHaH** [comment]
> > The filter "wc_stripe_hide_payment_request_on_product_page" was recently deprecated, which only makes it harder for external developers to at least make sure the buttons don't show if compatibility is not possible.
> 
> The deprecation was reverted on version 6.3.0.

Thanks for pointing that out! It's a start but doesn't really fix the original issue.

**Comment by PoeHaH** [comment]
Any news on this @rafaelzaleski ? Is it being looked at or will it not be fixed at this time? Thanks!

**Comment by rafaelzaleski** [comment]
> Any news on this @rafaelzaleski ? Is it being looked at or will it not be fixed at this time? Thanks!

@PoeHaH 
It's on our product backlog, and we intend to fix it as soon as we get availability for that. 
If you know how to fix this issue and want to contribute, you're welcome to submit a pull request with this fix, and we'll review it.

**Comment by shaunkuschel** [comment]
The ticket fields added by the Box Office plugin are not included in Express Checkout purchases from the product page as well, causing compatibility issues with the default behavior of that extension.

Reported on 4950082-zen

**Comment by EvanDotPro** [comment]
I've created a PR which fixes this for the official Product Add-Ons extension **only**. This will not resolve it for any other extensions unfortunately. Further investigation is still required to come up with a more generic solution that will work for all extensions with similar behavior.

**Comment by PoeHaH** [comment]
> 

Can you link the PR?

**Comment by EvanDotPro** [comment]
@PoeHaH The PR is here: #2422

A more generic solution would likely require wiping out the customer's shopping cart, adding the item with all the add-ons/options/whatever to the now empty cart, then simply triggering the payment request button the same way as on the cart / checkout pages.

Wiping out customers' carts like that may be unexpected / undesired behavior, so further discussion may be needed.

One of the developers on our team has proposed the concept of "temporary" carts, which would solve this. However, this would need to be added in WooCommerce core, not the Stripe extension.

**Comment by PoeHaH** [comment]
Perhaps we are talking about different things but wouldn't this flow solve it for *all* plugins:

1) Buy now button is clicked
2) An ajax 'add to cart' request is made, much to how Woo already allows it. If you do this the WooCommerce way, any external plugin can hook in and send any data along they need.
3) Product info, including final amount, is sent back to the frontend for the payment button.

**Comment by EvanDotPro** [comment]
@PoeHaH We're actually talking about the same thing. :)

The issue with that flow is when the customer already has other products in their cart. [Best practices](https://developers.google.com/pay/api/web/guides/ux-best-practices#product-page) and customer expectations indicate that the payment button on the product pages should trigger the purchase of that single product _only_, not that product + everything else in their cart.

This is why in my previous message I said we'd have to clear the customer's cart first, then add the product as configured for this to work as expected. However, imagine a scenario where a customer has 10 things in their cart, they go to add an 11th, but accidentally click the Google Pay button instead of add to cart. Now when they back out of Google Pay, they're only going to have the 11th item in their cart and the other 10 they added will be gone.

Hope this helps clarify for you. Feel free to ping me if you have any other questions.

**Comment by PoeHaH** [comment]
Ah, I understand now. Perhaps this is an option:

It's been a while since I dug into your plugin's code but I think now the product price is included in the HTML on page load and then grabbed with javascript and passed to render the Google Pay window. Can you add a jQuery event so other plugin can manipulate the data that is passed to the Google Pay window? Similar to how WooCommerce fires jQuery events at certain points.

**Comment by EvanDotPro** [comment]
@PoeHaH Thanks for the response and brainstorming suggestions.

That's a potential option. As you probably understand though, this would require all plugins to individually add Stripe extension specific support for product page payment buttons to work — far less than ideal. I see something like that as more of a stop-gap hack until a more robust/proper solution can be implemented, however I'm hesitant because once we add something like that, we'll on the hook to support and maintain it until we can gracefully deprecate and remove it without breaking all the extensions that inevitable come to depend on it.

The temporary cart solution I mentioned before would probably be the most elegant solution and ensure that all extensions with this type of functionality "just work", however that proposal stalled internally a while ago. Perhaps I can see about raising that proposal again and see if I can get some momentum behind it.

**Comment by PoeHaH** [comment]
A few more points for my PoV:

1) Probably, the temp cart will not be implemented in the next years as it requires WooCommerce to build (and sign off on)  this.

2) You are right. It does require other plugins to add support but at least then there is an option to move things forward. Now, they can't do anything and have to disappoint their users (again, I refer to it being the top voted issue on the Ideas Board since years already). 

3) I definitely understand that you don't want to add additional code when not needed. But on the other hand, firing a jQuery event is one line of code and doesn't really require much support from the team I think.


Another way to do things:

1) Add the product to the normal cart via ajax, send back the cart item ID.
2) On succesful payment, fire another ajax call to remove the item from cart.
3) On canceled payment, do the same.

Downsides : requires more work from your team and is probably overkil for most use cases of your plugin.
Upsides: all other plugins that do anything with cart data will keep on working because the plugin follows Woo standards.

Anyway, thanks for listening. I hope you take some of my ideas under consideration so we can finally move this issue forward. You have no idea how many users are asking me about this on a monthly basis. They don't understand why plugins don't integrate and it frustrates them to a point they move on. I understand their disappointment.
