### ISSUE TITLE
Strip Integration of Alipay payment option is not showing

### ISSUE THREAD

**Issue by bcalmeil** [woocommerce/woocommerce-gateway-stripe#2383]
Hi all

The integration of Alipay with Stripe is not appearing in the payment method.

![alipay option is missing](https://user-images.githubusercontent.com/29054379/175851306-48d2aec8-0225-46d5-8a55-446cd1990fa9.jpg)

**Comment by tarunvijwani** [comment]
Hi there @bcalmeil  👋

Thanks for taking the time to make us aware that Stripe Alipay isn’t working with the Checkout and Cart blocks. These blocks are still in early access (via the feature plugin) and it’s expected that some existing Woo Extensions that integrate with the current checkout flow in WooCommerce core will not work with the blocks.

I have a few follow-up questions:

1. Did you [enable Stripe Alipay](https://support.stripe.com/questions/activating-alipay-on-your-stripe-account) in your Stripe account?
2. What steps did you follow to enable Stripe Alipay on your site?
3. Can you also please send a copy of your WooCommerce system status report?

You can get it from your dashboard by going to WooCommerce—> Status. 

We definitely want to help until things are working properly for you! Let us know.

**Comment by bcalmeil** [comment]
Hi 

Thanks for your feedback

1./ I have enabled Stripe in both WooCommerce and stripe platform
2./ I have followed the WooCommerce steps, and it used to appear before I activated the block cart/
3./ This is the WooCommerce status report

**Comment by bcalmeil** [comment]
Hi 

Thanks for your feedback

1./ I have enabled Stripe in both WooCommerce and stripe platform
2./ I have followed the WooCommerce steps, and it used to appear before I activated the block cart/
3./ This is the WooCommerce status report

**Comment by dougaitken** [comment]
Hey @bcalmeil 

Alipay, along with other Local Payment Methods don't have support for the new Cart & Checkout Blocks yet, only the [Stripe credit card](https://woocommerce.com/document/cart-checkout-blocks-support-status/#section-4) option is available - this is why Alipay doesn't show.

(I've removed your System Status Report from your comment as it isn't currently needed)

**Comment by masteradhoc** [comment]
@dougaitken how is the progress to get this available? My client will not be able to use the following activated:
- Stripe giropay
- Stripe Sofort
- Stripe Alipay

Giropay and Sofort i was able to see with this setting activated
![image](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/6242098/e13cbf28-1843-4601-9d2b-b0d19f69c4e2)

**Comment by Mayisha** [comment]
This is the expected behavior for the checkout block when `Enable the updated checkout experience` checkbox is disabled. The other payment methods are available on the block checkout if the `New checkout experience` is enabled. 

- By enabling the `New checkout experience` you can have giropay, iDeal, EPS, Bancontact, etc. on the checkout page. 
- For having Alipay on the checkout page, the store currency should be the one supported by the corresponding Stripe account. Here is [the list of supported currencies](https://docs.stripe.com/payments/alipay#supported-currencies) by country (country of your Stripe account). For example, if you have an Australian Stripe account, the store currency or checkout currency have to be `AUD` and only then Alipay will be available.
- Sofort is being deprecated by Stripe as a standalone payment method. ([source](https://support.stripe.com/questions/sofort-is-being-deprecated-as-a-standalone-payment-method)).

**Comment by Mayisha** [comment]
Closing this issue as it is the expected behavior for the legacy checkout experience. Please check my [previous comment](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2383#issuecomment-1999088651) for a detailed explanation.
