### ISSUE TITLE
Support for PIX payments in Brazil

### ISSUE THREAD

**Issue by jffaria** [woocommerce/woocommerce-gateway-stripe#2433]
Stripe recently introduced PIX payments in Brazil. It would be great to offer support for that as it is a huge chunk of payments market in Brazil.

**Comment by ricardo** [comment]
Another request in https://wordpress.org/support/topic/pix-installments/

**Comment by maylonsales** [comment]
Hello guys. 

I really need PIX because PIX are the first payment method here in Brazil..... 

and ! WE need installments payment in Stripe too. because everyone buys with installments !!!!

**Comment by renatofrota** [comment]
I am not sure what are the rules of this repository in regards to "+1" comments, the readme seems to be the same as the plugin's one, so...

+1

**Comment by thenbrent** [comment]
I'm closing this so the [feature request board](https://woocommerce.com/feature-requests/stripe/#) can be the canonical source of tracking popularity and help determine priority in our roadmap for features, instead of a GitHub issue (which will be focused on bug backlog).

I've created a new request to track popularity for Pix here: https://woocommerce.com/feature-request/support-for-pix-payments-in-brazil/#

I have reached out to the team responsible for the WooCommerce.com feature request board to find out how to add votes to an existing request. Once I can do that, I will add 4 votes to that request to ensure your contributions and the history of demand here is properly accounted for in that system.

If you're coming to this issue after it's closed, please vote on the above idea.

To help understand our plans for this feature, we will be focusing our near term efforts on improving the Payment Elements integration currently in the Stripe extension (under the "[new checkout experience](https://woocommerce.com/document/stripe/#new-checkout-experience)") before adding additional APMs to it or the legacy elements integration. Once the UPE integration is the default, we will begin offering additional APMs, with priority helped determine by votes on the feature request (A8C reference for the roadmap here: pc4etw-Jq-p2)

More details on closing this action for A12s here: pc4etw-IK-p2
