### ISSUE TITLE
Merchants with Stripe accounts in India are given an error when users check out on their site from another country.

### ISSUE THREAD

**Issue by thisissandip** [woocommerce/woocommerce-gateway-stripe#2482]
**Describe the bug**

Merchants with Stripe accounts in India are given an error when users check out on their site from another country.

"As per Indian regulations, goods export transactions require billing and a shipping address. More info here: https://stripe.com/docs/india-exports"

More details here: https://support.stripe.com/questions/failed-international-payments-from-stripe-accounts-in-india

The issue is when creating the customer: - if you're selling goods: pass both the billing address and the shipping address outside of India when creating a customer but it looks like the plugin doesn't pass the billing address to Stripe.

**To Reproduce**
1. Create a Stripe account based in Indian
2. Connect your site to WooCommerce
3. Place an order from outside India 

**Expected behavior**

Merchants from India, exporting globally should not get the above error.

**Screenshots**

![dPDeUP.png](https://user-images.githubusercontent.com/69596988/203243073-2f805e4b-04e2-4446-9bbe-925eb1e3cb5d.png)

**Additional context**

Internal discussion: p1668610016855489-slack-C7U3Y3VMY

**Comment by pssyss** [comment]
There is a serious issue with Stripe for India customers. I sent a Stripe invoice to the customer and yet it fails to recognize it correctly. 
![image](https://user-images.githubusercontent.com/52868702/216808297-03cf3067-c01c-4dad-991b-6ef9957c7231.png)

Secondly, when Woocommerce is creating the customer in Stripe, the customer currency is getting set in INR even the though the customer tried the payment in USD or another currency. 

It's frankly very distressing to see this happen and have no clear resolution from many months. We pay a lot of money to stripe for their service and its disheartening to see the poor resolution and support service provided.

**Comment by coolsatinder** [comment]
Any update on this? we are also facing same issue - https://prnt.sc/ilsPPztt4lMU

**Comment by pssyss** [comment]
> 

The problem was solved by changing the plugin. We now use [WEBTOFFee's plugin](https://wordpress.org/plugins/payment-gateway-stripe-and-woocommerce-integration/) and use STRIPE checkout. (so the customer is redirected to stripe to make the payment). horrible user experience and probably costing us sales, duh

Also when raising invoices in Stripe, make sure you have the billing and shipping address both in the invoices. 

Another amazing thing just happened. Bank of America did a chargeback 5 days after payment because the customer's shipping address was different from the billing address. This happened without the bank calling the customer, the order was already shipped and both myself nor the customer was informed about the chargeback. BIG FAIL on both stripe and BOA. Luckily I was able to stop the delivery but had to bear heavy losses on shipping and OFCOURSE stripe did not refund the transaction fees.

**Comment by stoltzrx** [comment]
6226179 - zen

**Comment by igorhereira** [comment]
6235615-zen

**Comment by ericfri** [comment]
6233490-zen

**Comment by Brianmitchtay** [comment]
6290987-zen

**Comment by Babylon1999** [comment]
zd-6500521

**Comment by ghost** [comment]
I am facing the same issue. Need support asap. please...

**Comment by zoemyers** [comment]
6800618-zd-a8c

**Comment by james-allan** [comment]
This should be fixed with https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2731. I'm going to close this issue given the PR has been merged. That fix is scheduled for release later this week.
