### ISSUE TITLE
Stripe secrets should be write only

### ISSUE THREAD

**Issue by prettyboymp** [woocommerce/woocommerce-gateway-stripe#2508]
We should be doing more to keep the Secret Key and Webhook Secret for the "Stripe Account Keys and Webhooks" settings from being accessible, even by other site administrators.  These keys are pretty important, especially the Secret Key as it can give a user access to the make changes on the backing Stripe account where they may not have access otherwise.

Because of this, we should avoid rendering these secrets back to the browser and only allow them to be written to from the settings screen.

![Screenshot 2022-12-23 at 10 50 48 AM](https://user-images.githubusercontent.com/103718/209363108-6270ab63-ef53-4376-a27c-d3e01c96732e.png)

**Comment by james-allan** [comment]
> we should avoid rendering these secrets back to the browser and only allow them to be written to from the settings screen.

@prettyboymp I just wanted to confirm what you had in mind on this. Do you mean that the browser wouldn't receive the secret key at all? For example the field would be filled with *** if it has been previously saved, you can change and write to it, but can't read it at all. ie a `password` input type doesn't go far enough.

**Comment by james-allan** [comment]
Just noting there was a similar issue filed here https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2643. They had similar ideas about how to hide the keys and only make them editable.

**Comment by prettyboymp** [comment]
> @prettyboymp I just wanted to confirm what you had in mind on this. Do you mean that the browser wouldn't receive the secret key at all? For example the field would be filled with *** if it has been previously saved, you can change and write to it, but can't read it at all. ie a `password` input type doesn't go far enough.

That's correct.  The two secrets should be write only fields and we should avoid sending it to the browser to protect it from being leaked.  Putting in asterisks as placeholders or some other value to indicate that the field has already been filled in and as #2643 suggests, we could only save the value if the submitted value matches specific patterns.

**Comment by Mayisha** [comment]
> The two secrets should be write only fields and we should avoid sending them to the browser to protect it from being leaked.

@prettyboymp I have found two issues with this expected behavior when updating my PR https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2704 to match the expectation.

1. If the fields are write-only then there is no way for the user to update a key if needed. Masking the saved keys is necessary but the option to provide a new value should also be there.
2. If we do not send the keys to the frontend, the `Test connection` feature does not work.

**Comment by james-allan** [comment]
> If the fields are write-only then there is no way for the user to update a key if needed. Masking the saved keys is necessary but the option to provide a new value should also be there.

They should be able to update the key if they want by entering a new value and saving it. 

So for example: 

1. On load, a masked value of the current key (eg `pk_test_aK**************************************************oc`) is presented in the field. 
3. To update/change the current key, the user can enter a new value and save. 
4. The function which saves this form will need to be able to identify if the field has been changed. eg
   - If the field is empty delete the keys. 
   - If the saved value == the mask value of the current key then nothing has changed. Leave the current keys saved. 
   - If the saved value != the mask value, and it's a valid key (eg starts with `pk_...`) then save the entered value
      - it may not be necessary but we could utilise a hash to do some of these comparisons. eg if a hash of the value submitted by the form != a hash of the current key etc. 

> If we do not send the keys to the frontend, the Test connection feature does not work.

This one is a little more tricky. If the user has just entered new keys, this test connection still works because it takes the values in the form to test the connection. If these form fields values are masked however (ie they are preexisting keys) it won't work because the values are not legitimate keys. 

To get around the second scenario, we will have to we'll have to use a different approach. eg 

1. On page load the "Test connection" section is replaced with a success or fail depending on the current state of the saved keys. We can use whether the `WC_Stripe_Account::get_cached_account_data()` returns a valid result. 
2. If they change the keys, this "Test connection" section would change to the current Test connection by allowing the user to test the values currently in the fields. 

Does that make sense? This issue has broadened in scope quite a bit from its original idea so I guess feel free split it up if you want.
