### ISSUE TITLE
Cross-site redirect from "https://pay.google.com/about/" to "https://pay.google/about/" not allowed for payment manifests.

### ISSUE THREAD

**Issue by bm-aws** [woocommerce/woocommerce-gateway-stripe#2594]
**Describe the bug**
Google Pay not longer working since the last update.

Reason....
CORS Error: Cross-site redirect from "https://pay.google.com/about/" to "https://pay.google/about/" not allowed for payment manifests.

**To Reproduce**
1. Go to your product page with Google Pay button.
2. Check Browser Console
3. See error

**Environment (please complete the following information):**
 - WordPress Version: 6.2
 - WooCommerce Version: 7.5.1
 - Stripe Plugin Version: 7.3.0

**Past similar errors:**
https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1063

**Comment by rafaelzaleski** [comment]
@bm-aws, is this issue blocking you from paying with Google Pay? 
Google Pay is working for me in test mode.

**Comment by grzegorztomasiak** [comment]
I just started to integrate Stripe and having the same error, just stumbled across this topic but I don't know yet if it's blocking me from paying because I see Link instead, will monitor.

**Comment by dougaitken** [comment]
@bm-aws To build on Rafael's request, what happens when a payment is attempted? Do you have logging enabled? If so, is there anything additional logged there?

Under “Advanced settings”, tick Log error messages if you wish to save logs that can help you/us troubleshoot your site. This can be disabled and enabled as needed. Logs will appear under WooCommerce > Status > Logs. Use the dropdown menu to select, and view.

I can see the error message on macOS, latest Chrome when loading the product page, no payment request attempted.

**Comment by bm-aws** [comment]
Hi and sorry for the late response.

Could visit our client today and verify the issue. While on his Live System no Button appears, on mobile phones everything seems to work normal. Therefore, we dont see any errors in the Serverlogs or WP Logs. The only visible Error is in fact the posted CORS one.

On his Staging System in Browsers at least "Link" is working.

Looks more like an isolated issue on his site and not a general problem. Still would be nice to get the CORS errors fixed, but i think this ticket can be closed.

**Comment by Mayisha** [comment]
This was a Google Pay bug in Chrome and was flagged in the Chromium platform as well ([issue](https://issues.chromium.org/issues/40269402)). The problem is [fixed](https://issues.chromium.org/issues/40269402#comment11) on the Google Pay side.

Closing this one as the problem no longer happens.
