### ISSUE TITLE
WordPress version compatibility bump

### ISSUE THREAD

**Issue by ryanr14** [woocommerce/woocommerce-gateway-stripe#2656]
**Describe the bug**
Our last released, 7.4.1, of Stripe came out on May 30th and by that time WordPress was on version 6.2.2. That leads to questions from merchants who see the below notice.

**Expected behavior**
We'd expect to stay as current as possible in our plugin header with the latest version of WordPress.

**Screenshots**
<img width="513" alt="Screenshot 2023-07-09 at 10 41 25 PM" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/867748/311d3f7d-aa87-4b33-a371-40f098d285c3">

Thanks!

**Comment by james-allan** [comment]
The minimum tested WP version was updated to the latest WP (6.3) in this commit (https://github.com/woocommerce/woocommerce-gateway-stripe/commit/14fc3bf04addd8f32ffeba42980b4a62767c82e6) and released in our 7.5 release back on August 11th.

Ensuring the tested WP version is updated does form part of our release processes so that should prevent it from falling behind. After each WP release there is that chance it will be behind temporarily. I'll start an internal discussion about whether there's a process we can adopt to prevent that.
