### ISSUE TITLE
New Feature : PromptPay (Thailand) payment method

### ISSUE THREAD

**Issue by PhakphumV** [woocommerce/woocommerce-gateway-stripe#2657]
**Describe the solution you'd like**
I found that Stripe supports PromptPay payment which is mainly used in Thailand and I couldn’t find the payment method in version 7.4.1. 

What is PromptPay?
PromptPay is a Thailand based payment method that allows customers to make a payment using their preferred app from participating banks. Customers see a QR code when checking out with PromptPay. They complete the payment by scanning it using a Thailand bank app.
You can find out more from these links 

- https://stripe.com/docs/payments/promptpay
- https://stripe.com/docs/payments/promptpay/accept-a-payment

I'm working on this feature in my forked repo below and may need some assistance in development and testing
https://github.com/PhakphumV/woocommerce-gateway-stripe

**Comment by dougaitken** [comment]
_To ensure the WooCommerce team are having the most impactful work, we review older open Issues on this GitHub repository to find out what is still relevant._ 

For Feature Requests, we are using the [Stripe Feature Request Portal](https://woo.com/feature-requests/stripe/) for product enhancements rather than the GitHub repository.

**Please head to this Feature Request and add your vote! - [PromptPay integration for Woocommerce with Stripe](https://woo.com/feature-request/promptpay-integration-for-woocommerce-with-stripe/)**

While you're there, use the keyword search to review other feature requests others have submitted already - you can then add your vote.
