### ISSUE TITLE
[Deferred intent] Card - Handle capture-later transactions

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-gateway-stripe#2764]
### Acceptance criteria

- The following critical flow [Merchant -> Manual capture](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#manual-capture) must work as described
- It must work with both regular and 3DS cards
- Errors must be handled gracefully:
  - A relevant, user-friendly message must be shown to shoppers
  - A relevant note must be added to the order
  - A detailed message of the error must be logged to the log files if enabled
  - The order status must reflect the payment status

**Comment by james-allan** [comment]
I've tested the following scenarios and they all passed on the latest `add/deferred-intent` branch.

- [x] **Block Checkout**
   - [x] **_Standard Card_**
      - [x] Capture from Stripe Dashboard
      - [x] Capture from WooCommerce order
   - [x]  **_SCA/3DS Card_** <sup>* 📝</sup>
      - [x] Capture from Stripe Dashboard
      - [x] Capture from WooCommerce order
- [x] **Classic Checkout** 
   - [x] **_Standard Card_**
      - [x] Capture from Stripe Dashboard
      - [x] Capture from WooCommerce order
   - [x]  **_SCA/3DS Card_** <sup>* 📝</sup>
      - [x] Capture from Stripe Dashboard
      - [x] Capture from WooCommerce order

In all cases, the order was originally placed on-hold with an order note with detailed instructions: 

<p align="center">
<img width="200" alt="Screenshot 2023-12-06 at 12 19 13 pm" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/b895a0bb-d97a-44a6-a511-5312e91ed9ed">
</br>
<sup>Authorized payment order notes</sup>
</p>

After the order is captured, it has transaction complete notes too. 

<p align="center">
<img width="200" alt="Screenshot 2023-12-06 at 12 20 11 pm" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/0fc82ee5-880a-4fd0-b95d-e624e8ff0d27">

</br>
<sup>Authorized payment order notes</sup>
</p>

Support for auth/capture was added in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2753 (commit: https://github.com/woocommerce/woocommerce-gateway-stripe/commit/b67203690249e96cb7b41cac1413d0e71524c1ac) when `prepare_payment_information_from_request()` was introduced with the `capture_mode` param set when setting up and confirming the intent. 

The actual capturing of the payment either via the Stripe or WooCommerce dashboards didn't require any changes - the existing functionality just worked. 😀 

\* 📝
When paying with a SCA/3DS card, the order notes appear to be missing the charge ID (see screenshot below). This appears to be the only issue I came across while testing auth/capture. 

<img width="150" alt="Screenshot 2023-12-06 at 12 14 13 pm" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/e6eb0da1-4483-4f55-9c32-765ea77d6b5d">

**Comment by james-allan** [comment]
> When paying with a SCA/3DS card, the order notes appear to be missing the charge ID (see screenshot below). This appears to be the only issue I came across while testing auth/capture.

```
PHP Warning:  Attempt to read property "id" on bool in /wp-content/plugins/woocommerce-gateway-stripe/includes/abstracts/abstract-wc-stripe-payment-gateway.php on line 528
```

There's also this error message that accompanies the issue with SCA/3DS payments.

**Comment by csmcneill** [comment]
It might not fall in the scope of this issue, as I'm not sure if this only affects deferred intent. During some testing I'm doing for our Stripe documentation, I'm finding that saved payments cannot be used when auth + capture is enabled.

Attempting to pay via a saved payment method while auth + capture is enabled produces the following error on the front end:

```
Sorry, we are unable to process your payment at this time. Please retry later.
```

And this pops up in the logs:

```
Error: stdClass Object
(
    [error] => stdClass Object
        (
            [message] => The following payment method types ["giropay", "eps", "bancontact", "ideal", "sepa_debit", "p24"] can only be used with PaymentIntents that have capture_method=automatic. Please retry by creating a PaymentIntent with capture_method=automatic.
            [request_log_url] => https://dashboard.stripe.com/test/logs/req_OHRHNmYRRAy9Wv?t=1703627670
            [type] => invalid_request_error
        )

)
```

If this isn't related to deferred intent, please let me know and I'll be happy to open up a separate issue.

**Comment by james-allan** [comment]
Hey @csmcneill can you provide some replicating instructions? 

I've enabled auth and capture, created a saved payment method via the my account page and attempted to use that saved payment method to make a purchase. While testing on the latest version of Stripe, I couldn't replicate the error you mentioned.

We're you testing on the latest public version of Stripe or the working deferred intent branch (`add/deferred-intent`)?

If you were on the latest public version, then you might need to create a separate issue as this issue is specifically to do with the UPE with deferred intents project which isn't live at the moment. 

----

Something else I noticed from the error message you included from your log is that it mentions that "giropay", "eps", "bancontact", "ideal"... cannot be used with auth and capture. 

I have a feeling that you might be trying to use an APM that doesn't support auth and capture. If that's the case, the bug likely involves adding an APM saved payment method while Auth and Capture is disabled and then attempting to use that saved method while Auth and capture is enabled. 🤔 

In any case, if you can let me know what branch you were testing on, whether you had UPE enabled in WC > Payments > Stripe > Settings > Advanced and whether the payment method you were using was a saved card or perhaps a different method Giro pay, Sepa etc, then I should be able to point you in the right direction.

**Comment by csmcneill** [comment]
Thanks for looking into this @james-allan! I was using the latest stable release in my testing, so I wasn't using the deferred intent branch.

I'll do a bit more digging on my end, and I'll open up a fresh issue with some replication steps :)

**Comment by james-allan** [comment]
I've retested the lates `add/deferred-intent` branch with auth and capture enabled.

Block checkout
- [x] saved card
- [x] new card
- [x] 3DS card
- [x] Subscription free trial
Classic checkout
- [x] saved card
- [x] new card
- [x] 3DS card
- [x] Subscription free trial

**Notes** - In all the scenarios above the following expected outcome was observed: 

- On-hold order and an uncaptured charge in Stripe. 
- Processing the order captures the payment. 
- Because of the free trial, no payment is captured in that case. 

I noticed while testing that all the APMS are shown on the classic checkout even though auth & capture is enabled. 

| <img width="249" alt="Screenshot 2024-02-20 at 11 28 53 am" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/863ab081-41c8-4303-b436-3b13c33a2403"> | <img width="447" alt="Screenshot 2024-02-20 at 11 29 24 am" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/21da0bed-7e1a-4ce6-bd70-bd44049ac0f6">| 
|--------|--------|

I'll file a separate issue for that. Closing this one as auth and capture itself is working as expected.
