### ISSUE TITLE
[Split PE] Implement Split PE for cards in the block checkout

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-gateway-stripe#2789]
### Acceptance criteria

- When multiple payment method types are enabled, they must appear as different payment gateways in the classic checkout, as it happens when PE is disabled. Design xVAk98kbRKUByVTrhPc98g-fi-342_8806
- Payment processing must continue to work for cards
- Changes must be covered by tests
- e2e tests must be adjusted to at least maintain the same coverage they had before split PE

### Notes

This _might_ be handled in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2784. Confirm before grabbing this issue.

**Comment by james-allan** [comment]
This has been handled in #2784.

On the latest `add/deferred-intent` working branch, Cards with split have been implemented exclusively. 

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0daQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c0b6a35b3cb413bf79147caca0d481b9d603e5b1/Screenshot%202024-01-04%20at%209.56.07%20am.png" alt="Screenshot 2024-01-04 at 9.56.07 am.png" />

No other alternative payment method has been implemented yet. 

The way I implemented it for #2784, it loops over all the payment methods IDs ([ref](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/add/deferred-intent/client/blocks/upe/index.js#L13-L25)) and attempts to register the Payment method with the Blocks API ([ref](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/add/deferred-intent/client/blocks/upe/index.js#L40)).

The reason this doesn't work to implement split for all APMs is because those payment methods haven't been registered via the `$payment_method_registry` ([see this guide](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/checkout-payment-methods/payment-method-integration.md#putting-it-all-together)) and so it doesn't load. That's the next step as part of #2790. 

Given cards have already been implemented with Split UPE and they work to take card payments I'm going to close this as fixed in #2784.
