### ISSUE TITLE
Payment Request API: Issue with address verification (state)

### ISSUE THREAD

**Issue by GoodGuyTaj** [woocommerce/woocommerce-gateway-stripe#280]
Hi,

I implement the Payment Request API through the stripe gateway. When I tried to use different shipping addresses, it kept erroring and failing. It ended up being the State that caused it to fail. If I typed in Colorado, instead of CO, it would fail. Is this the plugin's fault or is the Payment Request API's fault?

#### Steps to reproduce the issue

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by sebsg** [comment]
Hi, 

I tried to reproduce your error, but to no avail. 

I completed the flow with an address from Colorado on the Mac and Android versions of Chrome on these two sites : 
https://woocommerce.paymentrequest.show/
https://rsolomakhin.github.io/pr/single/

Can you give me more information so I can try to repro?

Thank you!

**Comment by roykho** [comment]
@GoodGuyTaj - This issue only happens when using older versions of Chrome. Newer versions is a dropdown list of states in abbreviated form. But nonetheless I have put in a conditional check. Please test the master branch and see if it fixes your issues.

**Comment by GoodGuyTaj** [comment]
@sebsg I tried both of your links on my mobile and neither of them had issues while my website had issues.

@roykho I have a Galaxy S8+ and the playstore makes no mention of a newer version of Chrome. Is there a version of Chrome that Galaxy's are not privy too?

I pushed the new master branch to my staging site and that fixed about 50% of the issues (thanks for fixing this so fast). It fixed the issue with typing Colorado in (instead of CO). However, if I type COLORADO, it still fails.

**Comment by roykho** [comment]
@GoodGuyTaj - Yeah so originally only Chrome Canary or Chrome Dev had payment request features. And both of those browsers uses the dropdown state field instead of manual type. But in any case please test master again as I have just pushed up a fix.

**Comment by GoodGuyTaj** [comment]
@roykho - Thanks for the information. I pushed the new master and it works great! Thanks for being so responsive. 

With regards to the Payment Request API: it seems that if the browser does not support it, it takes them to standard checkout. Is there any way for the customer/user to abort/exit the Payment Request API and use the standard checkout(for whatever reason the customer may have) if they are on a supported version of Chrome?

**Comment by roykho** [comment]
No unfortunately its either on or off.

**Comment by sebsg** [comment]
Hi @roykho , I'm curious about the fixes you had to do. I'm trying to see if it's something we could do on our side (Chrome). Don't know if it's the best place for this conversation. 

Please let me know!

**Comment by roykho** [comment]
Sorry @sebsg I am not sure what you mean?

**Comment by sebsg** [comment]
You mention that you have fixed it on your side right? I was wondering if the fix you made is something we could do on Chrome too. 

Reason is, I don't think I understand what caused the error since we are supposed to send back the normalized state in the response. If I can get more insight into it, maybe I can fix it in Chrome too.

Does that make sense? Thanks!

**Comment by roykho** [comment]
Different Chrome versions have different ways to collect the state field. Some are just text fields where you can enter anything you want and others are dropdown fields where they're already predefined with the abbreviation. WooCommerce is expecting the latter. So all I did was normalized this in our code to account for the former. But it is not completely bulletproof because customers can still enter wrong/misspelled state name which would cause the same issue again.

**Comment by sebsg** [comment]
Oh I see. Dropdowns are used on Android and Desktop platforms now so that should help. Thanks for the info!

**Comment by madmath** [comment]
Thanks Roy, we are taking an action item as Chrome developers to make sure this is bulletproof for our users and the merchants.
