### ISSUE TITLE
Add PayPal

### ISSUE THREAD

**Issue by HH-LMS** [woocommerce/woocommerce-gateway-stripe#2807]
I would like it if you add PayPal also to this plugin. So you don't have to add another plugin for PayPal.
Stripe is supporting PayPal in their dashboard, so why don't add it to the plugin.

Thank you in advance!

**Comment by dougaitken** [comment]
_To ensure the WooCommerce team are having the most impactful work, we review open Issues on this GitHub repository to find out what is still relevant._ 

For Feature Requests, we are using the [Stripe Feature Request Portal](https://woocommerce.com/feature-requests/stripe/) for product enhancements rather than the GitHub repository.

**Please head to this Feature Request and add your vote! https://woo.com/feature-request/include-paypal-in-the-woocommerce-stripe-payment-gateway/ **

While you're there, use the keyword search to review other feature requests others have submitted already - you can then add your vote.
