### ISSUE TITLE
Critical Error When Deactivating Stripe for WooCommerce (WooCommerce inactive)

### ISSUE THREAD

**Issue by danielk-am** [woocommerce/woocommerce-gateway-stripe#2908]
**Describe the bug**
Critical error when deactivating Stripe for WooCommerce while WooCommerce is inactive.

**To Reproduce**
1. Go to Plugins > Installed Plugins.
2. Deactivate WooCommerce.
3. Deactivate Stripe.
4. Critical error encountered.

**Expected behavior**
I expect Stripe to be deactivated without any critical error.

**Additional context**
Is there a way to automatically disable Stripe or prevent it from being activated when WooCommerce is inactive?

**Comment by james-allan** [comment]
Hi @1dr0. Can you confirm you're using the latest version (v8.0) of the Stripe plugin? We fixed this very error a couple of weeks ago.

If the site is running Stripe 8.0, can you send us the fatal error message is so we can narrow it down. Thank you. 😃 

I'm going to close this one for now assuming it's the same error we fixed in 8.0.

**Comment by james-allan** [comment]
Sorry @1dr0 I'm mistaken. I've just noticed that 8.0 hasn't been released. In that case this issue has been fixed and will be deployed as part of our next release in 8.0.

For reference here's the original issue: https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2542 and the PR: https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2542
