### ISSUE TITLE
New Checkout Experience Display name not working correctly

### ISSUE THREAD

**Issue by carolframen** [woocommerce/woocommerce-gateway-stripe#2981]
**Describe the bug**
The display name on the new checkout experience is not showing on the checkout.

**To Reproduce**

1. Go to WooCommerce > Settings > Payments > Stripe 
2. Enable other payment methods besides credit card such as iDeal, Multibanco, etc.
3. Then, go to Stripe settings
4. Enable the new checkout experience
5. Under Display settings, set a display name
6. Now, go to the checkout page
7. The display name you chose is not there

**Expected behavior**
The expected behavior would be for the display name you chose to be on the checkout page. But also, the way my checkout page (while on the new checkout experience is enabled) look, does not match what is shown on the documentation.

Here's what the [documentation](https://woo.com/document/stripe/customer-experience/additional-payment-methods/#upe) says it will look like:
![image](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/119800062/d244e1d9-d992-4d88-8cdc-c949098222b3)

Here's how it looks on my website:
![image](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/119800062/afc0add8-6d0f-445c-970d-ca52fbc71331)

**Screenshots**
![image](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/119800062/ec485c80-4d89-4204-a998-94c6b04f3672)
![image](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/119800062/12899e64-292a-45bd-a76a-d6e77324cbd3)

**Environment (please complete the following information):**
 - WordPress Version: 6.4.3
 - WooCommerce Version: 8.6.1
 - Stripe Plugin Version: 8.0.0
 - Browser [e.g. chrome, safari] and Version: Chrome 122 on Windows 10
 - Any other plugins installed: I have tested this with only WooCommerce and Stripe on Storefront 4.5.4.

**Additional context**
This was brought up on the **[forum](https://wordpress.org/support/topic/can-not-pay-by-stripe-statement_descriptor-error/)**.

**Comment by a-danae** [comment]
Hey @carolframen ! Thanks for the report 🙂 

We have the following two GH issues to solve this problem:

- https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2993
With this, we'll allow customizing the label and description of each payment method.

- https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2990
With this, the Display name setting will be removed since it will be replaced by the new settings introduced by 2993.

I'm closing this issue in favor of these other two, but please feel free to reopen it if convenient.
