### ISSUE TITLE
[Afterpay] Clearpay logo not being displayed on the block checkout

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-gateway-stripe#3111]
**Describe the bug**

When using a Stripe account from the UK, the displayed logo on the block checkout is of Afterpay when it should be Clearpay instead.

**To Reproduce**
1. Connect a Stripe account from the UK
2. Change the store currency to Pound Sterling GBP
3. Enable Afterpay
4. As a merchant, go to the block checkout
5. Notice that the logo of Afterpay is displayed, even though the payment method is labeled as "Clearpay"

**Expected behavior**
The Clearpay icon must be displayed for the Clearpay payment method.

**Comment by james-allan** [comment]
I cannot replicate this today. I suspect we fixed it in one of the PRs we had around adding Clearpay/Afterpay. I saw I mentioned this bug here: https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3091#issuecomment-2089741696 the same day this issue was filed. But that WIP comment never made it into the final PR. 

![Image](https://github.com/user-attachments/assets/27f9fb4b-07a0-432c-a256-d773a2787f4a)

Closing this one.
