### ISSUE TITLE
Support Stripe Connect account when instantiating Stripe

### ISSUE THREAD

**Issue by jeffstieler** [woocommerce/woocommerce-gateway-stripe#312]
Upcoming work on WooCommerce Services will likely rely on this existing Stripe extension for accounts created on the Connect platform.

We'll need a way to specify the `stripeAccount` option when instantiating the `Stripe` object. See: https://stripe.com/docs/stripe.js#including-stripejs

👋  @mattyza

**Comment by roykho** [comment]
One way is to define a constant in WP Config. So `define( 'WC_STRIPE_ACCT', 'acct_adx9d9s' );` and the extension would just look for that and if found instantiate the Stripe object with that option.

**Comment by allendav** [comment]
We will also need to be able to set the stripe account from the REST API. So, instead of a PHP define, let's add this to the extensions settings. Further, when the stripe connect user account id is set, the API key fields should not be presented to the merchant in wp-admin.

See https://stripe.com/docs/connect/deferred-standard-accounts

**Comment by allendav** [comment]
Also noteworthy - while we can add the Stripe Connect User Account ID to the extension's settings (for the benefit of Calypso) we can't actually change the extension to use it for authentication since our platform secret is also required for "header based" authentication - see https://stripe.com/docs/connect/authentication#stripe-account-header

**Comment by jeffstieler** [comment]
> while we can add the Stripe Connect User Account ID to the extension's settings (for the benefit of Calypso) we can't actually change the extension to use it for authentication since our platform secret is also required for "Stripe-Account header" based authentication

@allendav where do we need to use the header-based auth? From what I understood, we would be using `stripe.js` which only requires the publishable (public) platform account key, and the connected account id. See: https://stripe.com/docs/stripe.js#stripe-function

**Comment by allendav** [comment]
> where do we need to use the header-based auth?

Nowhere. I was trying to make the the point that header-based auth is not an option for this extension because of the need for the platform secret

> From what I understood, we would be using stripe.js which only requires the publishable (public) platform account key, and the connected account id

I got the impression the connected account id was optional, and only used if we (the platform) wanted to execute transactions on the merchant's behalf (i.e. on our own servers, not the merchant's host) - do you get the impression the connected account id is needed more generally?

**Comment by jeffstieler** [comment]
> I got the impression the connected account id was optional, and only used if we (the platform) wanted to execute transactions on the merchant's behalf (i.e. on our own servers, not the merchant's host) - do you get the impression the connected account id is needed more generally?

Now that we've planned to retrieve the API keys that would normally be entered in manually by the user, there's no need to use the id AFAIK. The API keys should suffice.

**Comment by thorsten-stripe** [comment]
Yes, that is correct. When creating a deferred account or doing the OAuth flow we provide you with a set of API keys that are unique to your platform. Using these to authenticate allows you to run requests on the connected account but having the attributed to your platform. 

This way you don't need to use your platform secret key to make requests (which is the recommended way for hosted platforms) but simply use the generated API keys.

However, please note, since these keys are tied to your platform, should a connected account disconnect from your application (which they can do in their Dashboard), these API keys are voided and won't work anymore.
