### ISSUE TITLE
Multibanco is not compatible with Checkout Blocks

### ISSUE THREAD

**Issue by nicholasjeberlin** [woocommerce/woocommerce-gateway-stripe#3122]
**Describe the bug**
Multibanco is not compatible with Checkout Blocks. It does work with the older `[woocommerce_checkout]` shortcode though.

**Screenshots**
Checkout created with `[woocommerce_checkout]`:
<img width="543" alt="Screenshot 2024-05-06 at 1 07 27 PM" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/18408583/b6da2e9a-9029-464d-9138-313e042d1aec">

Checkout created with Checkout Blocks:
<img width="746" alt="Screenshot 2024-05-06 at 1 07 38 PM" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/18408583/034a728a-6b88-4a14-92ee-b38bcd06b803">

**Environment (please complete the following information):**
 - WordPress Version - 6.5.2
 - WooCommerce Version - 8.8.3
 - Stripe Plugin Version - 8.2.0
 - Browser [e.g. chrome, safari] and Version - Chome Version 124.0.6367.119 (Official Build) (arm64)

**Comment by nicholasjeberlin** [comment]
8151788-zen

**Comment by james-allan** [comment]
So I believe this is because Multibanco isn't supported via the Stipe UPE API. Multibanco works on the classic (shortcode) checkout by using the classic payment fields and having it's own `process_payment()` function.

At first I thought this would be a simple fix to make sure multibanco was included in the list of UPE methods but that wouldn't work. I think we'd need to build multibanco as a blocks payment method from the ground up.

**Comment by Mayisha** [comment]
Multibanco is now supported in the checkout blocks since `8.5.0` for UPE.

<img width="795" alt="Screenshot 2024-08-20 at 1 45 56 PM" src="https://github.com/user-attachments/assets/5a835723-0377-4910-8fdf-63da00bbd3f7">


You have to enable UPE (uncheck `Enable the legacy checkout experience` checkbox) in the Stripe settings page and set the store currency to Euro.

<img width="1130" alt="Screenshot 2024-08-20 at 1 43 53 PM" src="https://github.com/user-attachments/assets/80ada083-04a0-4202-a662-e5f26a4a16f5">
