### ISSUE TITLE
Cartes Bancaires support

### ISSUE THREAD

**Issue by jdrda** [woocommerce/woocommerce-gateway-stripe#3147]
As Stripe support very easily Cartes Bancaires, it would be nice to have it there.

**Comment by a-danae** [comment]
Hey @jdrda 👋  Thanks for reaching out!

We introduced support for Cartes Bancaires in 8.3.0. We're releasing [8.3.1](https://github.com/woocommerce/woocommerce-gateway-stripe/releases/tag/8.3.1-test) soon. It'd be good to wait for that release before updating.

We have more details on how it works in our documentation:
- https://woocommerce.com/document/stripe/customer-experience/cartes-bancaires/
- https://woocommerce.com/document/stripe/customer-experience/#co-badged-cards
- https://woocommerce.com/document/stripe/#customer-experience

I'm closing this issue since it should be done, but please feel free to open it again if I didn't get your request right or if there's any further action needed on our end 🙂

**Comment by jdrda** [comment]
Hi @a-danae ,

thanks for info. The first link is 404. I checked version 8.3.0 and did not see CB as payment possibility. Could you please explain, how it works? Could customer enter the card number directly with VISA / MC and so there is no need of using another subplugin like Klarna has?

Thanks a lot :)
