### ISSUE TITLE
single order, dublicate payment processed on stripe

### ISSUE THREAD

**Issue by heavestudio** [woocommerce/woocommerce-gateway-stripe#3220]
Using both woocommerce subscription and woocommerce stripe payment gateway.

everything was working fine, but for more than a week i can see that every order on the website create two payment request on stripe.

Only one api webhook active.

Tried to remove totaly the connection between the site and stripe and reset.

Change the way cron are triggered.

Nothing changes, still have a duplicate payement for every order

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - WordPress Version
 - WooCommerce Version
 - Stripe Plugin Version
 - Browser [e.g. chrome, safari] and Version
 - Any other plugins installed

**Additional context**

**Comment by aheckler** [comment]
Sounds like this might be an instance of https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2307, but I can't be sure?

@heavestudio 

> every order on the website create two payment request on stripe.

Are there any differences between the requests in the logs? Does one have Level 3 data and the other not?

**Comment by heavestudio** [comment]
at begining it had failed payment, but now, all payment are suceed
![Capture d’écran 2024-06-25 162218](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/70941515/91020373-3cfe-48e1-a7d7-f6591d853aff)

**Comment by aheckler** [comment]
Ah OK, so judging by the French there, this probably isn't a Level 3 data issue, since Stripe only supports Level 3 for U.S. merchants.

My suggestion would be to [contact our support staff](https://woocommerce.com/my-account/create-a-ticket?select=18627), explain the details of the error, give them any logs you have, etc. and see what they can help you find out. Without this being a confirmed bug in our code, GitHub really isn't the best place for the problem.

Thanks!
