### ISSUE TITLE
[HC] Stripe is showing unwanted messages on the payment options on version 8.5

### ISSUE THREAD

**Issue by carolframen** [woocommerce/woocommerce-gateway-stripe#3272]
**Describe the bug**
When using 8.5 some payment methods show an unwanted message on checkout.
It's the message that explains the payment method for the store owner, but it shouldn't be shown to the customers.

This only happens with the new checkout experience.

**To Reproduce**
1. Have Stripe 8.5
2. Check the credit card option on checkout

**Expected behavior**
For the message to not show.

**Screenshots**

![image](https://github.com/user-attachments/assets/94b89d49-7f85-4039-8031-3383bfd2f552)
![image](https://github.com/user-attachments/assets/20b20754-d3b1-46ac-b884-918ec3232e26)

Here's a screenshot of my checkout on 8.4
![image](https://github.com/user-attachments/assets/f401fa68-3e90-4093-a290-d01968fd322d)

**Environment (please complete the following information):**
 - WordPress Version: 6.5.5
 - WooCommerce Version: 9.1.1
 - Stripe Plugin Version 8.5
 - Browser and Version: [Chrome 126 on Windows 11](https://www.whatismybrowser.com/detect/what-version-of-chrome-do-i-have/)
 - Any other plugins installed: I tested with only Woo and Stripe active and on the Storefront theme

**Additional context**
Reported **[here](https://wordpress.org/support/topic/version-8-5-0-shows-messages-in-credit-card-and-sepa-dropdown-on-checkout-page/)**.

**Comment by OmarFPG** [comment]
I can also confirm the new text, however, this [is not a bug, it's a feature](https://www.google.com/search?sca_esv=458fc5d25ecd7a59&sxsrf=ADLYWIL9JocTM3v1LHDNNWOJZI5DLopQCQ:1720815148038&q=it%27s+not+a+bug,+it%27s+a+feature&udm=2&fbs=AEQNm0Aa4sjWe7Rqy32pFwRj0UkWd8nbOJfsBGGB5IQQO6L3J_86uWOeqwdnV0yaSF-x2jqnIzeFqsIkHfSINaNrAc0czRdnEMnTiu1W2iGRAO9H_3HwxTbnIzl0yV4QsB3FxIblXBj8MTHCaDhZGqx1OJ-lbERkeNml07hk0Vke1SfZT9YYuepDjH8kmbV3dA8KS-CRjeqD&sa=X&ved=2ahUKEwi0y_38p6KHAxWcTjABHatOCFkQtKgLegQIDhAB&biw=1920&bih=911&dpr=1).

Reviewing the latest [changelogs for Stripe](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/changelog.txt) you can find this: 
> * Add - Allow customizing the title and description of the UPE payment methods.

Which is awesome! You can customize each by going to your WooCommerce > Settings > Payments > Stripe > Payment Methods > Customize (next to each payment method). You can add a Name and a Description for each.

Edit: Here’s the relevant documentation for it: https://woocommerce.com/document/stripe/setup-and-configuration/additional-payment-methods/#customizing

Edit 2: it may actually be a bug, though, since maybe the empty settings shouldn't include a default string; I've seen another report already [here](https://wordpress.org/support/topic/custom-description-blank-doesnt-save/). From [this comment](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3176#pullrequestreview-2103066424) in the PR, it seems the empty should work, and from what we're seeing in actual usage, it isn't working!). (edited)

**Comment by mattthomasphoto** [comment]
It’s definitely a “new feature” however bugged the fact it’s pulling through the backend admin descriptions, which should definitely not be displayed to a customer. On the legacy version this wasn’t the case.

At the moment the only way is a dirty CSS method to hide, which isn’t ideal and shouldn’t be considered as a “fix”

**Comment by aheckler** [comment]
The dev team is aware of this issue and we're discussing the best way to handle it.

**Comment by Prin-S** [comment]
8494269-zd-a8c

**Comment by Prin-S** [comment]
8497019-zd-a8c
8514039-zd-a8c
