### ISSUE TITLE
Double order notes and double emails still occurs in version `8.6.1`

### ISSUE THREAD

**Issue by Mayisha** [woocommerce/woocommerce-gateway-stripe#3414]
**Describe the bug**
We fixed the [double order notes and emails](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2463) issue in Stripe `8.6.1` ([PR](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3331)). While some reporters confirmed that the issue is now fixed for them [[1]](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2463#issuecomment-2278498228)[[2]](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2463#issuecomment-2284341791), some users reported that they are still facing this issue-

1. https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2463#issuecomment-2288522780
2. https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2463#issuecomment-2299160831
3. https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2463#issuecomment-2323284089
4. https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2463#issuecomment-2327301387

**Comment by mattallan** [comment]
Thanks @Mayisha for pulling this out to a separate issue and listing the most recent incidents!

I think i've been able to replicate this on the latest Stripe version. Here are my findings:

- Duplicated emails sent 4 seconds apart:
![image](https://github.com/user-attachments/assets/bced59a2-2fb9-4a00-a52c-549ac2364a28)

- Duplicate order notes:
![image](https://github.com/user-attachments/assets/9491701b-1c34-4749-b0ae-ce6aa74a8df8)

### Steps to reproduce:

> [!IMPORTANT]
> To reproduce this issue you need to simulate the `setup_intent.succeeded` webhook being sent at the same time that `process_payment_with_deferred_intent()` is still processing the payment for the current order.
>
> **How would this possible?**
> It's hard to pin-point exactly how this would happen but Stripe controls when the webhook is sent and there's a lot of processing that needs to happens between sending our intent requests -> receiving the response -> completing the payment/checkout process.
> This means if there's any unexpected lag or delays (i.e. slow DB read, slow API request, third party code), it could cause both the webhook handling and process payment function to try and mark the order as completed at the same time, resulting in duplicate emails and order notes.

1. Activate the latest Woo Subscriptions and create a subscription product with free trial
2. Enable the credit card payment method and new checkout experience.
3. Make sure webhooks are setup correctly so that your test site is receiving them
4. Add the free trial subscription to your cart
5. Complete the checkout
6. View the Edit Order admin page and confirm there's duplicate order notes for processing the order
