### ISSUE TITLE
[ECE] Do not display ECE/PRB when CC is not enabled

### ISSUE THREAD

**Issue by annemirasol** [woocommerce/woocommerce-gateway-stripe#3546]
**Describe the bug**
When express payment methods are enabled, but credit cards are not, Apple Pay and Google Pay are still available in the <s>product, </s>cart and checkout pages. However, the shopper cannot complete their purchase using them, and the order results in an `Invalid payment method` error.

**To Reproduce**
1. As a merchant, enable `Apple Pay/Google Pay`, but disable `Credit card / debit card` as a payment method.
2. Enable some other payment method, like CashApp.
3. As a shopper, add a product to your cart.
4. Verify that Google Pay and/or Apple Pay are displayed in the <s>product, </s>cart and checkout pages.
5. Attempt to complete the purchase using Google Pay or Apple Pay. Notice that it will let you launch the payment modals. 
6. After clicking "Pay", the order will fail with an `Invalid payment method` error. 
**Expected behavior**
I expect Apple Pay/Google Pay to not be displayed if the shopper cannot finish their purchases using said methods.

**Screenshots**
![Image](https://github.com/user-attachments/assets/4d8a6576-12b0-4082-80a5-468d80df5800)

**Comment by james-allan** [comment]
@annemirasol I haven't been able to replicate the Google or Apple Pay buttons being shown on the product page following your steps.

**I think this issue is limited to the block cart and block checkout pages.** 

It's my understanding that this is because how `display_express_checkout_button_html()` determines if it should load the element for mounting the buttons to. In my testing `display_express_checkout_button_html()` isn't outputting the mounting element when cards are disabled and so even though the JS does everything else to render the buttons, there's no element to mount them to. There's nothing like this on the block powered pages, WC core mounts the buttons for us when we register them.

So, IMO we have 2 options here:

1. Make the block cart and checkout pages consistant with the other pages. ie Don't render them if cards are disabled. 
2. Work out if we can support these express buttons even if cards are disabled. 

The reason I've mentioned that second option is because if you disable cards in your Stripe settings you'll notice that Link disappears as an available express checkout method. Google and Apple Pay remain. I'm not sure if that's communicating that they should still work. 🤷‍♂

**Comment by annemirasol** [comment]
@james-allan Thanks! I've updated the description and removed the product page from the affected pages.

> So, IMO we have 2 options here:

I have no strong opinion here, but if we go for option #1, i.e. do not render, it would be great if we make the payment methods admin page's behavior consistent.
