### ISSUE TITLE
Prevent multiple `$order->payment_complete()` calls and duplicate "Stripe charge completed" order notes during subscription renewal processing

### ISSUE THREAD

**Issue by mattallan** [woocommerce/woocommerce-gateway-stripe#3568]
**Describe the bug**

> [!IMPORTANT]
> **Customers are not being double charged as a result of this issue.** There are however other potential areas of your store that could be impacted by this issue due to the multiple `$order->payment_complete()` calls and the multiple status transition hooks being triggered.

While processing subscription renewal payments, we are unlocking the order too early in the process leaving a small window for the `payment_intent.succeeded` webhook sent by Stripe to validate and proceed to mark the order as payment complete in parallel with the current request.

Here's a quick breakdown of our `process_subscription_payment()` function:

```
1. process_subscription_payment( $amount, $renewal_order )
2. lock_order_payment( $renewal_order )
3. create_and_confirm_intent_for_off_session( ... )
4. unlock_order_payment( $renewal_order )
5. get_latest_charge_from_intent()                // sends a "GET charges/ID" request off to Stripe
6. process_response( $charge, $renewal_order )    // marks the order from pending -> processing/completed status
```

From above, if there are delays in fetching the latest charge from Stripe, this gives time for the `payment_intent.succeeded` to be sent and because the order is still pending, this results in both requests eventually marking the order as `payment_complete()`.

**To Reproduce**

To replicate this consistently, I had to add a small `sleep( 2 );` between fetching the latest charge from Stripe and calling process_response() ([here](https://href.li/?https://github.com/woocommerce/woocommerce-gateway-stripe/blob/9cfc896a4b8ba790a482094df827df294680855f/includes/compat/trait-wc-stripe-subscriptions.php#L556)). While it seems hacky, this change in a sense just simulates a slow Stripe request to fetch a charge object which can happen.

```
$latest_charge = $this->get_latest_charge_from_intent( $response );
sleep( 2 );
$this->process_response( ( ! empty( $latest_charge ) ) ? $latest_charge : $response, $renewal_order );
```

1. Activate WooCommerce Subscriptions and purchase a subscription product with any successful card `4242424242424242`
2. Process a renewal order using the "Process renewal" action on the Edit Subscription page
3. While visiting admin Edit Order page for new renewal order and the admin Edit Subscription page, notice the double order notes:

| Renewal Order | Subscription |
|--------|--------|
|![Image](https://github.com/user-attachments/assets/ea88b638-f8d3-4989-bf6e-e48557cb6ce6)|![Image](https://github.com/user-attachments/assets/6987eb7a-1db7-41de-b50f-42d0d2322119)|

**Comment by contemplate** [comment]
@mattallan We are experiencing what I believe is this bug on a client's WooCommerce Subscription site which has Object Caching Pro on Nexcess WooCommerce Hosting.  We noticed that since October 15th we've had 410 Virtual Renewal Orders changed to "Processing" instead of "Completed".  This is most likely due to the the integration with Autocomplete WooCommerce Orders which seems to mark the first event as "Complete" but the second one stays as "Processing".  This is happening on a majority of renewal orders but not all.

I think it may be related to this issue as well but these are paid and not manual orders:
https://github.com/Automattic/woocommerce-subscriptions-core/issues/707

![Image](https://github.com/user-attachments/assets/8b549d70-125d-48d3-8cff-044debd70865)

![Image](https://github.com/user-attachments/assets/7f246d17-0ba0-4ea8-a7bc-fce98b891b97)

WooCommerce Stripe Gateway Version 8.8.1
WooCommerce Subscriptions Version 6.8.0
WooCommerce Version 9.3.3
Autocomplete WooCommerce Orders Version 3.3.6
Object Cache Pro Version 1.21.3

I'm going to check other clients in this scenario.

**Comment by georgejipa** [comment]
One of my clients' websites is experiencing the same issue. Hopefully, a patch will be released soon.

| Renewal Order  | Subscription  |
| ---------------  | ------------- |
| ![Image](https://github.com/user-attachments/assets/66433a62-fd52-4979-98b5-a340156760c2) |  ![Image](https://github.com/user-attachments/assets/715d708a-02ea-4365-9f86-a1ed26b7857d)  |

Plugins:
> WooCommerce Stripe Gateway Version 8.8.0
WooCommerce Subscriptions Version 6.8.0
WooCommerce Version 9.3.3

No object cache plugins are installed.
