### ISSUE TITLE
Payment Method is detached after WordPress user is deleted on a cloned site

### ISSUE THREAD

**Issue by grig-23** [woocommerce/woocommerce-gateway-stripe#3582]
**Describe the bug**

A very similar bug has been fixed in WooPayments recently:

https://github.com/Automattic/woocommerce-payments/issues/5384

Given a user with a WooCommerce subscription and a Payment Method stored in Stripe, if WordPress site is cloned, and the User is deleted on that cloned site, the pm_token is detached on Stripe in Production.

**To Reproduce**
1. Create a WooCommerce Subscription
2. Subscribe to a service with a test user
3. Login to the dashboard.stripe.com and confirm that the Customer was created and has a Payment Method in place
4. Setup a clone of that site, e.g. with WP Migrate Lite
5. Check if Stripe is connected on the clone. It might have to be re-connected given the new Stripe connection flow/mechanism.
6. From WP Admin panel of the clone site, go to Users and delete the customer you created on Step 2.
7. Go back to the Stripe Dashboard and look for the Customer. The customer exists but the Payment Method was detached.

**Expected behavior**

Deletion of a customer on the clone/staging site should not result in their payment method getting detached.

The payment token should remain untouched, or at least, a Confirmation screen should alert the user that there will be changes happening outside of WordPress.

**Screenshots**

**Environment (please complete the following information):**
N/A

**Comment by nicdwilson** [comment]
I'm not sure that this is a bug specifically,. In 8.4 we released [2672-zen](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2672) which added the `should_detach_payment_method_from_customer` function.

However, in 8820698-zd-a8c a careless developer has managed to detach 384 payment methods from subscriptions using a cloned site.

The site was connected to the live Stripe account (not in test mode) and no environment variables were set. This is a major hit for the customer. While this is on the developer, the problem is not necessarily well documented, developers do not RTFM, and many builders lack the technical chops to even know about the WP environment settings.

While we have some checks in place, I believe we need to be more aggressive, using something like the Woo Subscriptions staging site option (which compares a Search & Replace proofed live site URL with the current `site_url` to determine staging mode, or a full blown safe mode, as used in WooPayments and Jetpack.

Just a further comment that WP Staging, in the replication above, sets a staging environment variable, and therefore cannot be used to replicate. I would replace that step with something like using WP Migrate Lite, for example.
