### ISSUE TITLE
When paying with Apple Pay, tax isn't passed by AvaTax

### ISSUE THREAD

**Issue by dougaitken** [woocommerce/woocommerce-gateway-stripe#413]
#### Affected ticket(s)

ticket: 798272-zen

#### What I expected

When using Apple Pay via Stripe, Tax is shown correctly

#### What happened instead

When using [Stripe Payment Gateway](https://www.woocommerce.com/products/stripe/) and Apple Pay, the tax is missing from the Apple Pay dialogue.

#### Steps to reproduce the issue

Extensions active:

* [Stripe Payment Gateway](https://www.woocommerce.com/products/stripe/) with Apple Pay enabled
[AvaTax](https://woocommerce.com/products/woocommerce-avatax/)

With Apple Pay and AvaTax active, paying using Apple Pay doesn't have taxes calculated.
Disabling `Enable AvaTax tax calculation` shows taxes using Apple Pay.

From Beka

> sounds like Stripe needs to call `$cart->calculate_totals()` when loading apple pay / changing addresses, no issues with Apple Pay using AuthNet AIM or AuthNet CIM: 

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Hi @dougaitken have you tested this in 4.0? Also where can we get Avatax test account?

**Comment by roykho** [comment]
@dougaitken nvm, I searched around and apparently you can setup 30 days trial accounts.

**Comment by roykho** [comment]
Closed in favor of https://github.com/woocommerce/woocommerce-gateway-stripe/issues/566

**Comment by ingramleedy** [comment]
This is still an open issue and got lost in the merge request.    This is a pretty serious issue for ecommerce stores to be compliant with US state taxes and nexus rules!    I am sure as a merchant they pay what was collected, but in this case it wasnt collected and the merchant technically is still required to pay the taxes.       In our case, we use alot of drop shipping services, and we get charged taxes regardless if we captured it or not!

So --  

When using *Avalara Tax Plugin* to override internal tax tables and using *Stripe Payment Instant Payment Buttons*  (Instant Payment buttons on Product, Cart, and Top of Checkout page), taxes are not calculated based on what is in the wallet address or if the user changes the wallet address. 

(you can actually change the address in the wallet, refresh the page, and then the wallet calculates the correct tax. Or if the Woo already knows the user's address from a pervious checkout. However, I don't think its using the wallets address initially)

If using internal tax tables, all this works as expected.

The expected behavior is the calculated taxes are based on what is in the wallet address when it pops up the the first time or the address is changed in the wallet.  It should be the same behavior as using the internal tax rates.
