### ISSUE TITLE
Confusing UI - credit card fields greyed out

### ISSUE THREAD

**Issue by madeincosmos** [woocommerce/woocommerce-gateway-stripe#447]
#### Affected ticket(s)
N/A - found when testing for other problems.

#### What I expected
For the credit card fields to indicate their status clearly.

#### What happened instead

When I first load the page the fields look like disabled - dark grey sample text on lighter grey background:
![Screenshot](http://cld.wthms.co/934676+)
Screenshot: http://cld.wthms.co/934676

It looks even worse with Twenty Seventeen when the background color of the container is almost identical:

![Screenshot](http://cld.wthms.co/1DHfiZ+)
Screenshot: http://cld.wthms.co/1DHfiZ

#### Steps to reproduce the issue
Open the checkout page with a default theme and observe.

WC 3.2.6 & 3.3.0-beta1 + Stripe 4.0.1

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
They're actually the same color as all the other default WC form fields. ![](http://cld.wthms.co/Bi0Xts+) but the reason why it doesn't stand out as much is because the background of the payment area is of a darker shade. 

Also placeholder text traditionally is suppose to be light in color within the field.

How do you propose we make this stand out more that would work on most themes?
