### ISSUE TITLE
[Sources] Add Klarna support via Sources

### ISSUE THREAD

**Issue by dougaitken** [woocommerce/woocommerce-gateway-stripe#457]
#### Affected ticket(s)

903246-zd

Klarna is in a beta period, and support can be added via Sources. A public test page can be seen here - `https://stripe.com/sources/test_klarna`

More details in the ticket.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by thorsten-stripe** [comment]
@dougaitken can you please tell the user to get in touch with plugins+woocommerce@stripe.com with some details about their business. We have an internal clone of the WooCommerce Gateway with support for Klarna that we can share with them if they are a good fit for the beta.

Adding this publicly we'll only want to do once we move it to general availability.

**Comment by lkraav** [comment]
Hi. We're also looking into this. March 2020: what's the current status?

**Comment by dougaitken** [comment]
cc @allendav @bmccotter for current status of Klarna. I can edit my initial comment when we know.

**Comment by lkraav** [comment]
Thanks. It seems like a list of other Sources-based implementations already exist, iDEAL, Bancontact etc. Should this issue be re-opened cc @thorsten-stripe

**Comment by bmccotter** [comment]
Hi @lkraav -- its on our radar to implement with a few other APM's in 2020. Its not scheduled currently on our roadmap.

**Comment by lkraav** [comment]
If we could find a solid contractor to file a PR (Upwork or elsewhere), do you think y'all have bandwidth to review?

Looking at https://github.com/woocommerce/woocommerce-gateway-stripe/tree/master/includes/payment-methods implementing APMs doesn't look back-breakingly difficult, but I'm completely oblivious to any Klarna-specifics.

**Comment by allendav** [comment]
Reopening. We'll take a look at the LOE required to add this to checkout and provide an update.

**Comment by DanReyLop** [comment]
cc/ @allendav 

### Country support

For other APMs, we are just checking the site's currency to see if it's compatible. For example, for `SOFORT`, we are just checking that the store is in €.

For Klarna we could do the same, and check that the store is in `EUR`, `DKK`, `NOK`, `SEK`, `GBP`, or `USD`.

The payment will fail if for example the store is in `GBP` and the client is from France. 

**Effort: Minimal w/o multicurrency support, High with multicurrency support.**


### Legal stuff

Klarna requires that the merchant's Terms and Conditions and Privacy Policy are updated to reflect Klarna's involvement. ([https://stripe.com/docs/sources/klarna#prerequisite](See here). We could just add a warning to the Klarna settings page.

**Effort: Low.**


### Boilerplate payment method definition

We have several payment methods with identical code for the most part. We just need to change the descriptions, icon (we need an icon), etc.

**Effort: Medium.**


### Source creation

Klarna has many more required parameters to include in the Source object creation, but all that information can be fetched from the Cart.

**Effort: Medium.**


### Payment processing

Klarna has 2 modes of checkout: embedded, or redirect. I assume we'll want redirect (even though it's not their recommended option) because it's similar to the other APMs and it will be much simpler for us.

When the Source is created, it returns 3 URLs:
- URL to pay immediately
- URL to "pay later"
- URL to pay in installments

To keep this contained, let's assume we only want "Pay now".

Klarna allows for a bit of customization on their hosted checkout page:
- Business logo (needs to be a publicly accessible URL served as HTTPS).
- Background image (same).
- Page title.
- "Pay" button type (it can be "buy", "rent", "download", etc).

Let's assume we don't allow for any of that for the first iteration.

Klarna is asynchronous for payments made by customers in the UK and U.S., and synchronous otherwise. That means we need to support both flows. Fortunately, we already do, but we need to make it clear in the settings page that Webhooks need to be correctly configured, or else the async flow won't work.

**Effort: Medium.**


### Support for restricted businesses

When creating the Source object, there's an optional parameter called `klarna[attachment]`:
> Additional purchase information relating to the transaction that may be required for select businesses, such as those on Klarna’s Restricted List to increase approval rates. Values provided vary based on business type and can be found on Klarna’s site
And in Klarna's API docs:
> The required parameters will be described in the appendix of contract agreement.

So that looks like a rabbit-hole to support.

**Effort: High.**


### Conclusion

The basic functionality should be relatively easy to add. It would pretty much consist on copying an existing payment method, changing its description/icon/etc, adding some legalese to the settings page, and add all the required fields when creating the Source object. **I would say that would take a single person around a week to code, plus another week for review and testing, being conservative.**

And these are the features we could consider as "nice to haves":
- Embedded flow (instead of redirect). This is a wildcard, could be a day, could be a week.
- Multicurrency integration. This is a week at the very least, because there are lots of multicurrency extensions.
- Allow for "Pay later" and "Pay in installments". That could be an admin setting (easy) or a checkout option (harder, would need some extra UI). Technically the only thing that changes is that the URL to redirect to is different. But we'd need to test if by choosing "Pay in installments" for example, how is that perceived in Stripe's side. Several charges? I give this a week at the very least.
- Allow customization of the checkout page. Allow the merchant to add a logo, or use the store's logo automatically. Add admin settings to add a title and the type of "Pay" button. This should be a couple of days.
- Support for restricted businesses. This could be a day, could be a week.

**Comment by allendav** [comment]
Thank you @DanReyLop !

@bmccotter - sounds like a sprint's worth effort. Shall we pick a milestone? We'll want to carefully consider what we want to support for restricted businesses. Perhaps that part could be deferred from the first implementation?

**Comment by bmccotter** [comment]
Yes! Lets discuss during ou 1:1.

**Comment by getimo** [comment]
Hello, I’ve been pointed to this page by your staff on Wordpress.org. I just wanted to know if there’s a ready to work plugin or an update to that topic. The evaluation sounds like it would be coded fast but I can’t find any Informationen.

Many thanks in advance
Thomas

**Comment by bmccotter** [comment]
Hi @getimo we have Klarna on our roadmap, and as soon as we have timing around this we will be sure to share. Thank you for checking in!

**Comment by ServusNL** [comment]
It has been a while (9 months), is there any update on adding Klarna to the WooCommerce Stripe Payment Gateway?

**Comment by ServusNL** [comment]
> Hi @getimo we have Klarna on our roadmap, and as soon as we have timing around this we will be sure to share. Thank you for checking in!

Any update?

**Comment by demaya** [comment]
Any update on this?

**Comment by loge99** [comment]
Please tell this has been added already!!!!!

**Comment by nabeel-s** [comment]
Today Stripe announced on Twitter that Klarna is available on Stripe now. Will this be available in the WooCommerce Stripe plugin soon?

**Comment by bhound** [comment]
> 
> 
> Hi @getimo we have Klarna on our roadmap, and as soon as we have timing around this we will be sure to share. Thank you for checking in!

Is this issue still on the roadmap, and if so about how far out is it? Thanks!

**Comment by joostzx** [comment]
Dear Developer(s), 

I think Klarna is very important because "pay afterwards" is required by some authorities. An important condition of [https://www.thuiswinkel.org](url) is that customers have the option to pay afterwards.  

Only when you have this in working condition you can get a certification from [https://www.thuiswinkel.org](url) For many stores this is very important to have. Apart from that, of course you also want to serve your customer with an opportunity like this.

Of course i have read this article: [https://wordpress.org/support/topic/klarna-beta-stripe-products/](url) Where you have kindly ask to **Do no ask for an implementation date – the team are aware and will work on it in time**.

I hardly dare to ask... :)   but still hoping for an answer

Kind Regards,

Joost

**Comment by getimo** [comment]
> Dear Developer(s),
> 
> I think Klarna is very important because "pay afterwards" is required by some authorities. An important condition of [https://www.thuiswinkel.org](url) is that customers have the option to pay afterwards.
> 
> Only when you have this in working condition you can get a certification from [https://www.thuiswinkel.org](url) For many stores this is very important to have. Apart from that, of course you also want to serve your customer with an opportunity like this.
> 
> Of course i have read this article: [https://wordpress.org/support/topic/klarna-beta-stripe-products/](url) Where you have kindly ask to **Do no ask for an implementation date – the team are aware and will work on it in time**.
> 
> I hardly dare to ask... :) but still hoping for an answer
> 
> Kind Regards,
> 
> Joost

Since it’s over a year since I asked I think you can ask without mercy. :D 

no joke: 1 year is like 10 years on the Internet. The development of technologies is so fast that I ask myself if stripe is that top notch payment provider like they promote themselves on their website. I understand not to answer every question but waiting for 1 year without ANY information is just sad.

**Comment by loge99** [comment]
Guys, I wouldn‘t worry about them anymore. By now there is a very well rated alternative!
-> https://wordpress.org/plugins/woo-stripe-payment/

Oh and not just Klarna. This plugin above can do everything. 

May you never need to come back to this link ever again.
✅

**Comment by mredodos** [comment]
some news? +1 for add klarna

**Comment by serenityinchains** [comment]
The fact that the Developers are no longer responding means I'll be leaving this plugin. For them to not implement something so vital to our businesses, that has been available for YEARS on other plugins is ludicrous.

**Comment by felipevelzani** [comment]
Hi everyone, our team is still considering adding Klarna support to our WooCommerce Stripe extension.

We will let you know when we have updates on that. We appreciate your patience. 

_(For reference, I deleted a comment that was spam for a different WordPress plugin.)_

**Comment by getimo** [comment]
Still „considering“? I’m sorry but that’s not enough and too late. We switched already.

**Comment by loge99** [comment]
But the real DICK move is, they removed the comment with the plug-in that does a better job than theirs calling it SPAM.
That‘s what I call spitting on your own community.

**Comment by felipevelzani** [comment]
Hi @loge99!

It's important to remember that WooCommerce Stripe is a free and open-source solution. Anyone can create pull requests (with proposed new features), fork the repository to create their own version of the plugin, or even use a different independent plugin. All these are valid options and are part of the open-source freedoms.

Still, commenting on our repository with links to other projects and suggesting users no longer use our plugin is not okay, and that's why we considered this comment spam.

**Comment by loge99** [comment]
> Hi @loge99!
> 
> It's important to remember that WooCommerce Stripe is a free and open-source solution. Anyone can create pull requests (with proposed new features), fork the repository to create their own version of the plugin, or even use a different independent plugin. All these are valid options and are part of the open-source freedoms.
> 
> Still, commenting on our repository with links to other projects and suggesting users no longer use our plugin is not okay, and that's why we considered this comment spam.

Yo Felipe, you can make up whaaaaatever you feel good with, but it’s not gonna change facts or how anyone following this thread is starting to view this.

**Comment by serenityinchains** [comment]
> Hi everyone, our team is still considering adding Klarna support to our WooCommerce Stripe extension.
> 
> We will let you know when we have updates on that. We appreciate your patience.
> 
> _(For reference, I deleted a comment that was spam for a different WordPress plugin.)_

@felipelousantos 
While I understand that this plugin is free and open source, not including the pay-in-4 in your plugin is simply unacceptable. It's been available for years, it's been requested multiple times. Not having that option for our clients during checkout is leaving money on the table for those of us using it, and I would have gladly paid a subscription fee to ensure that it (and other new features) were included in a timely manner.

As such, we've moved to a different free and open sourced plugin that DOES offer the features we need. It's a shame, because as a developer you could have capitalized on this easily while also caring for the community you had fostered with this plugin. Instead, the indifference has left our company (and many others) no choice but to delete your plugin and move on.

**Comment by bhound** [comment]
> Hi everyone, our team is still considering adding Klarna support to our WooCommerce Stripe extension.
> 
> We will let you know when we have updates on that. We appreciate your patience.
> 
> _(For reference, I deleted a comment that was spam for a different WordPress plugin.)_

Ok, but it's gone from "on the roadmap" to "still considering" - as others have mentioned this is becoming a serious compliance issue as in some places pay over time functionality is legally required. I'd highly suggest bumping up the priority otherwise your plugin is going to become irrelevant since it won't meet business' statutory obligations.

**Comment by markmaurerrr** [comment]
4 years later and still missing. I absolutely can't believe it.

**Comment by robbens** [comment]
> > Hi everyone, our team is still considering adding Klarna support to our WooCommerce Stripe extension.
> > We will let you know when we have updates on that. We appreciate your patience.
> > _(For reference, I deleted a comment that was spam for a different WordPress plugin.)_
> 
> @felipelousantos While I understand that this plugin is free and open source, not including the pay-in-4 in your plugin is simply unacceptable. It's been available for years, it's been requested multiple times. Not having that option for our clients during checkout is leaving money on the table for those of us using it, and I would have gladly paid a subscription fee to ensure that it (and other new features) were included in a timely manner.
> 
> As such, we've moved to a different free and open sourced plugin that DOES offer the features we need. It's a shame, because as a developer you could have capitalized on this easily while also caring for the community you had fostered with this plugin. Instead, the indifference has left our company (and many others) no choice but to delete your plugin and move on.

Would you like to share the alternative you're using that has implemented Klarna? 🙏 

It really is a shame that this official plugin is lacking all the new features Stripe offers.

**Comment by loge99** [comment]
THIS ONE IS THE 5-STAR PLUGIN THAT HAS IMPLEMENTED ALL KLARNA FEATURES AND WORKS PERFECTLY:

https://de.wordpress.org/plugins/woo-stripe-payment/

**Comment by loge99** [comment]
@robbens this is the working alternative: https://wordpress.org/plugins/woo-stripe-payment/ Payment Plugins for Stripe WooCommerce

be quick, cause they will delete this comment soon.

**Comment by loge99** [comment]
If you can only see this comment and no link to the alternative, then they deleted the link once again.

**Comment by manwithpowers** [comment]
With the announcement that SOFORT is being deprecated at the end of 2023, Stripe's recommend solution is to implement Klarna but that's not possible for those of us relying on the WooCommerce Stripe Gateway yet. Is there any chance Klarna support can be given higher priority now?

**Comment by a-danae** [comment]
Hey hey 👋 Update over here. 

We're adding Klarna through the PaymentMethod API. Sources (or the Legacy checkout experience) will be deprecated. We're only integrating Klarna for the Updated checkout experience. 

Closing this issue in favor of this other one, but please feel free to open it again if further discussion is needed: 
- https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3043

**Comment by manwithpowers** [comment]
Thanks for your message. I am currently out of the office for the day.
My office hours:
Monday, Wednesday, Thursday: 9am - 3:30pm
Tuesday and Friday: 9am - 4pm
