### ISSUE TITLE
Apple Pay Support for Composite products

### ISSUE THREAD

**Issue by spraveenitpro** [woocommerce/woocommerce-gateway-stripe#532]
#### Affected ticket(s)

953377-zen

#### What I expected

I expected to see the `Payment Request Buttons` on the Composite product page just like they appear on the Simple product page.

#### What happened instead

The `Payment Request Buttons` appear on the simple product page but not on the Composite product page.

#### Steps to reproduce the issue

1. Activate Stripe along with enabling `Payment Request Buttons`.
2. Visit the composite product page and you will notice that there are no `Payment Request Buttons` which appear on the simple product pages like this: ![](http://cld.wthms.co/Z1Kt3T+)
[Direct Link](http://cld.wthms.co/Z1Kt3T+)

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by franticpsyx** [comment]
Had a look at this earlier and it seems that Stripe relies on adding the viewed product to the cart via JS to make that button work.

This isn't limited to Composite Products but potentially all product types with custom fields and plugins/extensions that add configurable fields, as well.

To support any product that includes configurable/custom fields, it will be necessary to collect and post all form inputs, so that custom product-type code can pick them up and validate correctly.

Ideally there should be some sort of error handling (maybe it's already included) to ensure that: 

* any core validation hooks are triggered before the product is added to the cart and 
* a message is displayed to the user when validation fails.

**Comment by roykho** [comment]
Closed in favor of https://github.com/woocommerce/woocommerce-gateway-stripe/issues/566
