### ISSUE TITLE
Checkout: "Sorry, your session has expired." if product is added to empty cart on checkout page

### ISSUE THREAD

**Issue by PureMango** [woocommerce/woocommerce-gateway-stripe#551]
#### What I expected

I expected that item will be just added to cart and checkout page will work as usual.

#### What happened instead

Instead the checkout page has loaded up and all the checkout fields were removed and the message "Sorry, your session has expired. Return to shop" was shown instead.

<img width="916" alt="2018-02-20 16 55 09" src="https://user-images.githubusercontent.com/3281210/36420371-fb19db60-165e-11e8-8f08-bd77b1dea842.png">

#### Steps to reproduce the issue

Make sure you have this plugin 4.0+ and latest WooCommerce. Open the incognito window and go to http://your-test-store.com/checkout/?add-to-cart=1234

It happens only if "Payment Request Buttons" option is enabled in the gateway settings.

The same happens if you have the code, that adds the item to the cart via Plugin API, when the checkout page is visited. Using WC()->cart->add_to_cart().

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Thanks for reporting. Unfortunately I am not sure if there is a way around this when using Payment Request Buttons because it requires AJAX functions which in turn requires "nonces" for security and that needs a user session to be created on page load.

If you have any ideas, please let me know. Meanwhile I will poke around to find a solution.

**Comment by PureMango** [comment]
Roy, could you please explain a little bit more about how the "nonces" and user session creation on page load are affecting the process of adding the item to the cart on the first visit (probably when the session is empty or doesn't exist) ?

**Comment by roykho** [comment]
Sure so you can see the code involved in this here https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/payment-methods/class-wc-stripe-payment-request.php#L137-L149

That session is needed when using nonce. Because creating a nonce requires a user session to be connected with.

**Comment by PureMango** [comment]
and how does this interfere with WooCommerce Cart object?

**Comment by roykho** [comment]
Its not interfering with the cart object. It is interring with the session object. Because user session tracks what is added to the cart, what is currently in the cart..etc.

I don't currently know the exact details otherwise this would be fixed however some time needs to be put in to know what the best solution would be.

**Comment by BeecherNetworks** [comment]
I'm experiencing this problem too. Payment Request Buttons are disabled. Only happening on Stripe orders, about 5 a day.

![IMG_20200426_213046_251](https://user-images.githubusercontent.com/179583/80699319-ac335800-8ad3-11ea-8b0a-d363379f0eef.jpg)

**Comment by StefYuluma** [comment]
are there any updates yet? i have got the same problem...

**Comment by Olubayosam** [comment]
I just ran into the same issue

however, when I was making researches into this, 
I noticed that this is mostly caused when woo-commerce pages are cached, this messes with the session object.

try to clear caches both on the server side and on the browser side

**Comment by wdm-janis** [comment]
I can tell that problem exists. I have the same issues, but what I notice, is if I use pre-filled fields for checkout with autocomplete, then I got a session expired error, when I add all information manually, no errors. It is a very strange bug.

**Comment by dahamsta** [comment]
@wdm-janis when you say "autocomplete", do you mean for a user that's logged in, with the data pre-filled by WooCommerce? Or data filled in by browser autocomplete, or perhaps an extension like Bitwarden? And is this immediately, or after a period of time?

**Comment by noumanqamar450** [comment]
I have the same issues, after error message the order is placed, the user thinks the order is not placed after seeing the message, then the user again places the order... and two-time payment is deducted and place the order

**Comment by Ljuk67** [comment]
Same here - just started hapenning on an eshop that has been running on Woocommerce for years. Currently WC version 9.5.2.

No Cloudflare, no caching plugin is active. 
No Stripe payment.

Using Elementor, for the checkout too.
