### ISSUE TITLE
Apple Pay/payment request to support custom field/pricing extensions on single product page

### ISSUE THREAD

**Issue by roykho** [woocommerce/woocommerce-gateway-stripe#566]
- [ ] Composite Products (works in cart/checkout)

- [ ] Smart Coupons (works in cart/checkout)

- [ ] Product Bundles (works in cart/checkout)

- [ ] Subscriptions (works in cart/checkout)

- [ ] Bookings (works in cart/checkout)

- [ ] Product Addons (works in cart/checkout)

- [ ] Mix n Match (works in cart/checkout)

- [ ] Avatax

- [ ] Account Funds (works in cart/checkout)

**Comment by dougaitken** [comment]
Can we make this Payment Request rather than Apple Pay? Or are the two different?

**Comment by roykho** [comment]
@dougaitken not exactly the same as they each have different quirks but the opened enhancement means to add it to all payment request despite the name. That name was chosen only so other people who requested them know its in the same context. I have however updated the name with /payment request so it is more clear.

**Comment by javorszky** [comment]
Also let's add Account Funds to the list

**Comment by AJerm** [comment]
Is it possible to perhaps add an option to disable payment request/apple pay buttons from all the product pages, but leave it visible in the basket?

That way items can still be processed and added to the basket according to all custom field information, but then allow the user to complete the transaction using the enhanced checkout UI these buttons offer.

I have some Fields Factory fields that I need associated with the orders, which don't get picked up until the product is in the basket. I believe disabling it only for the product page could be a good workaround for many people for now.

**Comment by dougaitken** [comment]
Yea @AJerm, it is possible to hide using a filter - `https://docs.woocommerce.com/document/stripe/#section-21`  And yes, as shown in the checkboxes, it works with some extensions.

For example, when using the [Product Add-Ons](https://www.woocommerce.com/products/product-add-ons/) extension, the Payment Request button is hidden on Product Page.

**Comment by roykho** [comment]
So far in testing the above mentioned extensions compatibility with branch 4.1, I've found that out of the ones I've tested, they work as expected during the checkout phase. Although they don't work within the product detail page it is not a show stopper. Payment request button can always be disabled on the product detail page.

So this may not have as high of a priority as initially planned. For now, we'll take this off 4.1 release and address it further down the line.

**Comment by AJerm** [comment]
Thanks @dougaitken, the code snipped on that page worked.

What would be very useful is if that was a checkbox option in the setting. Further to that, it would be great if there was a field where you could search and select products and their ID's to create a list to either block or whitelist the payment request buttons for those items.

That way a shop owner could disable them for complex products that have custom fields that need completing and adding to the basket, but leave them enabled for simple products for quick, swift and easy checkout for those items. Therefore getting the best of both worlds.

**Comment by roykho** [comment]
@AJerm we could pass the `post` object via the filter that way you can pick and choose which product you want to hide/show. Will add to 4.1 release.

**Comment by AJerm** [comment]
Cool :)

**Comment by gabrielhuisg** [comment]
Regarding the above. I have a query by Order Delivery Date Pro Plugin Author with the below questions. 
Could you help me please? Thank you

The ‘wc_stripe_show_payment_request_on_checkout’ hook which you have provided is to display the Payment button on the checkout page. The same hook which we have already provided you earlier in one of our replies which is to add the Apply pay button on the checkout page.

Earlier you provided a WooCommerce ‘woocommerce_checkout_update_order_meta’ hook which is fired when the ‘Place order’ button is clicked. We wanted the same hook from ‘WooCommerce Stripe Gateway’ plugin which is called when ‘Apple Pay’ button is clicked.

So, please provide us this information so that we can add (pass) the delivery information ahead when ‘Apple pay’ button is clicked.

**Comment by spraveenitpro** [comment]
Hey @roykho Hope you are well, thought of checking with you on the above query from our customer. Thanks :)

**Comment by helgatheviking** [comment]
Maybe add Name Your Price to this list? I just received a ticket from a user about it and this screenshot: https://imgur.com/a/zV1DGJc

It sounds like that for now I should inform the user to disable payment request on the product page itself? And hopefully the total will work correctly in the cart? Is that correct, @roykho ?

**Comment by helgatheviking** [comment]
thanks @roykho ! so https://docs.woocommerce.com/document/stripe/#section-21 is how they'd disable it? is the individual product passed to that filter yet so it doesn't have to be universally applied? Could it happen automatically for NYP like it sounds like it does for add-ons?

**Comment by roykho** [comment]
@helgatheviking yes the `post` object is passed so you can selectively choose.

**Comment by gabrielhuisg** [comment]
@roykho 
Regarding the above. I have a query by Order Delivery Date Pro Plugin Author with the below questions.
Could you help me please? Thank you

The ‘wc_stripe_show_payment_request_on_checkout’ hook which you have provided is to display the Payment button on the checkout page. The same hook which we have already provided you earlier in one of our replies which is to add the Apply pay button on the checkout page.

Earlier you provided a WooCommerce ‘woocommerce_checkout_update_order_meta’ hook which is fired when the ‘Place order’ button is clicked. We wanted the same hook from ‘WooCommerce Stripe Gateway’ plugin which is called when ‘Apple Pay’ button is clicked.

So, please provide us this information so that we can add (pass) the delivery information ahead when ‘Apple pay’ button is clicked.

**Comment by laurendavissmith** [comment]
We need to move this discussion to the ideas board for further evaluation: http://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/34518661-apple-pay-payment-request-to-support-custom-field

**Comment by helgatheviking** [comment]
I'm sorry to see this closed. This git issue itself is already a compilation of other issues, which seems to suggest the need. Everyone who's contacted me concerning this is expecting it to work on the single product page the same way it does for core product types. I don't know anything about the request APIs so maybe there's a limitation there blocking this or maybe it's just a huge project that you can't get into. I understand both, but from my perspective the _need_ to work with some of the biggest plugins in the Marketplace seems clear.

**Comment by douglsmith** [comment]
I have to agree with @helgatheviking. We have an official Stripe gateway for WooCommerce and extensions sold through the official WooCommerce store that are not compatible. Well, it goes beyond incompatible because it can break a site with unexpected results that can erode customer trust.

This feels much more like a bug than some feature request to be discussed and voted on.

If it's going to be treated like a feature then perhaps payment request needs to automatically get turned off if certain plugins are installed and a warning placed in the UI so unsuspecting store owners aren't caught by surprise with angry customers. And maybe the settings for where payment request shows up should be more granular so a typical store owner can control it. The sell pages for the incompatible extensions should probably have a warning on them too.

**Comment by laurendavissmith** [comment]
@helgatheviking @douglsmith The closing of this issue does not express the intent for us to not do the work for this one. We are in the process of cleaning up our enhancement issues which currently come at us from all directions and trying to centralize them into the ideas board so that we can gauge what the community is interested in. 

Once we're ready to begin work we'll reopen or open a new issue in the repo so that way enhancements that are logged in GitHub are ones that have active development on them and don't become stale.

That being said please feel free to vote up and comment on those idea board issues as we'll be actively looking at those going forward to keep driving the product decisions. I can't speak to the timing on this one but it's definitely not off of our radar.

**Comment by gabrielhuisg** [comment]
@laurendavissmith You should not close this. Instead I believe you could still leave it open while you can still centralise all the ideas internally. 

It's been more than few months and there are still no actions taken on the things that we have mentioned here. And now you are still saying that you guys would be working on those issues that we have raised . So what are you talking about. Could you guys simply take more actions instead of merely saying that you are going to take actions. No actions were taken after soooo many months since the start of this conversation

**Comment by douglsmith** [comment]
> We are in the process of cleaning up our enhancement issues

@laurendavissmith, @roykho, I don't suppose I could convince you to just remove the `[Type] Enhancement` label and add a `[Type] Bug` label instead? ;-)

BTW, I have tremendous respect for you all and really appreciate the great work you do! I just happen to disagree with the classification of this issue.

**Comment by laurendavissmith** [comment]
@douglsmith I'll definitely bring it up with the team and see where the discussion take us, I've added it to my todo list for our next team meeting

**Comment by dcx15** [comment]
It seems kind of crazy to me that this is still an ongoing issue, unless I am missing something. Hopefully this can be addressed soon.
