### ISSUE TITLE
New checkout flow for Stripe Checkout Popup Modal

### ISSUE THREAD

**Issue by roykho** [woocommerce/woocommerce-gateway-stripe#578]
As we have experienced that when using Stripe Checkout ( popup modal ), the checkout form does not get validated before it shows the popup. This could lead to poor UX because customer may get confused that their payment has already been taken..etc. We have tried to remedy this in the past by doing pre-validation prior to the popup however we quickly realize this has negative side effects on stores with custom checkout fields. So this validation was rolled back and we've add hooks for others to use if they so choose to custom add their own validation in.

So one proposal we have is to change the checkout flow when Stripe Checkout is used. This entails having the customer click on the normal place order button which then validates all the fields as normal and then it gets redirected to a summary order page with a pay button. This button then shows the popup. This allows for the validation to happen prior to them reaching the popup.

Ref discussions on #446, #161, #576

**Comment by joe-westcott** [comment]
Nice idea, @roykho !

Excuse me if this is obvious -- why isn't it possible to do the regular validation while also keeping the visitor on the same page, instead of loading a second page?

I see you noted that "pre-validation" was problematic with custom fields, but it's unclear why your pre-validation checks couldn't be expanded to handle all of the steps in regular validation, before showing the payment button.

I ask because customers drop off with every page that loads, so adding an extra page load could significantly affects sales and donations.

...

I know you know this, but for the record, with Stripe Checkout, you can offload validation for address fields. I mention it because this issues has issue #572 tagged, which related to collecting addresses in Stripe Checkout.

**Comment by joe-westcott** [comment]
For the sake of contradicting myself (ha), there could be a use case where someone validates addresses before payment, such as ensuring that the customer is located in a certain state, for example.

In this case, WooCommerce would need to validate the address, rather than relying on Stripe for it. The problem with Stripe Checkout is that the customer would need to enter the address twice, as @roykho and I have noted elsewhere.

But let's consider a case where:

1. The site owner sells to residents of a certain state, or they have other custom validation they need to perform.
2. The site owner wants to use Stripe Checkout, such as if they use Stripe Radar rules to prevent fraud, such as issue #572 .
3. Asking customers to enter their address information twice can annoy customers and cause some to drop off, which is a current problem when we combine Stripe Checkout and the Stripe Payment Gateway for WooCommerce.
4. Loading more pages may cause some customers to drop off, while they wait for another page to load.

I'm not sure what the solution would be in this case. At least not yet.

**Comment by roykho** [comment]
> why isn't it possible to do the regular validation while also keeping the visitor on the same page, instead of loading a second page?

Please read the comments here https://github.com/woocommerce/woocommerce-gateway-stripe/issues/576

The easy solution for all 4 cases is don't use Stripe Checkout. :) The inline embedded form works just fine and is actually the newer technology going forward in additionally it does Radar verification. 

This topic is mainly to satisfy the ones that are adamant on using Stripe Checkout.

**Comment by Babelfisch** [comment]
Why do you not do it like the on the YITH WooCommerce Stripe plugin? With Stripe Checkout, the payment button is shown on the thank you page, and thereby the order is fully validated.

This works great, is legally safe and easy for the customer.

**Comment by Babelfisch** [comment]
However, this is still better than having to enter the same data several times. At this time, the user enters credit card data and if the form is doesn't validates (in German shop several checkboxes must be checked), there is an error and he has to enter all cc data again. This causes order abandons and frustrated customers.

**Comment by roykho** [comment]
@Babelfisch perhaps you misunderstood me. Please read my original idea. It is same concept as YITH is what I am saying we may do.

**Comment by Babelfisch** [comment]
Ok, sorry. Hope you can implement this because I like the Stripe Checkout.

**Comment by roykho** [comment]
Another idea has come up. Perhaps we could store the source token with the order after the customer has entered the payment successfully. That way if there indeed is anything wrong with the checkout form, the customer can fix it and the second time they click on "Place Order", it would just used the previously saved source token without having to see the popup again. Thus eliminating the thought of having been charged twice.

**Comment by roykho** [comment]
New flow added in 4.1 branch

**Comment by jobthomas** [comment]
Hey @roykho, just a comment from a chat I had with a customer. 

While they understand the rationale behind it, it does add an extra step for the customer and that may even be more confusing (or bad UI) than having wrong details in there. Would there be other solutions that still use Stripe Checkout (for PCI compliance reasons) but not have that step in between?

**Comment by jobthomas** [comment]
Another customer with the same question: 1088414-zen

**Comment by roykho** [comment]
@jobthomas there is no way around this at this time.

**Comment by fariazz** [comment]
Is there a plan to bring those nice Elements into the Woocommerce theme? Adding that extra step to the modal workflow reduced our site sales significantly (we sell digital products - don't care or capture customer details to validate), and we had to disable Stripe altogether as the default inline form looked terrible.
