### ISSUE TITLE
[4.1 Beta-1] EPS allows payment outside of Austria

### ISSUE THREAD

**Issue by hannahswain** [woocommerce/woocommerce-gateway-stripe#589]
The EPS description states: `Relevant Payer Geography: Austria`

However, I could both see the payment option and do a test checkout with it when my location was not set to Austria. 

![Checkout](http://cld.wthms.co/IdIQUA+)

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Same with the Multibanco question. It relates to the currency. Stripe as always worked this way FYI.

**Comment by thorsten-stripe** [comment]
@roykho it might be worth looking into only surfacing the payment methods if a certain billing country is selected. E.g. map the payment methods to the relevant payer geography country list in the guide[0], or maybe have a country list in the settings of each method, where merchants can choose for which billing country they want to support a certain method.

Because otherwise the list of payment method becomes pretty long on the checkout page, especially for merchants selling globally. What do you think? 

[0] https://stripe.com/payments/payment-methods-guide

**Comment by roykho** [comment]
@thorsten-stripe yes we've discussed this before many years ago however never took any action because there are lots of cases to consider with this approach which I will not go into detail here however we may revisit this sometime in the future perhaps version 4.2.
