### ISSUE TITLE
Unnecessary extra step "Place order" before displaying Stripe modal

### ISSUE THREAD

**Issue by robman87** [woocommerce/woocommerce-gateway-stripe#613]
#### What I expected

On checkout page I expect to

1. Select credit card 
2. Click on "Pay/Proceed" 
3. Stripe modal to be displayed
![checkout-page-v4 0 7](https://user-images.githubusercontent.com/5516214/38924176-82d378d0-42fc-11e8-87d1-9e6bd69053f5.png)
4. Insert credit card details
5. Press "Pay $##"
6. Payment complete page.

#### What happened instead

On checkout page

1. Select credit card 
2. Click on "Pay/Proceed" 
3. Redirected to "order-pay" page
![extra-step-to-place-order](https://user-images.githubusercontent.com/5516214/38924474-5630bfd0-42fd-11e8-9e35-9cef4a4f9300.png)
4. Click "Place order" button
6. Stripe modal displays with an extra email field on "order-pay" page
![new-stripe-modal-with-email](https://user-images.githubusercontent.com/5516214/38923916-e725f2b4-42fb-11e8-9adf-475ea66a32a8.png)
7. Insert credit card details + email
8. Press "Pay $##"
9. Payment complete page.

This is adding several extra steps to the checkout process that will lead to lost sales and lower conversion rate from visitor to customer.

Is this behaviour intentional part of the upgrade?
How can the behaviour be reverted to the previous way?

#### Steps to reproduce the issue

Upgrade to v4.1.0 or 4.1.1 of stripe gateway.
Latest WordPress v4.9.5, WooCommerce v3.3.5, WooCommerce Subscriptions v2.2.19.
-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
By design.

**Comment by quickandeasyce** [comment]
I'll add as well that I'm not impressed by the support team or your own response to this issue on the wordpress.org forums. It's felt very hand-wavy as if the problem is the customer...

This issue is a real concern for smaller sites. People are used to seeing the Stripe modal and if you're running a small site people are more willing to trust stripe with their info than some random website. The modal is reassurance for those folks. 

So those of us running small sites are left to either customize our themes to incorporate the additional screen WOO added or to do the payment inline and potentially lose customers.
