### ISSUE TITLE
Unclear error message when email address not completely filled in

### ISSUE THREAD

**Issue by yukikatayama** [woocommerce/woocommerce-gateway-stripe#686]
#### Affected ticket(s)

1205205-zen
1719823-zen
2116284-zen

#### What I expected

1. Add product to cart and fill in billing info
2. In email field instead of `test@test.com`, only type in `test`
3. Checkout with Stripe
4. Error message that billing email is invalid should show

#### What happened instead
Instead of invalid email address error message, it says `Unable to process this payment, please try again or use alternative method.` Making it seem like it's an issue with payment itself.

#### Steps to reproduce the issue
Stripe 4.1.7
WC 3.4.2

1. Test with Storefront and Twenty Seventeen and in email field don't type in a full email address, i.e. `test`
2. Finish checkout
3. Unclear error message shows
4. Testing with COD for example does show error message at the top the billing email is invalid.

When testing with Storefront, there is an indication that email field is incorrect:
![](http://cld.wthms.co/tW7TPh+)
Link to screenshot: http://cld.wthms.co/tW7TPh

But, with other themes, such as this user's (and even in Twenty Seventeen looks like), they do not have that indication so customers only rely on error message coming from Stripe:

![](http://cld.wthms.co/9Xdu96+)
Link to screenshot: http://cld.wthms.co/9Xdu96

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by madeincosmos** [comment]
Also reported in 1719823-zen

**Comment by emyeele** [comment]
I am having the same issue! I would like the error to actually tell the user what the issue is instead of having them abandon their cart because of it.

**Comment by Ulprus** [comment]
I found this error yesterday and it's extremely frustrating. How this is low-priority is quite beyond me, but I sincerely hope it gets fixed soon.

**Comment by dougaitken** [comment]
This may not entirely be due to an email address being incorrect. 

That error message has been in numerous forum posts:

https://wordpress.org/support/topic/unable-to-process-this-payment-please-try-again-or-use-alternative-method-6
https://wordpress.org/support/topic/unable-to-process-this-payment-please-try-again-or-use-alternative-method-5/
https://wordpress.org/support/topic/unable-to-process-this-payment-please-try-again-or-use-alternative-method-7/
https://wordpress.org/support/topic/unable-to-process-this-payment-please-try-again/
https://wordpress.org/support/topic/unable-to-process-this-payment-please-try-again-or-use-alternative-method-4/

That error message appears twice in the whole extension code:
https://github.com/woocommerce/woocommerce-gateway-stripe/blob/6e325714b8026b35f2747890bf1d573fc1371d56/includes/class-wc-stripe-order-handler.php#L95
https://github.com/woocommerce/woocommerce-gateway-stripe/blob/6e325714b8026b35f2747890bf1d573fc1371d56/includes/class-wc-stripe-helper.php#L224
https://wordpress.org/support/topic/unable-to-process-this-payment-please-try-again-or-use-alternative-method-2/

Along with incorrectly formatted email addresses, we've seen it throw this error due to API keys needing to be rolled.
Or it will work in test mode but not live mode.

**Comment by bor0** [comment]
@roykho pinging you as you're most familiar with Stripe. It seems that `$source_info->error` is empty since it reached https://github.com/woocommerce/woocommerce-gateway-stripe/blob/6e325714b8026b35f2747890bf1d573fc1371d56/includes/class-wc-stripe-order-handler.php#L95. I don't think there's a way for us to log any additional errors because Stripe isn't sending them?

**Comment by dougaitken** [comment]
> I don't think there's a way for us to log any additional errors because Stripe isn't sending them?

The scenario which kicked off this discussion is when text is in the email address field that doesn't match the format for an email address. That is WooCommerce core so is this a core issue or something we can address in the Stripe extension?

**Comment by orhanfernandes** [comment]
Also reported on 2196284-zen

**Comment by budzanowski** [comment]
@yukikatayama or @dougaitken or @madeincosmos or anyone - could you please check $953?

**Comment by dougaitken** [comment]
@budzanowski do you still need a check on #953 / the current 4.2.4 branch?

**Comment by budzanowski** [comment]
@dougaitken nah it should be alright :)
