### ISSUE TITLE
Subscriptions: "Change Payment" Updated Card Not Used For manuell Renewals 

### ISSUE THREAD

**Issue by FitMo90** [woocommerce/woocommerce-gateway-stripe#728]
Maybe Same Problem like here:
#281 and #722 

1. scenario:
- active subscription. Payment for renewal-order failed because of a problem with the creditcard. For example declined.
- We let the customer know about it. 
- Customer will add a new payment source (new Creditcard) in his account. Steps to add a new creditcard: Customer goes to his account, adds a new payment. Select the button, that this should be used for future payments. confirmation.
- after it we "retry renewal payment" for the failed order in order actions on the admin-order-detailpage.
- Payment fails again. The process tries to renewal the payment again with the old creditcard/source. Not the new one. But the new one is added as source in Stripe.

2. Scenario:
- Customer added a new payment source
- We create in the subscription-Detail-Page a manuell renewal
- payment failed, because it tries to renewal the payment again with the old creditcard/source. Not the new one. But the new one is added as source in Stripe.

For both scenarios, future automatic payment will use the new creditcard. Only for manuell or existing orders not.

**Comment by roykho** [comment]
@FitMo90 
> Customer goes to his account, adds a new payment.

I believe they should of instead went to the subscriptions and click "Change Payment" on existing subscriptions order.

**Comment by gerdneuman** [comment]
> I believe they should of instead went to the subscriptions and click "Change Payment" on existing subscriptions order.

@roykho Technically, this is true. But the "Add payment" is very prominent on the 1st level of *My Account* so usually a user just logs in and then changes things there (not knowing that this is just for all furture "normal" orders and not the existing subscription). Same when a user tries to change the address of a subscription. 

I've seen this too extremely often. Subject experience is that at least half our subscription users do it wrong here. At the moment we even do not advocate changes on subscription by users themselves due to this one thing -- but we ask them to write us a mail instead. (Still lots of work, but less confusion/aftermaths of things going unintended from a users POV).

This is not a woocommerce-stripe bug, but a usuability by woocommerce-subscriptions that could be better. For instance, when changing address or adding payment method *and* having an active subscription at the same time, then there should be a banner "You really want to change your global address? Want to change your subscription instead? <link>Go to subscription</link>" (same for payment).

Pinging @thenbrent so he's aware of this subscription issue.

**Comment by neilgee** [comment]
> I believe they should of instead went to the subscriptions and click "Change Payment" on existing subscriptions order.

I also find that customers get stumped **where** to change the payment details and go to 'Payment methods' as a first port of call rather then 'My Subscriptions'.

So in doing so inadvertently, any previous failed orders will use the old failed Card details.

Is it possible to change the older failed subscription to the new card via the admin backend?

**Comment by roykho** [comment]
Unfortunately this is not something we can handle with this plugin. We can't assume adding a payment method via My Account->Add payment to replace one or all current active subscriptions.

This has to be done within Subscriptions however I believe Prospress and myself have talked about this in the past and it is not as easy as it seems to do.

**Comment by gerdneuman** [comment]
> We can't assume adding a payment method via My Account->Add payment to replace one or all current active subscriptions.

We looked into this issue again today in order to somehow mitigate the problem. I was wrong when referring to the global address change:

> Same when a user tries to change the address of a subscription.

In fact, when a user changes the billing or shipping address then there is a checkbox:

`[x] Update the Shipping Address used for all of my active subscriptions (optional)`

![image](https://user-images.githubusercontent.com/12525563/45915911-9ec8dd00-be5d-11e8-8563-a250bc76fd31.png)

This only shows when the user actually has an active subscription. I think this is very good UX actually.

The same UX should be done when the payment method is changed/added. That is a checkbox like:

`[x] Update the Payment Method used for all of my active subscriptions (optional)`

@roykho Could you reopen this bug? 

I think it would be within the responsibility of the WooCommerce Stripe plugin to add such a checkbox and implement the updating of all active subscriptions to the newly added payment method.

(I guess this all would not work for paypal based subscriptions where you cannot persist/store a payment method, but for Stripe I think this should all be feasible technically.)

**Comment by roykho** [comment]
@gerdneuman - I've added a checkbox to update all subs during add payment method. If you don't mind, please have a test on this branch https://github.com/woocommerce/woocommerce-gateway-stripe/tree/fix/issue-728

**Comment by gerdneuman** [comment]
Thank you! Just quick feedback: It's nice that there's a filter `apply_filters( 'wc_stripe_display_update_subs_payment_method_card_checkbox', true )` but for consistency it should be `false` by default because it is also `false` by default for the address changes as done by WC Subsciptions.

I'd surely change this to `true` (which would be the better default imho) but since upstream WC Subscriptions made its decision here, it's probably best to use the same default.

**Comment by roykho** [comment]
@gerdneuman thanks for the feedback, I've changed that to false by default and everything has been merged to the master branch now. By chance did you test it to see if it worked? Another words did adding a payment method actually changed all active subs?

**Comment by gerdneuman** [comment]
No, I haven't tested yet because testing subscriptions on a staging server is pretty complex. (Stripe itself makes it complex too). So even if I tested, it might fail as well just because I am in a staging env (internal network). So well, besides having not much time, I cannot do much. Once the release is out, I'll test asap on our live server. Sorry, I cannot do more atm.

**Comment by kevinbrown041** [comment]
The problem is still not fixed.
New credit cards are not associated with previously failed subscriptions even with the Checkbox ticked to Update the Payment Method used for all of my active subscriptions (optional)

Any news on this?
