### ISSUE TITLE
Stripe can't capture charge for authorized orders after partial refund

### ISSUE THREAD

**Issue by treibalen** [woocommerce/woocommerce-gateway-stripe#757]
#### Affected ticket(s)

1561572-zen
3411693-zen
3146888-zen
7217834-hc
19466492-hc

#### What I expected

When store owner receives On-hold order made via authorized (not captured) Stripe payment, they can refund it partially and then capture the rest amount.

#### What happened instead

When order is On-hold, you can issue a partial refund, but then when changing order status to Processing to capture payment, Stripe is unable to charge customer anymore.

#### Steps to reproduce the issue

Stripe settings: 

![Screenshot](https://d.pr/ZXomSD+)
Screenshot link: https://d.pr/ZXomSD

1) Place a test order paid with Stripe, it's On-hold now.
2) Refund the order partially via Stripe:

![Screenshot](https://d.pr/kTKlKB+)
Screenshot link: https://d.pr/kTKlKB

3) Change order status from On-hold to Processing. You'll see the error in notes:

![Screenshot](https://d.pr/3iCPOd+)
Screenshot link: https://d.pr/3iCPOd

I understand that the _correct_ way of doing this would be to edit On-hold order like this:

![Screenshot](https://d.pr/Xbl8U4+)
Screenshot link: https://d.pr/Xbl8U4

However, from the Edit Order page it's not explicitly clear that by issuing a partial refund, they won't be able to capture a charge anymore.

Setting the priority to high because with this case store owner will need users to pay again.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by treibalen** [comment]
Also, this is somehow similar, but in my case nothing is done via Stripe dashboard - https://github.com/woocommerce/woocommerce-gateway-stripe/issues/738

I also tested it with master branch just in case - the same error.

**Comment by dphyled** [comment]
I had a chat with a store owner who was very confused by this (7217834-hc)

I understand that refunds are meant to be returning money that has already changed hands, so refunding an authorization doesn't really make sense since no money has been transferred yet.

However, I also understand how having the refund button there could be confusing for shop owners (it would probably be the first place they go to "return" money to customers), and most would probably not assume that going through the refund process would result in the entire order being cancelled instead of just the smaller portion they were trying to refund.

Would it be possible to disable the Stripe refund button if the order has only been Authorized? Or add a note that a partial refund would cancel/release the authorization?

Also, when I was testing, from the WooCommerce Orders page, the only indication that anything is out of the ordinary is the "Pre-Authorization Released" note. Nothing changed to "Failed", and it appears it just refunded the $10, rather than cancelling the whole $550:

![Screenshot](https://cld.wthms.co/jOvcNj+)
Screenshot direct link: https://cld.wthms.co/jOvcNj

The user only realized they were missing money after they logged into Stripe and saw that the order had been cancelled.

**Comment by phillipcornwell** [comment]
I am unsure if what I see in 19466492-hc and 3146888-zen is related to this or not. If not, I'll open a new issue. When set to Authorize order and it uses either coupons or add-ons, Stripe is only capturing the lower price and either fails coupon orders or doesn't charge for the add-ons. The users Capture orders by updating the Order Status from On-Hold to Processing. 

When updated to "Processing" a coupon is order fails because it tries to capture the full order amount, disregarding the coupon. Since the store is asking for more than the authorized amount, it fails. When there are add-ons, the price captured is the order total minus the cost of the add-ons. That cost is then "refunded" back before capturing the lower amount, without the cost of any add-ons.

I can see it's been about a year since this was opened so trying to get clarification.

**Comment by johndcoy** [comment]
3411693-zen

**Comment by lindamork** [comment]
3520787-zen

**Comment by aheckler** [comment]
3710348-zen is this, I think.
