### ISSUE TITLE
No warning when saving test keys in live mode, leading to errors at the checkout

### ISSUE THREAD

**Issue by madeincosmos** [woocommerce/woocommerce-gateway-stripe#773]
#### Affected ticket(s)
1707884-zen

#### What I expected
If I accidentally add test keys in live mode, the plugin should detect they are incorrect and ask me to update them.

#### What happened instead
When disabling test mode in plugin settings, I can paste test keys in the Live Publishable Key and Live Secret Key fields and save them without any warning that something is wrong. 

The credit card form in no way indicates that it's working in test mode, and if then I enter a real credit card at the checkout I only get a generic error message saying your card is declined:

![Screenshot](http://cld.wthms.co/zwG0PD+)
Screenshot: http://cld.wthms.co/zwG0PD

In Stripe logs I can see the following error:

```
            [message] => Your card was declined. Your request was in test mode, but used a non test (live) card. For a list of valid test cards, visit: https://stripe.com/docs/testing.
            [type] => card_error
```

When I enter a test credit card number (i.e. 4242...4242), I can complete the order even though the plugin supposedly is working in live mode.

#### Steps to reproduce the issue
1. Disable test mode in plugin settings,
2. Save test keys in Live Publishable Key and Live Secret Key,
3. Proceed to checkout and try to complete the order with a real credit card,
4. Try to complete the order with a test credit card

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by reykjalin** [comment]
When I add test keys in the live mode fields I get this error in wp-admin:

<img width="1044" alt="Screenshot 2019-07-23 at 19 25 17" src="https://user-images.githubusercontent.com/13835680/61741269-06063500-ad80-11e9-9c82-243c1ab74a88.png">

This error message seems to have been in the plugin for about 10 months, although I'm not sure exactly if it's been in a _release_ for 10 months.

@madeincosmos do you remember if this was the case when you were testing for 1707884-zen?

I can still save the test keys as live keys, and that's something we may want to change since we can effectively tell when the test keys are used as live keys. @marcinbot any thoughts on whether we should add stricter error handling?

**Comment by v18** [comment]
I'm closing this issue as fixed. I'm not able to save test keys in live mode. I get this error and the keys are not saved:

<img width="571" alt="Screen Shot 2021-02-20 at 2 35 53 PM" src="https://user-images.githubusercontent.com/11487924/108585005-06feae80-7389-11eb-94a4-b71b8ce1fc26.png">
