### ISSUE TITLE
Stripe API failure breaks payment methods form

### ISSUE THREAD

**Issue by smazur** [woocommerce/woocommerce-gateway-stripe#776]
Stripe API failure breaks payment methods form and ugly error displayed.

#### What I expected

To see nice error message when Stripe API request fails when rendering payment method fields.

#### What happened instead

User sees message like following:

> WP_Error Object([errors] => Array([http_request_failed]=>....

#### Steps to reproduce the issue

1. Emulate Stripe API failure.
2. With active and configured stripe plugin go to checkout and you will see the issue.

**Comment by smazur** [comment]
Need to properly handle exceptions in WC_Gateway_Stripe::payment_fields() and print nice looking error message, like:

> There was a problem connecting to the Stripe API endpoint.

**Comment by thenbrent** [comment]
Closing this one due to lack of recent activity. While it is very true a better error message could be used, in those black swan events where the Stripe API goes down, there are far bigger issues than the error message. That said, as we look to move the default experience to the Payment Elements / UPE, we can factor in better exception handling for that case.
