### ISSUE TITLE
'api' is not sent in 'woocommerce_stripe_request_headers' filter (Enhancement)

### ISSUE THREAD

**Issue by sumudumathew** [woocommerce/woocommerce-gateway-stripe#800]
#### What I expected
Because the Woocommerce Stripe Gateway doesn't implement Stripe Connect, we have implemented our own. However the implementation proved more difficult because the 'woocommerce_stripe_request_headers' filter does not send the 'api' (e.g.: charges, refunds), for us to selectively modify the headers (i.e.: add the Stripe-Account header). However the 'api' is being sent in the 'woocommerce_stripe_request_body' filter.

Would it be possible to please request an enhancement to add the 'api' info to the 'woocommerce_stripe_request_headers' filter ?

#### What happened instead
Not applicable

#### Steps to reproduce the issue
Not applicable

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by thenbrent** [comment]
Closing this one due to lack of recent activity. While it is valid gap, it's not been a priority in the last 4 years, and unlikely to become one soon. To see it become a priority, please create a feature request: https://woocommerce.com/feature-requests/stripe/ 

If it proves popular enough, we may consider it for the roadmap.
