### ISSUE TITLE
Feature: Allow Test Mode via WP-Config, Hook, Global Variable

### ISSUE THREAD

**Issue by koconder** [woocommerce/woocommerce-gateway-stripe#801]
Currently testmode is defined in the settings and cant be set outside of the admin panel "dynamically".

#### What I expected

Something like a define statement which can be used for a number of developers and 3rd party plugins to automatically force the plugin into test mode, this is great for developers that use the same codebase and sometimes test on live production DB but with locally mapped install like dev.xxxx

My setup is many domains mapped to a single WP install, but having the option of something such as this would be very ideal:

`define( 'WC_STRIPE_TESTMODE', true );`

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by koconder** [comment]
Bump

**Comment by agenceKanvas** [comment]
That would be awesome ! Could prevent some errors on dev ...

**Comment by thenbrent** [comment]
Closing this one due to lack of activity. While it's a valid request that could be helpful, it's not been a priority the last 4 years, and unlikely to be anytime soon.

> cant be set outside of the admin panel "dynamically".

While not as clean as a `WC_STRIPE_TESTMODE` constant, I believe it will be possible to set test mode dynamically already using low level WP filters, like attaching a callback to `'option_woocommerce_stripe_settings'` that overrides the `'testmode'` value to be `'yes'` under certain conditions.
