### ISSUE TITLE
Outdated API

### ISSUE THREAD

**Issue by gilesholder** [woocommerce/woocommerce-gateway-stripe#811]
The gateway seems to be utilising the 2018-09-24 version of the API when the latest is 2019-02-19.

My system is showing 96% use for the old version and 4% for the newer.

**Comment by grigorijurasov** [comment]
You've mentioned that Stripe for WooCommerce is utilizing 2018-09-24 version when the latest version is 2019-02-19. 

This has been addressed in the latest Stripe release and now 2019-02-19 version is utilized.

There was a release on 2019-03-14 on the Stripe side but looking at [Stripe changelog](https://stripe.com/docs/upgrades) I see that this only concerns the native subscriptions on Stripe side which aren't used by our plugin and `application_fee` parameter which is also not used. The `application_fee` parameter was renamed to `application_fee_amount`.

Therefore the lack of an update to 2019-03-14 version on our side should not affect the functionality of [Stripe](https://woocommerce.com/products/stripe/) plugin, although it would be great if someone could double-check this.

Adding High priority label so this could be double-checked quicker since it will most likely not require a lot of time to check whether the new release on Stripe side could potentially have a negative effect.

**Comment by dougaitken** [comment]
#834 fixes this

**Comment by dechov** [comment]
As mentioned by @grigorijurasov, the version was updated to 2019-02-19 in the 4.1.15 release, and the more recent version update doesn't affect this extension.
