### ISSUE TITLE
Add option or filter to disable CVV Field

### ISSUE THREAD

**Issue by njeffers** [woocommerce/woocommerce-gateway-stripe#812]
Using the latest WP, WC, and Stripe plugins.

I technically prefer to have CVV in use due to fraud protection, although some customers have requested to remove it. I would tell them that it's not an option, except that Stripe specifically allows you to add a customer with just their Card # and Expiration date through their admin panel. I was able to get this process to working pretty easily by doing the following:

1) Disable "Block if CVC verification fails" under Radar Rules - https://dashboard.stripe.com/radar/rules
2) Simply remove the div for #stripe-cvc-element in class-wc-gateway-stripe.php
3) Order went through without a hitch, and confirmed that it's processed successfully on Stripe.

Now, editing the plugin file directly makes me feel scummy. I'm not sure how this method would work for the inline CC Form, but maybe a simple filter for the "standard form" would be an option? I also know that there's probably some semi-broken JS due to this field no longer existing, although on my end, it doesn't cause any breakage. A tweak there may be needed as well?

**Comment by rachidbigm** [comment]
I think that hide CVV will increase the risk to frustrating users who enter an incorrect number is the big issue and increase more drop-off...

**Comment by njeffers** [comment]
Hi @rachidbigm,

I think you may have misunderstood what I'm saying. if anything, it's one less field to fill out, which should make it less frustrating.

Oddly enough, the woocommerce docs for Stripe even show a version without CVV, although it looks like they changed this in the plug-in.

**Comment by JoelStickney** [comment]
I agree with this completely, having to directly edit the plugin to bypass the CVV check is silly.

**Comment by dougaitken** [comment]
> Oddly enough, the woocommerce docs for Stripe even show a version without CVV, although it looks like they changed this in the plug-in.

You're right @njeffers - this has been updated in the past year but this previous version asked for a CVV when the card details were entered.

I'd love to have some context about _why_ the CVV field should be disabled from your clients, what online card payments are able to be processed without a CVV being entered?

You can also ensure you're giving the correct message to the customer. Using a Stripe test card ending `0127` - and using that will give you the error `The card's security code is incorrect.`.

**Comment by njeffers** [comment]
@dougaitken - thanks for the clarification on the old screenshot. 

As for why - for the most part, I agree that the CVV is better for preventing fraud (or so I've read). I can't fully remember the particulars of why the last customer requested this, although stripe does allow it. See my notes above about Radar, and how to disable CVV verification.

A little context - needed to migrate from an ancient unknown platform to WP + WC + Woocommerce Subscriptions. Some customers are recurring, and some are manual subscription renewals. I believe the issue may have come down to exporting from another payment gateway to Stripe. I don't believe the credit cards had CVV/CVC with them. I was able to import them into stripe, then import each customer's tokens (customer and card) into their WordPress user info. Something happened here, and we basically had to use User Switcher to act on behalf of the customer to access the front end and process their next payment. Problem is, we don't have their CVV. Telling thousands of recurring users to walk through these steps to get their account back in sync is an idea that's dead in the water.

This is a one-off scenario, but in general, I feel like less fields is better from a conversion standpoint. I told the customer that it can't be done without the CVV (which would make sense), but he pointed out that Stripe allows it, so why can't my site? For that reason, I feel like it should follow Stripe's requirements/rules. Even if only temporarily to help get people transitioned from an old system. This might be why Stripe allows you to skip CVV the first place - they know other processors might not provide the CVV.

I'm not quite sure what you mean by the last sentence.

**Comment by dougaitken** [comment]
HI @njeffers 

> I'm not quite sure what you mean by the last sentence.

I meant that you can test Stripe using a test card which will return an error replicating an incorrect CVV - this might not be helpful for you scenario.

> This is a one-off scenario, but in general, I feel like less fields is better from a conversion standpoint. 

Personally, I have never come across an eCommerce site where the CVV wasn't needed at some point in the transaction flow. This could be UK specific and lack of CVV may be US centric?

> I told the customer that it can't be done without the CVV (which would make sense), but he pointed out that Stripe allows it, so why can't my site? For that reason, I feel like the plug-in should follow Stripe's requirements/rules. 

This wouldn't be a requirement unless I've missed something. This plugin/extension uses Stripe Elements so that whole payment card area is served via JavaScript directly from Stripe - `https://stripe.com/elements`

For consideration, it would be great to have you add your ideas to the [Ideas Board](http://ideas.woocommerce.com/forums/133476-woocommerce), which is where developers go to look for future plugin features and improvements. This is where the inclusion of Apple Pay and other payment request buttons came from. 

I'll close this thread for now with an Enhancement label

**Comment by JoelStickney** [comment]
I should have written back earlier, but @njeffers - the CVV can actually easily be removed via a WooCommerce Filter and even using this Stripe Plugin, the CVV is processed just fine, just use:

```
  add_filter('woocommerce_payment_gateway_supports', function() {
 	if ($feature == "credit_card_form_cvc_on_saved_method") {
 		return false;
 	}
 	else {
 		return $supports;
 	}
}, 11;
```

Note: This does produce a javascript error because React TRIES to mount to the CVC div that no longer exists, but it's not fatal. I'm sure this can be overridden somehow using something like:

```
wc_stripe_form.mountElements = function() {
      if ( ! $( '#stripe-card-element' ).length ) {
        return;
      }

      if ( 'yes' === wc_stripe_params.inline_cc_form ) {
        stripe_card.mount( '#stripe-card-element' );
      } else {
        stripe_card.mount( '#stripe-card-element' );
        stripe_exp.mount( '#stripe-exp-element' );
        //stripe_cvc.mount( '#stripe-cvc-element' );
      }
    }

```

But since everything works without that, I'm not even going to try to find out how / where to override the  default mountElements function though. HOPEFULLY, the developers give us a filter in the future to do so (which they really should give, at least, use developers a filter to disable both the PHP and JS rendering of the CVC / CVV divs.

PS. @dougaitken - the most well-known store I know of that doesn't require a CVV / CVC is Amazon - this is, of course, in the US, but I don't see why they'd have a separate fraud policy elsewhere. The reason they do it is one less reason the customer gives up and leaves. That's worth the risk to them, and the fact that Stripe doesn't require the CVC if set within the Radar settings means others feel the same.

**Comment by dougaitken** [comment]
> the most well-known store I know of that doesn't require a CVV / CVC is Amazon - 

Interesting! Is that on first purchase with a new payment card?

**Comment by njeffers** [comment]
@JoelStickney - thanks for your solution, and for your time in helping to explain.

**Comment by JoelStickney** [comment]
@dougaitken - It's anytime you add a card for any reason, these are the fields: Full Name, Card Number, Expiration. After a card has been saved the only time it'll ever ask you to re-verify is if you try to ship to a new address, and then they simply ask you to verify you know the card number.  

Screenshot: https://cloudup.com/cfMjYceijUn

@njeffers - No problem, I've been wanting to get rid of the CVV for awhile now as it's just one more barrier to payment when I know all of my customer's personally, and I don't ship anything (virtual product) so the extra security doesn't mean anything to me. 

I wanted to mention if you wanted ZERO JS errors, you could throw some JS onto the checkout and get the cvc element and then .remove() it. I tested this and it works just as well, but something about using JS to change things doesn't sit right with me so I dug into the input buffer until I found my solution. Unfortunately that solution comes with a a JS error. Honestly, the current BEST method would be to combine both approaches. Use the output buffer manipulation to add `display: none` to the div (that way the customer doesn't have to see anything even for a millisecond), then stripe.js will see the ID and mount it, and then you can remove it with JS.

I MAY end up doing that. I just like an all-PHP-based solution (a filter would be a godsend tbh).

**Comment by JoelStickney** [comment]
It took me about 30 minutes, but here are the three files you could replace in the Stripe plugin to accomplish this goal in the SAME way every other option is handled (via settings, I even included descriptions for users to understand the option) and I honestly think the developers should take this approach. I've coded my solution directly into the plugin as an option in the DB instead of a filter just like the rest of the settings. Check it out. :)

[Stripe-Disable-CVC.zip](https://github.com/woocommerce/woocommerce-gateway-stripe/files/3312265/Stripe-Disable-CVC.zip)

**Comment by JoelStickney** [comment]
@dougaitken - Do you think this is better served as an option in WooCommerce Settings, or as a boolean filter (in all of the applicable places)? I've never contributed to this plugin before, but I'd like to start.
