### ISSUE TITLE
Minor calculation error for stores with a WC base currency different than Stripe account

### ISSUE THREAD

**Issue by danielbitzer** [woocommerce/woocommerce-gateway-stripe#84]
The order meta `Net Revenue From Stripe` is incorrect when the order currency is different from the Stripe currency as Stripe returns all price fields in the Stripe account currency.

Also would you be prepared to add a hook after the payment request so that a few other fields stored in order meta. It would be super valuable for stores that that have this different currency setup.

**Comment by roykho** [comment]
Please provide more information as to what you mean by "incorrect". What are steps that we can test to reproduce this issue?

**Comment by danielbitzer** [comment]
See includes/class-wc-gateway-stripe.php:631

`update_post_meta( $order->id, 'Net Revenue From Stripe', $order->get_total() - $fee );`

This calculation use a value from the order object (in the order's currency) and the fee returned from Stripe (in the Stripe account currency). The 2 sources will not always be using the same currency. Often Stripe users will charge in USD and their Stripe account will be in their local currency.

**Comment by roykho** [comment]
I see what you mean however I am not sure why this would be a problem because usually the store owner would set the WC and Stripe to be the same currency. What is the use case for them to different?

But to resolve any discrepancies here, the "Net Revenue" can definitely be calculated based on Stripe's returned total and fees so it is not using one amount from WC and one from Stripe. Perhaps they even have a net calculation somewhere in the return but I have to check.

**Comment by danielbitzer** [comment]
Well I'm in Australia so I can only use Stripe in AUD (some countries can use multi-currency Stripe but not us) but I want to charge in USD as the the majority of my customers are US based. I agree most stores won't have this setup but its not uncommon.

Stripe do return a net calculation in their response. 

Because of this weird multi-currency setup it would be super helpful to also have the gross amount stored in a meta field and be able to do a multi-currency tax calculation at this point. Could you add an action hook after the response? 

Thanks for looking in to this!
