### ISSUE TITLE
I can't refund

### ISSUE THREAD

**Issue by kevin25** [woocommerce/woocommerce-gateway-stripe#871]
I can't input the amount to refund. The field is disabled.

<img width="1176" alt="Screen Shot 2019-05-20 at 11 19 03" src="https://user-images.githubusercontent.com/2909982/57996368-3536c680-7af1-11e9-90ad-7626fd0b1c9a.png">

#### Steps to reproduce the issue

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by BFTrick** [comment]
I struggled with this exact thing this morning.

When you click `Refund` a modal pops up and encourages you to configure some settings.

What's confusing is the QTY also switches from a number to an input box. And I didn't notice this for at least 10 minutes. I just kept clicking and clicking trying to adjust the greyed out field.

![Screen Capture on 2019-05-20 at 11-36-58](https://user-images.githubusercontent.com/1065372/58040831-b55e2b80-7af3-11e9-99f5-f998d33b8a4b.gif)

One solution would be to visually highlight those fields in some way. Maybe when you hover over the refund amount it highlights the item fields? Or when the modal loads the text inputs also have an animation?

When I see a new modal I don't assume anything in the original page changes. That's why it took me so long to figure out.

**Comment by dougaitken** [comment]
This was a change in Core 

woocommerce/woocommerce/issues/23379#issuecomment-484610279

https://github.com/woocommerce/woocommerce/wiki/3.6.x-notes-FAQ#the-refund-input-field-is-grayed-out-when-viewing-orders-and-trying-to-refund-items

@kevin25 - To refund correctly either increase the quantity of the product to refund it fully and restock the product, or you can partially refund using the Total field next to the product.

Closing as this isn't specific to Stripe
