### ISSUE TITLE
Styling banner for version < 4.1.14 shows on new installation

### ISSUE THREAD

**Issue by dougaitken** [woocommerce/woocommerce-gateway-stripe#891]
#### What I expected

See messages when are relevant to site when I first install Stripe and nothing previous to that.

#### What happened instead

The styling banner which was introduced in version `4.1.14` appears on a brand new installation - is there a way we can check for version updates and display if moving from <`4.1.14` only

Full message for searchability: 
`WooCommerce Stripe - We recently made changes to Stripe that may impact the appearance of your checkout. If your checkout has changed unexpectedly, please follow these instructions to fix.`

#### Steps to reproduce the issue

* Install a version of Stripe above 4.1.14 on a new WooCommerce site or a site which previously didn't have it installed
* Note upon activation that the banner is displayed. 
 * This causes confusion for Store owners, especially since it is an error notice ( #876 )

Can possibly be fixed in relation to #876 ? 

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by RadoslavGeorgiev** [comment]
#876 is easy to fix and I think it's clear that we'd like to switch to a standard notice, instead of an error one.

I also agree that the message should does not need to be shown on new installations, but that's not so easy to fix. I don't think there is a clear "flag", which indicates which version was used until now, if any. So the question becomes whether we need to keep on showing the message, considering that more than 60% of the install base is already running 4.2, or we could remove it?

cc @allendav @DanReyLop @v18
