### ISSUE TITLE
New profile created when attempting to update payment method

### ISSUE THREAD

**Issue by apmwebdev** [woocommerce/woocommerce-gateway-stripe#917]
#### Affected ticket(s)
2138111-zen

#### Synopsis
- Stripe + Woo Subscriptions issue where when a customer changes their payment method, it's creating an entirely new customer profile in Stripe.
- Merchant claims that we are making an incorrect API call when a customer updates their card:
> If the API call were sent using the new customer ID and the new source ID it would go through successfully. To prevent this in future the API call that should be sent when a customer updates their card information is the update customer call and not the create customer call. You can see the update customer call API reference here:
>
>https://stripe.com/docs/api/customers/update

- The subscriptions that were affected were imported, likely incorrectly
- Technically, we don't support imported subscriptions, but in this case, we will likely need to prove that it was an import error to close this.
- [Initial Slack conversation is here](https://a8c.slack.com/archives/C0D9EC4H0/p1562615036222500)

#### Specific Case

Here is a specific case, as they describe it:

> On 20 June she added a new credit card compared to the one she had before - for [redacted]
>
> When adding a new payment method (new card) on our website, this is creating a new customer ID with the same source ID despite the card being different. When updating a credit card it should do the opposite - create a new source ID with the same customer ID. Do you know why it would be doing the opposite of what its meant to be doing?
>
> If we can work out why then we may just solve this riddle. I'm not sure if it will fix all the problems, but this is certainly looking hopeful as far as understanding more about what is happening.
>
> Her customer ID initially was [redacted] and then it changed to [redacted] on 20th June when she updated to a new card. Her source ID stayed the same though - according to the logs - [redacted] (It should have done the opposite and changed the source ID and kept customer ID the same).

Here are the logs that we think relate to that situation for June 20th:
```
2019-06-20T02:30:18+00:00 DEBUG 
====Stripe Version: 4.2.0====
====Start Log====
sources/
====End Log====


2019-06-20T02:30:19+00:00 DEBUG 
====Stripe Version: 4.2.0====
====Start Log====
customers request: Array
(
    [email] =>[redacted]
    [description] => Name: [redacted]  Username: [redacted]
    [metadata] => Array
        (
        )

)

====End Log====


2019-06-20T02:30:20+00:00 DEBUG 
====Stripe Version: 4.2.0====
====Start Log====
customers/[redacted]/sources request: Array
(
    [source] => [redacted]
)

====End Log====


2019-06-20T02:30:22+00:00 DEBUG 
====Stripe Version: 4.2.0====
====Start Log====
customers/[redacted] request: Array
(
    [default_source] => [redacted]
)

====End Log====


2019-06-20T02:30:23+00:00 DEBUG 
====Stripe Version: 4.2.0====
====Start Log====
customers/[redacted]/sources request: Array
(
    [limit] => 100
)

====End Log====
```

#### Question
Is there a way to verify that the new Stripe customer profiles being created when people attempt to update their payment methods are a result of some piece data being corrupted or missing, and not a bug, as the user claims?

Specifically:
- We would like to determine where in the Stripe plugin code the API call is made when a customer updates their card. Our theory is that there is a missing piece of data that wasn't properly imported, which the Stripe plugin uses to determine which type of API call to make.
- Can someone here help me work through the code and see if this theory holds up?

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by fevered** [comment]
Additional information for this bug: Orders are failing 1 minute before the successful recurring transactions, and this is happening on accounts where there are duplicate stripe customer IDs. After the orders fail, they are being marked as completed

**Comment by allendav** [comment]
@DanReyLop - can you take a look at this? I've tentatively set it to High and 4.3.0 for now. Thank you!

**Comment by thenbrent** [comment]
> Is there a way to verify that the new Stripe customer profiles being created when people attempt to update their payment methods are a result of some piece data being corrupted or missing, and not a bug, as the user claims?

Yes. Steps to confirm if this is a bug:

1. open your test store in a private / incognito tab so you are not logged in
1. purchase a new subscription product with Stripe and create a new WP/WC user for this purchase (this will create a new customer and source at Stripe)
1. Confirm in the [**Stripe > Customers** dashboard](https://dashboard.stripe.com/test/customers) that a new customer was created for that user
1. in a separate browser window, where you are logged in as an admin, confirm the customer and source ID are set in WP/WC on the [**WooCommerce > Edit Subscription**](https://docs.woocommerce.com/document/subscriptions/add-or-modify-a-subscription/#section-8) screen
1. go back to the private / incognito tab and [change the payment method](https://docs.woocommerce.com/document/subscriptions/customers-view/#section-11) as the subscriber
1. in the browser window logged in as an admin, open the **WooCommerce > Edit Subscription** screen again to check if the customer  ID set in WP/WC is the same or has changed
1. Check in the [Stripe dashboard](https://dashboard.stripe.com/test/customers) if a new customer was created for that user (each customer's creation date/time is available there)

I just tested this with Stripe 4.2.5, and didn't see a duplicate customer created.

As this behaviour doesn't occur with a subscription purchased normally using Stripe, and given we're not seeing reports of this from other customers, it's fair to say it's a result of data not imported correctly rather than a bug. Especially because I know this behaviour would occur if importing a subscription not the `_stripe_customer_id` meta data not being set correctly against the subscription. That is the most likely cause.

**Comment by DanReyLop** [comment]
Adding to that, my own conclusion by looking at the code is:
- We aren't doing anything wrong, we are calling `POST /customers/[CUSTOMER_ID]` when adding a new source, which is the correct endpoint to use. That won't create a new customer object, because the customer ID is in the URL.
- The problem in this specific case is probably with [this logic](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/class-wc-stripe-customer.php#L199-L204). Could be that the `_stripe_customer_id` meta on the user exists, but somehow that doesn't correspond to a valid Stripe customer anymore. In that case, a new customer object will be created in Stripe, and the source will be attached to it.
