### ISSUE TITLE
Remove customer-facing Stripe brand identification

### ISSUE THREAD

**Issue by dechov** [woocommerce/woocommerce-gateway-stripe#933]
#### Affected ticket(s)

None, to my knowledge.

#### What I expected

Front-end brand identification that is relevant and meaningful to customer rather than merchant, which would include "Visa" and "Discover" but not include "Stripe".

#### What happened instead

"Stripe" mentioned in default title and description on the Checkout screen:

<img width="341" src="https://user-images.githubusercontent.com/1867547/62158109-b9b97880-b2dc-11e9-8631-1756c070f141.png">

#### Steps to reproduce the issue

With the Stripe payment method enabled and without the gateway title or description having been modified, go to Checkout and confirm mention in payment method of "Stripe" (payment processor only merchant interfaces with).

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by thenbrent** [comment]
Closing this one due to lack of recent activity. While it is valid UX issue, it's not been a priority in the last 4 years, and unlikely to become one soon. That said, as we look to move the default experience to the Payment Elements / UPE, we can factor in better defaults for that (it already uses "Popular payment method" and can move to just use the payment method name e.g. "Credit Card".)
