### ISSUE TITLE
Gateway not using Users’ Billing Address fields for a saved card

### ISSUE THREAD

**Issue by hannahswain** [woocommerce/woocommerce-gateway-stripe#94]
Original forum question: https://wordpress.org/support/topic/gateway-not-using-users-billing-address-fields-for-a-saved-card/

When a user updates their Billing Address and goes to checkout, Stripe is still using the Billing Address attached to the saved card on Stripe’s servers and not the updated Billing Address from the checkout fields or from their saved Billing Address fields on their profile.

This is how we stumbled upon this bug.

1) We were testing Stripe’s settings of “Decline: Charges that fail zip code verification” (In Stripe Account Settings under General).

2) We checked out with an incorrect ZIP and Address associated to a new credit card, successfully while that option was unchecked. The new credit card was saved for future use.

3) We went to the user’s Billing Address and updated it with new correct fields.

4) In Stripe we turned on “Decline: Charges that fail zip code verification.”

5) We tried to checkout again using the saved card. The new correct billing address fields were populated into the checkout page. The payment should have completed successfully since the updated address fields were given, but the payment still failed. In Stripe, a new Blocked payment appeared with the old address fields associated.

Another disconnect: The email that auto fires for a failed payment showed the order having the new Billing Address and using the saved credit card.

I am reporting this issue because this gateway plugin needs either some copy or a hard restriction on the billing address fields. If a user is checking out with a saved credit card, it should not let them fill in or change the address fields. Or on the other hand, if a user is updating their billing address fields under My Account, there should be some copy stating the saved card on file will not reflect billing address changes, then instruct them to delete and readd the card.

485672-zd-woothemes

**Comment by roykho** [comment]
So this one definitely will need some ideas in terms of UX. WC by default separates billing address section and payment section. So it is easy for customers when updating billing address to think that updates the payment method that is saved on file when it doesn't. But if they go to the payment method section, they don't have option to update the card on file. They can only delete and add again. But even adding, there are no fields for billing address. So if they had an account on Stripe before, that will be used to tie in with the newly added card which may or may not be what they're expecting.

So either we give a clear message when updating the billing address fields that it does not  affect the addresses on the saved cards OR do that plus add billing address fields to the saved card section. Note they can have more than one saved card and each card could potentially be billed to different people/location.

cc @mattyza

**Comment by mattyza** [comment]
Is there any rule around updating the billing address on Stripe's end, before attempting to checkout using a saved card?

**Comment by roykho** [comment]
There are no update process/logic for updating address. The reason being a saved card's billing address could be different from the current checkout address. So there would be unintentional change if we just assume to update the saved card billing with the one checking out.

So this update/change must happen only when they go to My Account.

**Comment by mattyza** [comment]
Cool. So when an address is changed in My Account on WooCommerce, we can update the address in Stripe? Or the other way around?

**Comment by roykho** [comment]
It can, however the update address in My Account is separate from the payment method area. That is why "Needs Design" was tagged because we potentially need to add address fields per payment method.

Or we can compromise for now and just assume the billing address is the address for all payment methods that are saved? Another words when they update the billing address in My Account, we just update all payment methods in Stripe with the newly updated billing address?

**Comment by mattyza** [comment]
> Or we can compromise for now and just assume the billing address is the address for all payment methods that are saved? Another words when they update the billing address in My Account, we just update all payment methods in Stripe with the newly updated billing address?

Yep, I'd say that's a fair assumption, @roykho. Let's do that.

**Comment by roykho** [comment]
Notice added to customers when they change the billing address. In 4.1 branch.

**Comment by wscheinhart** [comment]
I tested with the 4.1 branch and don't get the notice when I change the billing address in My Account. I have to say that I use WooCommerce Checkout Field Editor Pro plugin, so this may play a role, but it is a often used plugin.

I processed an initial order and saved CC with billing name/address for person A. Then I changed the billing name/address to person B in My Account. When I place another order it shows correctly person B as billing name/address and I use the previous saved CC from person A. I was expecting an error, but Stripe processed the charge and shows in the event log for that charge the billing name/address for person B as info but uses the resource attached to person A. So, essentially a different person uses someone else's previous stored CC - not good.

**Comment by roykho** [comment]
@wscheinhart here is the notice you're supposed to see when you update the address in my-account http://cld.wthms.co/fu4CmF

**Comment by wscheinhart** [comment]
Sorry, but your hook function show_update_card_notice( $user_id, $load_address ) in class-wc-gateway-stripe.php never fires - at least on my site. The only other place where that hook is used is in the WC Subscription plugin and there it fires.

When I put the same hook for 'woocommerce_customer_save_address' into a snippet it also works. Not sure why the hook is not registered or fires in my configuration but it does not even call the function show_update_card_notice(). 
Suggestion for the message itself - I would change it from 'error' to 'notice' as it is a less critical info for user otherwise they think something went wrong. I would also check if $load_address == 'billing' so the message does not show for shipping address. Lastly, I would not add an in-line style for the href as usually everyone's theme handles that, but add a class if anything so people can use CSS if they want to style beyond default theme.

**Anyway, the real issue though for me is why the payment is processed when the billing name/address has changed and now uses the previous resource for the stored CC. You can't count on the user to make sure they do change the CC and re-add it after billing address changes. This is also an issue when I place a new order and just enter a different billing address than the saved one, I can still use the previously stored CC with the other person's billing address - that really should not be processed but rather show and error message for the user.**

**Comment by roykho** [comment]
@wscheinhart not entirely sure I follow the flow of your issue. We have not changed anything in that regards. Are you assuming we have intentionally changed something in 4.1 branch that affects this? Or is this already happening in the public release?

So why would a customer change their information to a person they don't know?

**Comment by BioResonance** [comment]
This is probably happening not only with 4.1. I only started to test these scenarios now after the change for billing address update info was implemented. Why does it matter? It is an issue that I believe needs to be fixed.

I can give you two examples where the billing name/address, or better the CC info is not identical with the user info - when I pay for my children or spouse online then it is my billing name/address while the account user info is from my children or spouse. Or, I have two CC, one personal and one business both have different billing addresses and I use them both on the same account depending on if I want to charge a purchase to my business or private.

I hope you would agree that some check needs to happen in the software (plugin or stripe) that the name/address info associated to a saved resource has to match the billing name/address info for a payment request. If there is no match the payment needs to be rejected and the user should see an error message e.g. "payment method used does not match selected billing name/address".

As I said, even if the user sees the notice about re-adding payment method upon billing address change, there is no guarantee they won't miss or forget it. That would still not address the case when I enter a different billing info on a new purchase and select a saved CC with a different billing info it was saved under.

**Comment by roykho** [comment]
@wscheinhart what you're proposing if I understand correctly will require the save cards to each have its own individual address attached instead of using the general billing address of the customer. That is what this OP was all about in fact. But ti requires substantial amount of work to make that happen and we have not ever had any complaints about this thus far. So it would be quite low on our priority to make that happen. Thus we took one step forward by adding the notice for now. I hope that is more clear.

**Comment by wscheinhart** [comment]
I understand the intent of the notice, but it won't help when I enter a different billing info for an order and then select a saved CC that has a different billing info associated with.

I also understand the amount of work involved when implementing a complete solution. 

However, I was looking for an interim solution where at least the saved info for a resource is checked against the presented billing info and if that does not match an error message is displayed and payment is not processed.

**Comment by brandwaffle** [comment]
@roykho I just ran into this issue and while I'm not sure what the overall effort would be, I think the following workflow would be ideal and should minimize dev effort vs other approaches:

- Customer updates billing address in their My Account tab
- Billing address is assumed to be correct for all cards on file, i.e. Stripe Sources
- Iterating through all Stripe Sources for a user, update the owner's address per this API doc https://stripe.com/docs/api#update_source-owner

At first glance, it seems this would update the source to reflect the new address, enabling the order to be processed with the same source ID. I'm not sure this is 100% possible though, since it's not clear to me if a Source can be updated like a Card, and from what I can see the plugin stores Sources rather than Cards.

I will also add the use-case for this was a customer who was asked to update their payment info and who responded by updating the billing address in My Account. The card expiration is still well in the future and the number has not changed, so there is no need to have someone re-enter the card number from a security perspective.

In terms of associating each card with its own billing address, that might ultimately be the right solution here. I also have a work card with a different billing address than my personal card, and regularly sign up for both personal and work subscriptions to the same products.

Depending on overall desire for the feature and effort required, we might be able to pitch in with a pull request or two, assuming we can agree on an approach.
