### ISSUE TITLE
Payment Request provide defaults to pass checkout validation

### ISSUE THREAD

**Issue by grahamsmith** [woocommerce/woocommerce-gateway-stripe#950]
#### What I expected

I have a plugin that makes use of the filter `woocommerce_checkout_fields` that adds in an additional dropdown field:

```
$fields['billing']['foo'] = array(
        'type' => 'select',
        'input_class' => array('input-text',),
        'required' => true,
        'label' => __('Error message'),
        'options' => $optionsArray
    );

```

When using the Payment Request button via cart page (I have disabled for products), I was expecting the ability to provide default values to my custom field as I _believe_ Payment Requests do not currently support extra custom fields.

Questions:

- Am I right in my knowledge that custom fields on payment requests are not currently supported?
- Is there a preferred work around for adding required custom fields?

#### What happened instead

When an Apple Pay request was made the process resulted in an error message stating that  the required field was not completed.

#### Steps to reproduce the issue

Add extra field using a method below via plugin/functions

```
<?php

add_filter('woocommerce_checkout_fields', 'add_foo_to_checkout');
function add_foo_to_checkout($fields)
{
    $optionsArray = array();
    $optionsArray['bar'] = "bar";


    $fields['billing']['foo'] = array(
        'type' => 'select',
        'input_class' => array('input-text',),
        'required' => true,
        'label' => __('Foo'),
        'options' => $optionsArray
    );

    return $fields;
}

?>
```

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by v18** [comment]
Related to #829, #1338, #1146, #1401

**Comment by asumaran** [comment]
@v18 I can reproduce this issue consistently. How are we planning to address this?

- ~To add a "default" prop to allow to pass a default value?~
  - ~In the case we do this. We need to confirm if the behavior will play well with the "required" prop since the input will always have a value therefore input validation will never fail in the Cart page. On the checkout page the input will fail only if the user manually deletes the default value.~

edit: 

I just noticed we already support the `default` prop.

https://github.com/woocommerce/woocommerce/blob/0df1d3ef64660be4534572390c5fce5471e39e41/includes/wc-template-functions.php#L2685

I'll make sure the default value is used at the moment the Payment Request button is used on the Cart page
