### ISSUE TITLE
Order: SOFORT charge.succeeded not recognized

### ISSUE THREAD

**Issue by TobiasThulke** [woocommerce/woocommerce-gateway-stripe#951]
#### What I expected
The event charge.succeeded was triggered in Stripe. Wordpress accepts the triggered event and marks the order with the status "Finished". A comment is added to the order, "Stripe load completed (load ID: XXXX)". 

#### What happened instead
The event charge.succeeded was triggered at Stripe. Wordpress accepts the triggered event only partially and marks the order with the status "Finished". There are orders that have already been paid and are not noted within Wordpress. Stripe successfully executed the call. There are no log entries for analysis. 
The whole thing leads to an inconsistent order overview, which entails a considerable additional effort in the maintenance of the orders. 

#### Steps to reproduce the issue
Not known, on what the problem depends. The orders i compared looks all the same. On some orders, the plugin trys to create another charge, after the charge.succeeded event got triggered. Stripe logs an 409 error then. Even don't know why this happens.

**Comment by allendav** [comment]
Hi @Traxstar - we'll try to get to the bottom of this. Would you reply with:

o the exact version of the Stripe extension you are using (you can find this in wp-admin > Plugins)
o the exact version of WooCommerce you are using (same place)

The message "Stripe load completed" doesn't appear in our Stripe extension, so I am wondering if another plugin is interfering here. Has this ever worked for you, and if so when did it stop working?

**Comment by Traxstar** [comment]
Hi @allendav - good to here from you that quick. 

WooCommerce Version: 3.6.5
WooCommerce Stripe Gateway Version: 4.2.3

The message "Stripe load completed" was a translation mistake of mine, because my Backend is in German. So the message that is set as a comment in the orders that got successfully processed is "Stripe-Belastung abgeschlossen (Belastungs-ID :XXXXX). 

So the problem in detail is not the comment or so, it is the fact that some of the SOFORT Orders don't receive the callback from the API of Stripe, even if i can see them as successfully executed in the logs of stripe. For me this means that there is something internaly wrong handeling this callback.

**Comment by Traxstar** [comment]
Hi @allendav 
is there any progress right now? This bugs realy slows my productivity if i need to double check any  order in my shop. Would be awesome if there would be some kind of feedback - thanks!

**Comment by allendav** [comment]
Hi @Traxstar - we are focusing on SCA for Stripe right now but will try to get to this after that
