### ISSUE TITLE
Successful order was marked as Failed in Woo: "Stripe SCA authentication failed."

### ISSUE THREAD

**Issue by fhaps** [woocommerce/woocommerce-gateway-stripe#980]
#### Affected ticket(s)

2305087-zen

#### What I expected

If an order is successful and payment for it is received via Stripe, I expect WooCommerce to reflect this by marking the order as `Processing` or `Completed`.

#### What happened instead

An order was received via Stripe, but WooCommerce marked it as `Failed`. Debug was disabled at the time, but the order came in with this note:

```
Stripe SCA authentication failed. Reason: The provided source has failed authentication. You can provide source_data or a new source to attempt to fulfill this PaymentIntent again. Order status changed from Pending payment to Failed.
```

![](https://cld.wthms.co/mXPZpU+)
Image Link: https://cld.wthms.co/mXPZpU

The error message in the note is similar to the ones highlighted in issue #902, closed a couple months back. I'm wondering if this might be related.

#### Steps to reproduce the issue

Haven't been able to reproduce reliably so far.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by RadoslavGeorgiev** [comment]
> Haven't been able to reproduce reliably so far.

Same here, at least not reliably. At one point I was able to fail the SCA authentication, which resulted in a failed order, but then I tried again, resulting in a separate, successful order. I cannot understand what I did though: Around 100 tries later, instead of getting a second order, the original order is getting marked as processing and receives the order notes. 

> If an order is successful

The string `Stripe SCA authentication failed. Reason: %s` can only appear in order notes in two cases:

1. Failed intent webhook: This one definitely indicates that the payment was not successful.
2. After the SCA modal, the intent enters the `requires_payment_method` status. This status would only appear once the SCA challenge is denied/failed/rejected.

To understand what's happening, let's request screenshots of pair(s) of:
- An order, which is marked as failed in WooComerce, but the customer claims to be successful.
- A screenshot of the payment in Stripe Dashboard, corresponding to that payment.

At the very least, this would clear my suspicion that the order that was successfully paid in Stripe is not the dashboard from the screenshot above.

**Comment by fhaps** [comment]
Quick update to say I have requested the screenshot from the customer. Will update here once they get back to us.

**Comment by fhaps** [comment]
User has shared the following images.

The charge does look to be for order #210245, the one pictured in the Woo Dashboard above. 

![](https://cld.wthms.co/edwNuS+)
Image Link: https://cld.wthms.co/edwNuS

![](https://cld.wthms.co/ocPpLA+)
Image Link: https://cld.wthms.co/ocPpLA

![](https://cld.wthms.co/C3WOf1+)
Image Link: https://cld.wthms.co/C3WOf1

![](https://cld.wthms.co/Pje5Yn+)
Image Link: https://cld.wthms.co/Pje5Yn

**Comment by fhaps** [comment]
@RadoslavGeorgiev  I noticed the order note was recorded at the same time that the first failed attempt was logged in Stripe. 

So it looks like the order wasn't updated once the credit card processed correctly in Stripe. It only recorded the first failed attempt.

![](https://cld.wthms.co/PmE91t+)
Image Link: https://cld.wthms.co/PmE91t

![](https://cld.wthms.co/4Mruk1+)
Image Link: https://cld.wthms.co/4Mruk1

**Comment by RadoslavGeorgiev** [comment]
@fhaps I see that the error corresponds to the first failed payment, but I could still not reproduce it.  I tried multiple failed SCA challenges, and a successful payment with the same and/or another card, but it always worked properly.

The only thing that makes me suspicious from the screenshots is the __highest__ risk score of 98, but I am not sure how it would've affected the process here. I suggest leaving the debug logs on and investigating them if such an issue happens again.

**Comment by fhaps** [comment]
@RadoslavGeorgiev Thanks for your help looking into this. Might have been a one-off thing, maybe.

Asked the customer to keep debug enabled, in case this happens again. Closing this thread for now.
