### ISSUE TITLE
SCA with hash url #confirm-pi- don't work with angularjs

### ISSUE THREAD

**Issue by auban** [woocommerce/woocommerce-gateway-stripe#987]
#### What I expected

Checkout page confirm order with stripe credit card 4000000000003220 (3D Secure SCA).

#### What happened instead

The modal 3D Secure 2 authentication for a transaction not open.

In conjuction with angularjs the hash url not work.
Angularjs add a forward slash just after the hash like so #/confirm-pi-

Is it possible to change this line 431:
`var partials = window.location.hash.match( /^#?confirm-pi-([^:]+):(.+)$/ );`

Example with this:
`var hash_val = window.location.hash;
var partials = hash_val.substring(hash_val.indexOf('confirm-pi-')).match( /^confirm-pi-([^:]+):(.+)$/ );`

Regards,

Auban

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by v18** [comment]
Hi @auban - can you let me know what your environment is that requires Angular when using the Stripe payment gateway? For example, do you have a plugin or theme that uses Angular during checkout?

**Comment by auban** [comment]
Hi, yes I use the plugin wp-ng and I use angularjs during checkout. Today I path every time the js in stripe gateway plugin.
Thanks for resolve this problem.
Auban

**Comment by thenbrent** [comment]
Closing this due to lack of recent activity, and the small surface impact. It appears to only impact sites with Angular running for checkout (or using [wp-ng](https://href.li/?https://github.com/RedCastor/wp-ng) which appears no longer active). If it's still an issue and you haven't found a suitable workaround, please reopen to confirm; however, it will remain low priority even once reopened.
