### ISSUE TITLE
SCA: prettify link when order has already been paid for and user is coming to authenticate a previous payment attempt that required authentication

### ISSUE THREAD

**Issue by v18** [woocommerce/woocommerce-gateway-stripe#994]
steps:
1. customer pays for subscription
2. subscription renewal goes through
3. renewal payment  has error `authentication_required`
4. customer gets an email to come back to authenticate
5. user ignores email
6. user pays for the renewal in another way
7. user comes back to authenticate payment from #4

**Comment by RadoslavGeorgiev** [comment]
I need more details for this. I performed the steps you mentioned (#6 was done through the "Pay for Order" button on the subscription page), and I don't see a link to modify. Because the order is already paid, I see the following message, which is defined [here](https://github.com/woocommerce/woocommerce/blob/master/includes/shortcodes/class-wc-shortcode-checkout.php#L115):

![image](https://user-images.githubusercontent.com/5311119/68463898-4519a280-0218-11ea-9108-d924da791f8f.png)

Do you have the text of the message in mind?

In any case, the current state might not be perfect UI-wise, however this is not a high-priority bug either. I'm, changing the label and moving to `4.3.2`.

**Comment by v18** [comment]
Removed this from the next milestone since it's low priority - can be handled if there are complaints or if we review the flow later.

**Comment by thenbrent** [comment]
Closing this one due to lack of recent activity.
